show_stage("龙湾门大堂.png", "龙湾门大堂")
set_bg_mat("ImgPaperFold")
play_bgm("Music/回忆.wav")
light_scene(0.2)

local longwanying = actor("龙万莹")
local laosong = actor("老宋")
local dongfangsha = actor("东方鲨")
local dongfangzhouyu = actor("东方骤雨")
local dongfangtun = actor("东方豚")
local dongfangli = actor("东方狸")
local situ = actor("司徒来也")

set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
longwanying:setPos(600, 75)
longwanying:face_right()
laosong:setPos(900, 75)
laosong:face_right()
dongfangsha:setPos(300, 75)
dongfangsha:face_right()
dongfangzhouyu:setPos(2000, 75)
dongfangzhouyu:face_left()
dongfangtun:setPos(2300, 75)
dongfangtun:face_left()
situ:setPos(2600, 75)
situ:face_left()
dongfangli:setPos(2900, 75)
dongfangli:face_left()

--先一起走过去
dongfangzhouyu:movetoX(1200)
wait_twn(dongfangtun:movetoX(1500), dongfangtun:daze())

dongfangzhouyu:say("你这个贱人竟然与厨子私通，还与外人一起图谋我龙湾门基业。")
laosong:say("东方骤雨，嘴里放干净点。当年我本与莹儿两情相悦，若不是你见色起意，害我被追杀，你怎能强娶莹儿。")
dongfangzhouyu:say("原来是你，你竟然还活着。")
longwanying:say("东方骤雨，当年我怀有鲨儿，得到你呵护备至的照顾，本想有了依托，委身于你。")
longwanying:say("那曾想，我食为鲜一门皆因你的陷害而遭受不幸……")
dongfangzhouyu:say("你这个贱人居然早已知晓……还惺惺作态与我扮演恩爱夫妻……")
dongfangzhouyu:say("如今你们一家又落入我的手中，我是先送你这个吃货儿子，还是你奸夫下黄泉呢？")
dongfangtun:say("大哥……想不到你竟然是……")
dongfangsha:say("我……我……")
longwanying:say("我无话可说，你让我们离开吧。")
dongfangzhouyu:say("你！你住嘴！先让我清除孽种！")
shake_stage(20, 1)
dongfangzhouyu:jumpTo(400, 75)
longwanying:flip()
laosong:jumpTo(300, 75)
wait_twn(dongfangsha:jumpTo(100, 75), laosong:offsetY(-200), laosong:daze())
stop_bgm()
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
laosong:say("孩儿……照顾好你娘……")
dongfangzhouyu:say("你这个野种！你这个奸夫！")
longwanying:say("宋郎！宋郎！")
laosong:movetoY(-600, 5000)
kill_disciple("老宋")
shake_stage(20, 1)
wait_twn(dongfangsha:jumpTo(200, 75), dongfangsha:daze())
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
dongfangsha:say("爹……为何……")
wait_twn(dongfangzhouyu:offsetY(-200), dongfangzhouyu:daze())
dongfangzhouyu:say("啊——（一把蛟龙枪刺穿了东方骤雨身体…）")
dongfangzhouyu:movetoY(-600, 5000)
kill_disciple("东方骤雨")
shake_stage(20, 1)
wait_twn(dongfangtun:jumpTo(400, 75), dongfangtun:standfront(), dongfangtun:daze())
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
dongfangtun:say("你不是我大哥……（赶上一枪刺死了东方鲨）")
longwanying:say("豚儿……你……你竟然杀了鲨儿……你的亲哥哥啊！")
dongfangsha:say("二弟……如果让我选……我也不想……")
hide_all_stage_bubble()
dongfangsha:movetoY(-600, 5000)
kill_disciple("东方鲨")
wait_twn(situ:movetoX(1200), situ:daze())
longwanying:flip()
situ:say("这……这算什么事儿啊……")
wait_twn(dongfangli:movetoX(1500))
situ:say("这样的事情他不知道也好，何尝不是“无知是福”呢……")
dongfangli:say("“无知是福”吗？还真是伪善啊……")
hide_all_stage_bubble()
wait_twn(dongfangli:flip(), dongfangli:movetoX(3000))
stage_narration("门外，一个少年的背影轻盈地离开")
if leave_menpai("东方狸") then
  pop_tip("<color=#ff7a00>东方狸</color>离开了龙湾门")
  play_sfx("Tip/Tip1.wav")
end
destroy_menpai("食为鲜")
set_menpai_leader("龙湾门", "东方豚")

hide_all_stage_bubble()

black_scene(0.25)
set_flag("完成食为鲜灭亡结局")
hide_stage()
light_scene(0.25)
