show_stage("龙湾门大堂.png", "龙湾门大堂")
light_scene(0.2)
play_bgm("Music/回忆.wav")

local dongfangzhouyu = actor("东方骤雨")
local longwanying = actor("龙万莹")
local dongfangsha = actor("东方鲨")
local dongfangtun = actor("东方豚")
local dongfangli = actor("东方狸")
local situ = actor("司徒来也")
local laosong = actor("老宋")

--初始化位置和朝向
dark_all_actors()
dongfangzhouyu:setPos(400, 75)
dongfangzhouyu:face_right()
longwanying:setPos(700, 75)
longwanying:face_left()
dongfangsha:setPos(1000, 75)
dongfangsha:face_left()
dongfangtun:setPos(1300, 75)
dongfangtun:face_left()
dongfangli:setPos(2500, 75)
dongfangli:face_left()
situ:setPos(1500, 75)
situ:face_left()
laosong:setPos(-400, 75)
laosong:face_right()

situ:say("你们东方家大势已去，不要再垂死挣扎了！")
dongfangtun:say("我们……我们就这么败了吗？")
dongfangsha:say("该死！可恶！这世间还有那么多珍馐没享受，新来的那个厨子手艺刚刚才有了点意思……")
dongfangtun:say("大哥，这都什么时候了，还想着这些？")
situ:say("你不也是？若不是只顾着捡掉落的香囊汗巾，如何会被我们追上？")
dongfangsha:say("可不是？逃命还不忘带着女人用的东西，也不知什么癖好……")
dongfangtun:say("你侮辱我可以！但我绝对不容许你玷污我的挚爱之物！")
situ:say("又是为了……，行吧……我都懒得辩解……")
dongfangzhouyu:say("逆子！你们一个个垂头丧气、哭哭啼啼，都像什么样子！")
situ:say("东方骤雨，虎焰龙湾的仇恨，就让我来了结吧……")
dongfangzhouyu:say("小子，今番败了，非是你们强势！不过是我们东方家内讧，让外人占了便宜而已。")
longwanying:say("夫君……")
dongfangzhouyu:say("夫人，你说是不是如此？")
longwanying:say("夫君这话是什么意思？妾身如何听不明白……")
dongfangzhouyu:say("夫人，不必瞒了，事到如今，还不肯说实话吗？")
longwanying:say("……")
dongfangzhouyu:say("想我东方家兴盛一时，临了竟是葬送在这几个不知是何人的野种手中，当真可笑！")
dongfangsha:say("什么野种？")
dongfangtun:say("爹？您……")
longwanying:say("夫君此言，当真不顾及我们的夫妻情分了吗？")
dongfangzhouyu:say("哼，你瞒着我与奸夫私通之时，又可曾想过顾及夫妻情分？说吧，这些孩子之中，到底谁不是我东方家的后？")
longwanying:say("这么说，这些年你迟迟不立继承人，导致他们几个兄弟相争，竟是这样的原因？")
dongfangzhouyu:say("龙湾门岂可落入外人之手？")
longwanying:say("你当真心狠……")
dongfangzhouyu:say("若非你水性杨花，我又如何愿意出此下策？这些年可给了你不少坦白的机会。这几个孩子，我亦愿意视如己出。")
longwanying:say("哼！虚伪之言！")
dongfangzhouyu:say("如今东方家败落，我无话可说，只希望终是能解开心中疑惑。说吧，究竟哪个孩子不是我的！！")
longwanying:say("你还是杀了我吧！")
dongfangzhouyu:say("你当真以为我不敢？")
longwanying:say("你还有什么不敢之事？我本同宋郎两情相悦，若不是你的出现，我又怎么会沦落至此？")
dongfangzhouyu:say("……")
longwanying:say("当初食为鲜被陷害谋杀食客，宋郎被追杀，便再无消息。我本以为宋郎已死，想一死了之，奈何竟有了身孕……")
dongfangtun:say("这么想的话，那不就是大哥——")
dongfangzhouyu:say("果然是你这个吃货！")
dongfangsha:say("什么？什么？")
longwanying:say("若非我四处求人打听，哪里会得知真相？真是好笑，这么多年，竟却没想到最险恶的竟是枕边人！")
dongfangzhouyu:say("可我对你这些年倒也真心实意，你怎么敢……")
longwanying:say("有什么敢不敢的！你不知道的事情还多着呢！")
dongfangzhouyu:say("你！你住嘴！先让我清除孽种！")
shake_stage(20, 1)
dongfangzhouyu:jumpTo(900, 75)
longwanying:flip()
wait_twn(dongfangsha:offsetY(-200), dongfangsha:daze())
stop_bgm()
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
dongfangsha:say("爹…为…为何杀我…")
dongfangzhouyu:say("因为你，你是个野种！")
dongfangsha:say("可…晚上的肘子…还没…吃完…")
dongfangsha:movetoY(-600, 5000)
kill_disciple("东方鲨")
shake_stage(20, 1)
wait_twn(laosong:jumpTo(800, 75), laosong:daze())
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
laosong:say("东方老贼！你给我去死吧！")
dongfangzhouyu:flip()
dongfangzhouyu:say("啊——是你！")
laosong:say("当年夺我妻者是你！如今又夺我亲儿性命！不得好死！")
wait_twn(dongfangzhouyu:offsetY(-200), dongfangzhouyu:daze())
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
dongfangzhouyu:say("啊——（一把菜刀砍在东方骤雨头上，血顺着他的眉眼流下来，像是一道菜…）")
dongfangzhouyu:movetoY(-600, 5000)
kill_disciple("东方骤雨")
longwanying:say("宋郎！小心！")
shake_stage(20, 1)
wait_twn(dongfangtun:jumpTo(1000, 75), dongfangtun:daze())
dongfangtun:say("大胆逆贼！（赶上一枪刺死了老宋）")
longwanying:say("宋郎！你……你竟然杀了宋郎！")
situ:say("这……这算什么事儿啊……")
laosong:say("莹儿，我不在乎你之前都经历了什么！也不在乎你这些年跟了什么人！终是我对不住你…")
hide_all_stage_bubble()
laosong:movetoY(-600, 5000)
kill_disciple("老宋")
wait_twn(dongfangli:movetoX(1700))
situ:say("这样的事情他不知道也好，何尝不是“无知是福”呢……")
dongfangli:say("“无知是福”吗？还真是伪善啊……")
hide_all_stage_bubble()
wait_twn(dongfangli:flip(), dongfangli:movetoX(3000))
stage_narration("门外，一个少年的背影轻盈地离开")
add_player_item("龙蛇袍", 1)
-- add_player_item("骤雨寒冰拳", 1)
destroy_menpai("龙湾门")

hide_all_stage_bubble()

black_scene(0.25)
set_flag("完成龙湾正常结局")
hide_stage()
light_scene(0.25)
