show_stage("龙湾门大堂.png", "龙湾门大堂")
light_scene(0.2)
play_bgm("Music/回忆.wav")

local dongfangzhouyu = actor("东方骤雨")
local dongfangtun = actor("东方豚")
local dongfangli = actor("东方狸")
local laosong = actor("老宋")
local longwanying = actor("龙万莹")
local dongfangsha = actor("东方鲨")
local situ = actor("司徒来也")

--初始化位置和朝向
dark_all_actors()
dongfangzhouyu:setPos(700, 75)
dongfangzhouyu:face_right()
dongfangtun:setPos(400, 75)
dongfangtun:face_right()
dongfangli:setPos(-500, 75)
dongfangli:face_right()
laosong:setPos(2600, 75)
laosong:face_left()
longwanying:setPos(2000, 75)
longwanying:face_left()
dongfangsha:setPos(2300, 75)
dongfangsha:face_left()
situ:setPos(-500, 75)
situ:face_right()

--先一起走过去
longwanying:movetoX(1000)
dongfangsha:movetoX(1300)
wait_twn(laosong:movetoX(1600), laosong:daze())
longwanying:say("东方骤雨，二十年前你以奸计陷害食为鲜，害得我们一家离散之仇，今日一并了结。")
dongfangzhouyu:say("原来你这个贱人早已知晓，与厨子私通，还与外人一起图谋我龙湾门基业。")
laosong:say("东方骤雨，嘴里放干净点。当年我本与莹儿两情相悦，若不是你见色起意，害我被追杀，你怎能强娶莹儿。")
dongfangzhouyu:say("原来是你，你竟然还活着。")
longwanying:say("如今你走投无路，快快自尽，顾及我们几十年夫妻情分上，我们可以留你一个全尸。")
dongfangtun:say("母亲，这……这究竟是怎么回事？这里面是不是有什么误会？")
dongfangzhouyu:say("如今东方家败落，我无话可说，想必这个吃货便是你俩的孩子。")
dongfangtun:say("大哥……想不到你竟然是……")
dongfangsha:say("我……我……")
dongfangzhouyu:say("可我对你这些年倒也真心实意，你怎么敢……")
longwanying:say("有什么敢不敢的！你不知道的事情还多着呢！")
dongfangzhouyu:say("你！你住嘴！先让我清除孽种！")
shake_stage(20, 1)
dongfangzhouyu:jumpTo(1200, 75)
longwanying:flip()
laosong:jumpTo(1300, 75)
wait_twn(dongfangsha:jumpTo(1600, 75), laosong:offsetY(-200), laosong:daze())
stop_bgm()
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
laosong:say("孩儿……照顾好你娘……")
dongfangzhouyu:say("你这个野种！你这个奸夫！")
longwanying:say("宋郎！宋郎！")
laosong:movetoY(-600, 5000)
kill_disciple("老宋")
shake_stage(20, 1)
wait_twn(dongfangsha:jumpTo(1400, 75), dongfangsha:daze())
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
dongfangsha:say("爹……为何……")
wait_twn(dongfangzhouyu:offsetY(-200), dongfangzhouyu:daze())
dongfangzhouyu:say("啊——（一把蛟龙枪刺穿了东方骤雨身体…）")
dongfangzhouyu:movetoY(-600, 5000)
kill_disciple("东方骤雨")
shake_stage(20, 1)
wait_twn(dongfangtun:jumpTo(1200, 75), dongfangtun:standfront(), dongfangtun:daze())
play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
dongfangtun:say("你不是我大哥……（赶上一枪刺死了东方鲨）")
longwanying:say("豚儿……你……你竟然杀了鲨儿……你的亲哥哥啊！")
dongfangsha:say("二弟……如果让我选……我也不想……")
hide_all_stage_bubble()
dongfangsha:movetoY(-600, 5000)
kill_disciple("东方鲨")
wait_twn(situ:movetoX(700), situ:daze())
longwanying:flip()
situ:say("这……这算什么事儿啊……")
wait_twn(dongfangli:movetoX(300))
situ:say("这样的事情他不知道也好，何尝不是“无知是福”呢……")
dongfangli:say("“无知是福”吗？还真是伪善啊……")
hide_all_stage_bubble()
wait_twn(dongfangli:flip(), dongfangli:movetoX(-500))
stage_narration("门外，一个少年的背影轻盈地离开")
add_player_item("龙蛇袍", 1)
destroy_menpai("龙湾门")

hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成龙湾起义结局")
light_scene(0.25)


avg_talk("司徒来也", "此间事了，夫人以后有何打算?")
avg_talk("龙万莹", "(player:fname)掌门，我本想一家人和和气气生活在一起，可如今却是这个结局。")
avg_talk("龙万莹", "我这个弱女子也拿不定主意，食为鲜前途全凭(player:fname)掌门定夺。")

local options = {
    "吞并食为鲜",
    "保留食为鲜",
}
local idx = show_avg_select("司徒来也", "……", options)
if idx == 1 then
    avg_talk("司徒来也", "夫人，虎焰门愿代为接管食为鲜。")
    avg_talk("龙万莹", "也好！我可以隐退江湖，守着宋郎和鲨儿，过些平淡的日子。")
    local areas = areas_of_menpai("食为鲜")
    for _, area in pairs(areas) do
        player_occupy_area(area)
    end
    destroy_menpai("食为鲜")
else
    avg_talk("龙万莹", "也好，食为鲜虽小，却也是我夫君与我心血所聚。我愿意继续经营，为虎焰门效力。")
    avg_talk("龙万莹", "此拳法秘籍乃是龙湾秘传，如今龙湾门已不复存在，便赠予(player:fname)掌门吧。")
    add_player_item("骤雨寒冰拳", 1)
    add_player_item("水龙戒", 1)
    set_flag("让龙万莹经营龙湾")
    set_both_friendship("player", "食为鲜", 100)
    local diplomatic = require("Common/diplomatic")
    diplomatic.make_ally("player", "食为鲜")
end
