local subtitles = {"清晨 暮霭⼭庄"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("bg_15.png", "暮霭⼭庄")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/山雨欲来风满楼.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local luzhui = actor("鹿追")
local qiliuge = actor("齐六哥")
local subanjian = actor("苏半见")

--初始化位置和朝向
dark_all_actors()
qiliuge:setPos(2700, 75)
qiliuge:face_left()
luzhui:setPos(2900, 75)
luzhui:face_left()
situ:setPos(2500, 75)
situ:face_left()
subanjian:setPos(-500, 75)
subanjian:face_right()

--剧情
situ:movetoX(1350)
qiliuge:movetoX(1550)
wait_twn(luzhui:movetoX(1790),situ:daze())
situ:jump()
situ:say("我等皆从⻁焰⻔⽽来，求⻅暮霭⼭庄苏掌⻔。")
hide_all_stage_bubble()
wait_twn(subanjian:movetoX(500),subanjian:daze())
wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈"))
subanjian:say("焰⻔？还真是稀客啊，此来何为啊？")
hide_all_stage_bubble()
wait_twn(situ:movetoX(1250),situ:daze(),situ:jump())
situ:say("苏掌⻔何必明知故问？⾃然是为了被掌⻔拿去的岁炙叶⽽来。")
subanjian:say("啊，原是这件事。")
subanjian:say("我们暮霭⼭庄亦是对⽕神树⼗分崇敬，早听闻听说⽕神树每年最红的叶⼦叫岁炙叶，有似⽆穷尽的⾄阳神⼒，能百病不⽣、诸毒不侵。")
subanjian:say("因此才借来⼀观，⻁焰⻔也算是江湖中的名⻔⼤派，不会这么⼩⽓吧？")
hide_all_stage_bubble()
wait_twn(luzhui:jump(),luzhui:shake(),luzhui:movetoX(970),luzhui:daze())
luzhui:say("这哪⾥是借？明明就是偷！")
subanjian:say("哎，姑娘可不要凭空污⼈清⽩，偷的话哪⼉会像我这般⼤⽅承认的？")
subanjian:say("只是那⽇我登⻔拜访，想要借这岁炙叶，恰逢⻁焰⻔中⽆⼈，只能先⾏借⾛了。")
situ:say("小鹿，回来")
wait_twn(luzhui:jump(),luzhui:shake(),luzhui:movetoX(1790),luzhui:daze())
situ:say("苏掌⻔莫⾮不知道，不问⾃拿，便是窃吗？")
subanjian:jump()
subanjian:say("哎我这不就是先斩后奏罢了，你看看这些叶⼦就在这⼉，⼀⽚没少，⼀⽚没坏，⼤可放⼼借给我便是了。")
wait_twn(qiliuge:movetoX(1350),qiliuge:daze())
qiliuge:say("掌⻔……这苏半⻅可是外送名号“借⽆还”，⼀张嘴冠冕堂皇，可拿去的东西从未归还过。")
wait_twn(qiliuge:movetoX(1550))
situ:shake()
situ:say("岂有此理...")
situ:say("他这样刁钻奸猾，同明抢⼜有什么差别？")

subanjian:jump()
subanjian:say("怎么？你等意下如何？不要嘀嘀咕咕，便是现在将叶⼦讨回，我暮霭⼭庄宽宏⼤量，⾃然也不会计较。")
luzhui:shake()
luzhui:say("这……并⾮是我⿅追⼩⽓，只是这真正的岁炙叶每年只有⼀⽚。")
luzhui:say("炙家族世代收集，集⻬三百⽚⽅才能催发其中的⽕神之⼒。")
luzhui:say("如今集⻬这⼆百九⼗九⽚已是不易，若是借给苏掌⻔这⼗九的话，怕是就⼜要等上⼗⼏⼆⼗年。")
subanjian:say("不愁不愁，待摘到那第三百⽚，我⾃然将这⼗九⽚拱⼿奉还，我暮霭⼭庄崇敬⽕神之树，也⾃然想⻅识这其中的⽕神之⼒。")
situ:say("既然如此...")
hide_all_stage_bubble()
local options = {
  "不如先将叶⼦暂存在此，以免得罪暮霭⼭庄……",
  "此⼈油滑奸诈不相信，还是要回来的好。",
}
local idx = show_quick_selections(options)
switch(idx) {
  ["1"] = function()
    situ:say("江湖中谁⼈不知苏掌⻔“借⽆还”的称号，只怕我这前脚应允，苏掌⻔后脚便反悔。")
    wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈哈"))
    subanjian:flip()
    subanjian:say("那就看司徒掌⻔有没有胆魄来信我这么⼀遭。")
    wait_twn(situ:movetoX(1100),situ:daze())
    situ:say("我⻁焰⻔上上下下都将诚信摆在江湖处事的第⼀原则，与我往来的也都是江湖之中诚信之辈，我今⽇便成⼈之美，相信苏掌⻔定不会失信于⼈。")
    subanjian:flip()
    wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈，有趣有趣着实有趣，这江湖上上下下，你还是第⼀个说信我苏半⻅之⼈。"))
    situ:say("苏掌⻔⻅外了不是，希望“借⽆还”碰到我后，成为“借有还”，毕竟苏掌⻔也不愿落⼈诟病吧。")
    subanjian:jump()
    subanjian:say("好！就凭你这句话，等⿅姑娘拿到第三百⽚岁炙叶时，俺⽼苏定将这⼗九⽚岁炙叶完璧归赵！")
    situ:jump()
    situ:say("那便⼤丈夫⼀⾔。")
    subanjian:say("管他什么⻢都难追。")

  end,
  ["2"] = function()
    situ:say("虽说苏掌⻔明理，可在下却听闻掌⻔还有个“借⽆还”的尊号……这岁炙叶终究是⿅家世代⼼⾎，我可做不了主…… ")
    luzhui:say("⼩⼥可不敢质疑苏掌⻔这“借⽆还”的名号啊。")
    wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈……"))
    subanjian:flip()
    subanjian:say("⼈⼈都知我这“借⽆还”的名号，却⼜⼈⼈都不知我这“借⽆还”的名号从何⽽来。")
    situ:say("这名号到底从何⽽来，倒是想听苏掌⻔告知⼀⼆。 ")
    subanjian:flip()
    wait_twn(subanjian:movetoX(600),subanjian:daze())
    subanjian:say("这么想知道？")
    situ:jump()
    situ:say("这⿍⿍⼤名的来历确实让⼈好奇啊")
    subanjian:flip()
    wait_twn(subanjian:movetoX(400),subanjian:daze())
    subanjian:flip()
    subanjian:jump()
    subanjian:say("你既不愿将这岁炙叶借于我，我⼜凭什么与你多做⼝⾆？不过，你且记住，⽼⼦想要的东西，还从未失⼿过。")
    situ:say("是吗？恐怕这次苏掌⻔的算盘可要落空了。")
    subanjian:say("什么意思？")
    qiliuge:say("⻔主，这岁炙叶我已⽤探云⼿取回来了")
    qiliuge:flip()
    qiliuge:daze()
    qiliuge:say("⿅⼩姐您看⼀下，是否有缺损。")
    luzhui:jump()
    luzhui:say("⼗七……⼗⼋……⼗九，是，⼗九⽚！⼀⽚不少！")
    wait_twn(shake_stage(),subanjian:jump(150,2,0.5),subanjian:shake())
    subanjian:say("你这混蛋玩意是何时…… ")
    qiliuge:flip()
    situ:say("就在与苏⻔主探讨这“借⽆还”称号是如何⽽来时。")
    subanjian:jump()
    subanjian:say("你居然⽤这种下三滥的⽅式窃取！还讲不讲江湖道义？！")
    qiliuge:jump()
    qiliuge:say("苏掌⻔，在下只不过是以其⼈之道还治其⼈之⾝罢了。")
    wait_twn(subanjian:jump(150,2,0.5),subanjian:shake())
    subanjian:say("你，这⼥孩到底跟你们⻁焰⻔什么关系？！")
    subanjian:say("居然为了她的⼏⽚叶⼦，来暮霭⼭庄造次，你就不怕有来⽆回吗？！ ")
    situ:jump(150,1,0.5)
    situ:say("⿅追就是我们⻁焰⻔的⼈，她的事情就是我的事情。")
    situ:say("今⽇前来，就是要把叶⼦带回去，想让我留在暮霭⼭庄，倒是要看看苏⻔主，有没有这个本事了。")
    wait_twn(shake_stage(),subanjian:jump(150,2,0.5),subanjian:shake())
    subanjian:say("可我说了，我想要的东西，还从未失⼿过，哪天我酒劲上了头破⻔来抢，就别怪我下⼿太重打断了你胳膊腿。")
  end
}
hide_all_stage_bubble()


black_scene(0.5)
hide_stage()
set_flag("完成偷树叶的人")
light_scene(0.25)




