local subtitles = {"深夜 虎焰门大堂"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("殿内.png", "虎焰门大堂")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/抉择_一念之间.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local luzhui = actor("鹿追")
local qiliuge = actor("齐六哥")

--初始化位置和朝向
dark_all_actors()
qiliuge:setPos(2500, 75)
qiliuge:face_left()
luzhui:setPos(2500, 75)
luzhui:face_left()
situ:setPos(-500, 75)
situ:face_right()

--剧情
wait_twn(qiliuge:movetoX(800),qiliuge:daze())
wait_twn(qiliuge:flip(),qiliuge:say("大伙人呢？"),qiliuge:flip())
hide_all_stage_bubble()
wait_twn(luzhui:movetoX(1200),luzhui:jump())
qiliuge:flip()
luzhui:say("六哥！六哥！可算是回来了！可是打听出了是谁偷拿了收集好的岁炙叶？！")
wait_twn(qiliuge:movetoX(890),luzhui:jump())
qiliuge:say("⿅姑娘莫急！真是没想到，潜⼊咱们这⾥偷⾛岁炙叶的，竟然是暮霭⼭庄的掌⻔，苏半⻅。")
qiliuge:say("这位掌⻔也真够厚脸⽪，偷了叶⼦竟还公然炫耀。")
luzhui:jump()
luzhui:say("苏半⻅？！莫不是那个暮霭⼭庄那个被称作“借⽆还”的掌⻔？")
luzhui:say("听说落于他⼿的宝物，从未有⼈能够要回，这……这可怎么办！")
wait_twn(situ:movetoX(630),situ:jump())
situ:say("眼下这苏半⻅虽偷了叶⼦，但⼀时之间未必能参透其中关窍，想来这事情还有转圜的余地。")
hide_all_stage_bubble()
wait_twn(luzhui:jump(),luzhui:shake())
luzhui:say("我怎么可能不急！炙家族守了数百年的东西，就这样被盗⾛，我……我…… ")
wait_twn(situ:movetoX(1400),situ:flip(),luzhui:flip())
situ:say("⼩⿅⼉稍安勿躁，他只拿着这单单⼗九⽚岁炙叶能起到什么效果？")
luzhui:shake()
luzhui:say("只怕他研究不出岁炙叶的效果，⼀怒之下将它毁了，那这些年的⼼⾎可就⸺")
situ:jump()
situ:say("事不宜迟！现在动⾝前往暮霭⼭庄，定要把岁炙叶讨要回来！")
qiliuge:jump()
qiliuge:say("我们走")
hide_all_stage_bubble()
qiliuge:flip()
situ:movetoX(-200)
qiliuge:movetoX(-200)
luzhui:flip()
luzhui:say("好！我也要⼀起去！")
hide_all_stage_bubble()
luzhui:movetoX(-200)

black_scene(0.5)
hide_stage()
set_flag("完成岁炙叶情报")
light_scene(0.25)