local subtitles = {"破败的 暮霭⼭庄"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("bg_15.png", "暮霭⼭庄")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/日常_烟火人间.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local luzhui = actor("鹿追")

local subanjian = actor("苏半见")

--初始化位置和朝向
dark_all_actors()
situ:setPos(2500, 75)
situ:face_left()
luzhui:setPos(2700, 75)
luzhui:face_left()
subanjian:setPos(300, 75)
subanjian:face_right()

--剧情
situ:movetoX(1500)
wait_twn(luzhui:movetoX(1700),situ:daze())
subanjian:shake()
subanjian:say("唉，这偌⼤的息⻛⾕，已经没有我苏半⻅的位置了吗？")
situ:say("⾮是江湖不容你，⽽是你为⼈太不厚道，才⾛到如今的地步。")
subanjian:shake()
subanjian:flip()
subanjian:say("你我因这⿅姑娘的红叶结仇，现在也算是守了你与⿅姑娘的承诺了。")
situ:jump()
situ:say("信守承诺，是息⻛⾕侠⼠应有之道。")
wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈……你真是个有趣的家伙……"))
subanjian:say("没想到你为了这个⿅姑娘的承诺，不惜与我苏半⻅⽃个你死我活。")
hide_all_stage_bubble()
wait_twn(situ:movetoX(1200),situ:jump(),situ:daze())
situ:say("为了值得信任和珍惜的⼈，我不惜付出⼀切，这是侠义之道，⽽你……")
situ:say("从未将信义看在眼中，更不会拥有我和⿅追的情感，这些，你岂能明⽩？")
subanjian:jump()
subanjian:shake()
subanjian:flip()
subanjian:say("你少在这⾥得意洋洋，⽼⼦曾经也是守信之⼈，也有过同⾈共济的⽣死之交！")
wait_twn(luzhui:movetoX(1500),luzhui:daze())
luzhui:say("看不出来呀。")
subanjian:flip()
subanjian:shake()
subanjian:say("哼……你⾃然是不知，我那兄弟骗了我……他将我赠予他的红⾊棉⾐穿⾛了……再也没有回来……")
luzhui:jump()
luzhui:say("就只是⼀件棉⾐你便处处坑蒙拐骗？")
subanjian:say("那可不只是⼀件⾐服……那是我们的约定，约定⼀起奋⽃⼀起努⼒⼀起成为名扬天下的⼤侠……")
situ:say("可如今却只剩你⼀⼈，这么说……")
subanjian:shake()
subanjian:say("是啊……那个家伙真是可怜，虽有⼀⾝志⽓，却四处碰壁遭殃，他不辞⽽别离开⼈世……")
subanjian:say("唉，这个江湖上，不会再有让我守信之⼈了……")
hide_all_stage_bubble()
wait_twn(situ:movetoX(900),situ:jump(),situ:daze())
situ:say("就算被⻓夜笼罩，也不能放弃对黎明的希望啊……")
subanjian:shake()
subanjian:say("你说得对，但对我来说已经晚了，既然息⻛⾕没有我的位置，我还是回到我⼉时的⽥间……")
subanjian:say("⻩粱还是⻩粱，布⾕还是布⾕，没有什么鸿鹄之志，也没有什么你争我夺，只有⼀壶⽶酒，伴我⼀醉⽅休。")
situ:say("希望你能够悟明⽩。")
subanjian:flip()
subanjian:say("昨晚，我梦⻅我死去的好兄弟了，他，把那棉布⾐还给我了。")
wait_twn(luzhui:movetoX(1150),luzhui:daze())
luzhui:jump()
luzhui:say("哈哈，是你说的那件红⾊棉布⾐吗？")
subanjian:say("是也不是吧……")
subanjian:say("那⾐裳，好像⽐我借给他的更宽，更⻓，摸上去更舒服，只不过，是⿊⾊的……")

black_scene(0.5)
hide_stage()
light_scene(0.25)
