local subtitles = {"火神树林", "一会过后…"}
options = 2

--初始化场景和背景音乐
show_cg({subtitles[1]})
show_stage("bg_60.png", "火神树林")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/少女鹿追.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local luzhui = actor("鹿追")

--初始化位置和朝向
dark_all_actors()
situ:setPos(2500, 75)
situ:face_left()
luzhui:setPos(2700, 85)
luzhui:face_left()


--剧情
if options == 1 then
    luzhui:movetoX(800)
    wait_twn(situ:movetoX(1150),luzhui:flip(),situ:daze())
    luzhui:say("⽕之神将他的⼒量蕴藏这棵古树中，当时掩护⽕之神的，也就是炙家族。")
    luzhui:say("按照⽕之神的遗愿，炙家族每年都会采集岁炙叶，收集⽕之神⼒量的凝华，以盼望重新唤醒⽕神之⼒。")
    situ:shake()
    situ:say("那么说，三百这个数字也是⽕之神定下的。")
    luzhui:shake()
    luzhui:say("是的，奶奶说，⽕之神临终之前，与古树进⾏了⻓时间的交流，定下了三百这个数字，并将⾃⼰的⾎液献给了炙家族")
    luzhui:say("所以只有炙家族才能唤醒⽕神之⼒。")
    situ:jump()
    situ:say("原来如此，现在炙家族唤醒⽕神之⼒的希望都在⼩⿅⾝上了。")
    stage_narration("只见小鹿拿出了岁炙叶")
    luzhui:jump()
    luzhui:say("三百⽚岁炙叶都在这⼉，⼀⽚不少，神圣的⽕神之树啊，请赐予炙家族第九代传⼈⽕神之⼒吧！")
    stage_narration("………")
    situ:jump()
    situ:say("⽕神之树…好像没有反应。")
    luzhui:say("是呀…奶奶好像没告诉过我，要如何唤醒⽕神之⼒… ")
else
    luzhui:movetoX(800)
    wait_twn(situ:movetoX(1150),luzhui:flip(),situ:daze())
    luzhui:jump()
    wait_twn(play_sfx("Voice/Female2_Laugh_2.wav"),luzhui:say("终于等到这天了，炙家族⼏代⼈的愿望要在今天实现了！"))
    situ:say("那么说，⼩⿅将成为⽕之神的传⼈了，太棒了！")
    luzhui:say("⽕神的传⼈⼩⿅可不敢当，如果能够唤醒⼀点点⽕神之⼒，已是此⽣⼤幸了。")
    situ:say("我⼀直没想明⽩，这⽕神之⼒为什么会在⽕神树⾥⾯呢？")
    hide_all_stage_bubble()
    luzhui:flip()
    wait_twn(luzhui:movetoX(350),luzhui:daze(),luzhui:flip())
    luzhui:say("奶说，三百年前，息⻛⾕⼤地出现了⼀位叫昆吾的神⼈。")
    luzhui:say("他是上古⽕神吴回的后⼈，昆吾给息⻛⾕⼤地带来了⽕种和希望")
    luzhui:say("⼈们⽤⽕种冶炼陶器，⽣活变得丰富多彩，昆吾深受百姓爱戴，被⼈们尊成为⽕之神。")
    luzhui:jump()
    situ:say("被称之为神的，⼀定是给⼈带来幸福和希望的。")
    wait_twn(luzhui:movetoX(700),luzhui:daze())
    luzhui:say("因为昆吾的⽕可以熔断当时统治者的宝剑，有奸⼈借此对他诋毁污蔑，导致⽕之神受到追杀。")
    luzhui:say("在村⺠的掩护下，⽕之神藏⾝于⻁焰⼭古树中，将灵魂与古树融为⼀体。")
    luzhui:jump()
    luzhui:say("于是就有了我们⾯前这棵⽕神之树。")
    situ:say("原来⽕神之树是这么来的。")
    luzhui:say("⽕之神将他的⼒量蕴藏这棵古树中，当时掩护⽕之神的，也就是炙家族。")
    luzhui:say("按照⽕之神的遗愿，炙家族每年都会采集岁炙叶，收集⽕之神⼒量的凝华，以盼望重新唤醒⽕神之⼒。")
    situ:shake()
    situ:say("那么说，三百这个数字也是⽕之神定下的。")
    luzhui:shake()
    luzhui:say("是的，奶奶说，⽕之神临终之前，与古树进⾏了⻓时间的交流，定下了三百这个数字，并将⾃⼰的⾎液献给了炙家族")
    luzhui:say("所以只有炙家族才能唤醒⽕神之⼒。")
    situ:jump()
    situ:say("原来如此，现在炙家族唤醒⽕神之⼒的希望都在⼩⿅⾝上了。")
    stage_narration("只见小鹿拿出了岁炙叶")
    luzhui:jump()
    luzhui:say("三百⽚岁炙叶都在这⼉，⼀⽚不少，神圣的⽕神之树啊，请赐予炙家族第九代传⼈⽕神之⼒吧！")
    stage_narration("………")
    situ:jump()
    situ:say("⽕神之树…好像没有反应。")
    luzhui:say("是呀…奶奶好像没告诉过我，要如何唤醒⽕神之⼒… ")   
end


hide_all_stage_bubble()
options = {
  "是不是还没到唤醒的时候，要不咱们下次再来试试。",
  "这边有个树洞，会不会和它有关呢。",
}
local idx = show_quick_selections(options)
switch(idx) {
  ["1"] = function()
    wait_twn(play_sfx("Voice/Female2_Sigh_1.wav"),luzhui:say("唉，好吧，我们先走吧…"))
    wait_twn(luzhui:flip(),luzhui:daze())
    luzhui:movetoX(-200)
    situ:movetoX(-200)
  end,
  ["2"] = function()
    wait_twn(situ:movetoX(1000),situ:daze())
    situ:say("这边有个树洞，会不会和它有关呢。")  
    wait_twn(luzhui:movetoX(800),luzhui:daze())
    luzhui:jump()
    luzhui:say("可是…它们会有什么样的关联呢？")  
    situ:say("苏半⻅的事情给了我⼀个启发。")  
    luzhui:say("苏半⻅？")  
    situ:say("⽆论是谁，借了的东西⼀定要还给本主⼈…")  
    luzhui:jump()
    luzhui:say("你的意思是？")  
    situ:say("这三百⽚岁炙叶虽是炙家族⼀代代⼈费尽⼼⾎收集的，但是它们原本是属于⽕神之树的。")  
    luzhui:say("所以…我是要将这三百⽚岁炙叶，还给⽕神之树！")  
    situ:say("你看这个树洞深处，⾥⾯泛着⾎红⾊的微光，它似乎在预⽰着什么！")  
    luzhui:say("那么，我就按你说的，把岁炙叶还给树洞中…")  
    stage_narration("⿅追伸出雪⽩的双⼿，捧着三百⽚岁炙叶，放⼊树洞中…")
    luzhui:shake()
    luzhui:say("哇，这个树洞⾥⾯…好温暖…")  
    situ:jump()
    situ:say("⼩⿅你看…感觉红⾊的光变得越来越强了！")  
    luzhui:shake()
    wait_twn(play_sfx("Voice/Female2_Hurt_2.wav"), luzhui:say("我的双⼿，好热啊…")  )
    situ:jump()
    situ:say("那…是⽕神之⼒吗？")  
    wait_twn(luzhui:shake(),luzhui:shake())
    wait_twn(play_sfx("Voice/Female2_Hurt_1.wav"), luzhui:say("燃烧了，树洞⾥⾯燃烧起来了，我的⼿好烫…")  )
    situ:say("坚持住啊，⽕神之⼒唤醒了！")  
    shake_stage()
    wait_twn(luzhui:shake(),luzhui:shake())
    luzhui:say("好烫啊，我快⽀撑不住了，好痛…")  
    wait_twn(play_sfx("Voice/Female2_Hurt_2.wav"), luzhui:say("好烫啊，我快⽀撑不住了，好痛…")  )
    situ:jump()
    situ:say("小鹿")  
    stage_narration("司徒来也⼼疼⿅追，也将⼿伸⼊树洞，⽤⾃⼰双⼿护着⿅追的双⼿，被树洞中燃起的⽕焰灼烧。")
    situ:shake()
    situ:say("这…啊…这是什么感觉…")  
    luzhui:shake()
    luzhui:say("来也…你…⼩⼼…")  
    situ:shake()
    situ:say("啊…我的⼿…全⾝都…好烫…")  
    shake_stage()
    situ:rotatetoZ(90)
    wait_twn(luzhui:rotatetoZ(-90),luzhui:shake())
    local subtitles1 = {"一会过后…"}
    show_cg({subtitles[2]})
    situ:rotatetoZ(-90,0)
    wait_twn(luzhui:rotatetoZ(90,0),luzhui:shake(),situ:daze())
    situ:shake()
    situ:say("刚才…发⽣了什么？")  
    situ:jump()
    situ:say("我的⼿臂，我的全⾝…都好热啊…感觉好奇怪。")  
    luzhui:jump()
    luzhui:say("你获得⽕神之⼒了！")  
    situ:shake()
    situ:say("我？为什么是我？不应该是⼩⿅吗？")  
    wait_twn(luzhui:flip(),luzhui:daze())
    luzhui:say("我也没想明⽩…可能是你不惜性命守护炙家族的⼩⿅，感动了⽕之神呢！")  
    situ:shake()
    situ:say("可是…只有炙家族才能继承⽕神之⼒，我不是炙家族的传⼈呀…")  
    luzhui:flip()
    luzhui:jump()
    wait_twn(play_sfx("Voice/Female2_Laugh_2.wav"),luzhui:say("但你是炙家族传⼈最爱的⼈，嘻嘻。"))
    situ:shake()
    situ:say("⼩⿅…")  
    luzhui:jump()
    wait_twn(play_sfx("Voice/Female2_Laugh_2.wav"),luzhui:say("怪不得奶奶⼀直想要我嫁给司徒家族"))
    luzhui:say("也许她早就知道司徒来也才是⽕之神的天选之⼦吧，由你来继承这份⼒量，⽐⼩⿅更合适呀！")  
    situ:say("我……")
  end
}


black_scene(0.25)
hide_stage()
light_scene(0.25)
