local subtitles = {"暮霭⼭庄村庄某农户家"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("大门.png", "暮霭⼭庄周边村庄")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/ThunderRain.mp3", 0.2)

--设置滤镜，以及滤镜效果大小
local filter = add_camera_filter("CameraFilterPack_Atmosphere_Rain_Pro")
filter.Fade = 0.65;

--初始化人物
local Son = actor("[speaker:儿子][img:hero_ASheng]")
local Mother = actor("[speaker:母亲][img:pawn_CunMing_female_3]")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
Mother:setPos(700, 75)
Mother:face_left()
Son:setPos(2500, 75)
Son:face_left()

--剧情
wait_twn(play_sfx("Voice/Female1_Sigh_2.wav"),Mother:say("哎，也不知道臭小子跑哪里去了。"))
Mother:shake_bubble()
Mother:say("下这么大雨，两个人都不让我安心。")
Mother:daze()
hide_all_stage_bubble()
wait_twn(Son:movetoX(1450), Son:daze())
wait_twn(Son:offsetY(-70), Son:daze())
Son:say("娘，孩⼉回来了")
wait_twn(Mother:flip(),Mother:movetoX(900))
Son:offsetY(70)
Mother:say("臭小子，总算回来了，先去屋里面擦擦。")
Son:say("咋不⻅我爹爹啊？")
wait_twn(play_sfx("Voice/Female1_Sigh_2.wav"),Mother:say("哎，你爹爹早晨就唉声叹⽓地出了⻔，到现在还没回来。"))
Son:say("爹爹他有什么事情唉声叹气啊？")
hide_all_stage_bubble()
wait_twn(Mother:shake(),Mother:jump())
Mother:say("还有什么事情，不就是因为是你这败家⼦⾃作聪明，把家⾥唯⼀两头⽔⽜借给那暮霭⼭庄的苏庄主。")
wait_twn(Son:jump())
Son:say("可苏半⻅庄主答应，到了秋分，还我四头⼤⽔⽜，还送我⼀把⾦丝⼤环宝⼑。");
hide_all_stage_bubble()
wait_twn(Mother:daze(),Mother:jump())
wait_twn(Mother:movetoX(1100))
wait_twn(Mother:jump(),shake_stage(40,0.5))
wait_twn(play_sfx("Story/Fist.mp3"),Mother:say("你可⻓点⻅识吧，⽅圆⼗⾥谁不知道那苏半⻅的德信，你不知道他的外号叫“借⽆还”吗？"))
Son:shake()
Son:say("哎呦，娘好疼……")
Son:say("借⽆还……那咱们家的⽔⽜岂不是⽩搭了……")
Mother:say("现在正是春耕之时，家⾥没了⽜，你爹急得团团转。")
Son:shake_bubble()
Son:say("爹现在去哪⾥了？……")
Mother:say("我怎么知道，他⼀早就往望尘崖的⽅向⾛了…")
Son:shake()
Son:say("望尘崖……遭了！他该不会是想不开吧……哎呀……我闯了⼤祸了！")
hide_all_stage_bubble()
wait_twn(Son:jump(),Son:daze())
Son:say("这么大的雨……我去找爹爹")
hide_all_stage_bubble()
wait_twn(Son:movetoX(-200))
Son:hide()
wait_twn(Mother:jump(),Mother:shake(),Mother:face_left())
wait_twn(Mother:say("是啊！哎呀！这可叫我怎么活呀……"))
hide_all_stage_bubble()
wait_twn(Mother:movetoX(-200))
Mother:hide()

remove_camera_filter("CameraFilterPack_Atmosphere_Rain_Pro")
black_scene(0.5)
hide_stage()
light_scene(0.25)
