local subtitles = {"暮霭⼭庄-望尘崖"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("bg_60.png", "暮霭⼭庄-望尘崖")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/抒情_柔情似水.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local chuanxi = actor("[speaker:川西][img:hero_LaoSong]")

--初始化位置和朝向
dark_all_actors()
situ:setPos(2500, 75)
situ:face_left()
chuanxi:setPos(700, 85)
chuanxi:face_left()


--此处剧情使用多转身，大叔的话语更多是对自己所讲，释怀

--剧情
chuanxi:say("小友，别看了，过来吧")
chuanxi:flip()
wait_twn(situ:movetoX(1250),situ:daze())
chuanxi:say("⻁焰新主，⽓焰雄厚，后⽣可畏啊，看来⽼夫川西是要离开这个坚守了⼆⼗余年的⼭崖了。")
situ:say("川西大叔言重了，我看大叔招数⼲练，谈吐清雅，不像是暮霭⼭庄苏半⻅这⼀流派啊。")
chuanxi:say("我的武功是⾃学⾃成，和苏掌⻔的武学确实不属⼀脉。")
situ:say("我说的可不只是武功，⽓质也不像⼀流派的，你这么⼤年纪了，为何还要帮苏半⻅这种⽆赖卖命呢。")
chuanxi:flip()
wait_twn(chuanxi:movetoX(550),chuanxi:daze())
chuanxi:say("哈哈哈，⽆赖不⽆赖，⽼夫倒是不好评价，我主要是舍不得这望尘崖的⻛景。")
situ:jump()
situ:say("这望尘崖…向下望去，满眼暮霭沉沉，不⻅⼀花⼀树，毫⽆⼼旷神怡之感，倒是看得⼈⼼⽣恐惧和迷茫。")
situ:say("⼤叔居然留恋这等景⾊？")
chuanxi:flip()
chuanxi:say("正因如此，我才留恋…")
situ:say("这⼜是为何呢？")
chuanxi:shake()
chuanxi:say("⼆⼗年前，我在这⾥，找到了⾃⼰⼀⽣的使命。")
situ:say("投靠苏半⻅加⼊暮霭⼭庄吗？")
chuanxi:flip()
wait_twn(chuanxi:movetoX(350),chuanxi:daze())
chuanxi:say("不不不，和他完全没有关系，那是⽐什么江湖⻔派争⽃之类的，重要⼀百倍⼀千倍的事情。")
situ:jump()
situ:say("哦？那是什么事情")
chuanxi:flip()
chuanxi:say("渡世⼈于⽔⽕，挽⽣命于尘埃。")
situ:shake()
situ:say("这么⾼尚吗？")
chuanxi:say("我本在这望尘崖上劈柴习武为⽣。")
chuanxi:say("你刚才说这⼭崖下的⼀⽚⼤雾，让⼈感到未知和迷茫，看不到⼀丝希望，也许当年的他也是这么想吧…")
situ:shake()
situ:say("他？")
chuanxi:flip()
chuanxi:say("⼆⼗年前，站在崖边轻⽣的书⽣。")
situ:shake()
situ:say("轻⽣的…书⽣？")
chuanxi:shake()
chuanxi:say("我永远记得他那瘦弱的⾝躯，绝望的眼神…他的脚已经踩到了崖边，再往前⼀步，就将在这暮霭之中粉⾝碎⻣。")
chuanxi:say("我救下了他，我将⾃⼰卖柴换来的酒温给他喝，我和他坐在我那⽊屋⼦⾥聊了⼀整夜…")
chuanxi:say("直到第⼆⽇朝阳初升时，我从他的眼睛⾥看到了光，那⼀刻，我知道…我挽救了⼀条⽣命。")
situ:jump()
situ:shake()
situ:say("⼤叔做了件⼤善事啊。")
chuanxi:say("那书⽣离开后，我就再也没有⻅过他，但我在看那⼭崖之下，眼中的⻛景都变了…")
chuanxi:shake()
chuanxi:say("顺着⽇光穿过的雾霾，我仿佛能看到潺潺的流⽔，张开翅膀的布⾕⻦，悄然⽣⻓的树⽊… ")
situ:jump()
situ:say("⼀定是救了⼈之后，⾃⼰的⼼境也变了。")
chuanxi:flip()
chuanxi:say("我找到了渡⼈、渡⼰、渡⼼的内在涵义，我决定，不再离开这座⼭崖。 ")
chuanxi:say("说来也怪，我从未想到过这世上有这么多轻⽣的⼈。 ")
situ:say("你是说，后来还有其他轻⽣想跳崖的⼈？")
chuanxi:say("是啊，这些年来，我在崖边救下了⼤概有⼗余⼈吧，其中有家徒四壁的，有郁郁不得志的，有被恋⼈抛弃的，有亲⼈遇难的…")
situ:shake()
situ:say("…亲⼈遇难，为何要选择轻⽣呢，不应该好好活下去讨回公道吗…")
chuanxi:flip()
chuanxi:say("不是每个⼈都像你⼀样⼼胸豁朗，有⼏个⼈，我是废了好⼤劲才劝回来的。 ")
situ:say("这些被⼤叔救了的⼈，不知后来过得如何。")
chuanxi:say("他们有的后来⼩有成就，当然也有的继续过着艰苦的⽣活，不过⾄少…他们都重拾了对⽣命的希望。 ")
chuanxi:say("很多⼈都回来感谢我，陪我喝酒聊他们的近况，那是我⼀⽣中最满⾜的时刻……")
chuanxi:shake()
chuanxi:say("只是我第⼀次救的那个书⽣，那以后就再也没有⾳讯了。 ")
situ:shake()
situ:say("我终于了解⼤叔为什么舍不得这望尘崖了。")
chuanxi:flip()
chuanxi:say("胜者占⼭，败者落⽔，是息⻛⾕的江湖规矩，今后这望尘崖成了⻁焰⻔的地盘，司徒掌⻔如果看到轻⽣的⼈，也会劝他们活下去吗？")

hide_all_stage_bubble()
local options = {
  "川西⼤叔，不如你就留在这崖边吧。",
  "这就不⽤⼤叔操⼼了，我的地盘我爱怎么样就怎么样。",
}
local idx = show_quick_selections(options)
switch(idx) {
  ["1"] = function()
    wait_twn(situ:movetoX(780),situ:daze())
    situ:say("川西⼤叔，不如你就留在这崖边吧。")
    chuanxi:shake()
    chuanxi:say("可是我不能背叛苏半⻅，当年他将望尘崖占据后，我答应他只要同意我留在这崖边，我便⼀⽣效⼒于暮霭⼭庄，我不能失信。")
    situ:jump()
    situ:say("居然还有对苏半⻅这么守信的⼈。")
    chuanxi:say("苏掌⻔对我也不薄，我不愿背信弃义。")
    situ:say("我并没有逼你投靠⻁焰⻔的意思，我的意思是")
    situ:say("这望尘崖虽然成了⻁焰⻔的地盘，但是川西⼤叔随时可以来，哪怕是⼀直在这⾥也⽆妨。")
    chuanxi:shake()
    chuanxi:say("司徒掌⻔真是胸怀宽⼴、深明⼤义啊！")
    situ:say("当然，这是我司徒来也和你川西之间的约定，能⾃由呆在望尘崖的，只限于你⼀⼈。")
    wait_twn(chuanxi:offsetY(-40),chuanxi:daze())
    chuanxi:shake()
    chuanxi:say("老夫我…感激不尽")
  end,
  ["2"] = function()
    situ:jump()
    situ:say("这就不⽤⼤叔操⼼了，我的地盘我爱怎么样就怎么样。")
    chuanxi:flip()
    chuanxi:say("说的也是，我怎么能要求你呢…")
    wait_twn(situ:movetoX(780),situ:daze())
    situ:say("请你离开这⾥吧。")
    chuanxi:shake()
    chuanxi:say("好…好…芸芸众⽣⾮吾事，本是望尘⼀樵夫。")
    chuanxi:movetoX(-200)
  end
}


black_scene(0.25)
hide_stage()
light_scene(0.25)
