local subtitles = {"⻁焰⻔"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("殿内.png", "⻁焰⻔")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/山雨欲来风满楼.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local luzhui = actor("鹿追")

local subanjian = actor("苏半见")
local baishiba = actor("白十八")

--初始化位置和朝向
dark_all_actors()
situ:setPos(2500, 75)
situ:face_left()
luzhui:setPos(2700, 75)
luzhui:face_left()

subanjian:setPos(2500, 75)
subanjian:face_left()
baishiba:setPos(2700, 75)
baishiba:face_left()

--剧情
situ:movetoX(500)
wait_twn(luzhui:movetoX(700),luzhui:daze())
situ:flip()
luzhui:shake()
luzhui:say("也不知道苏半见他们下一步会做什么")
luzhui:say("今天已经算是得罪死他们了")
situ:jump()
situ:say("别担心，兵来将挡水来土...")
stage_narration("还没说完，就见苏半白追了过来")
clear_saved_prev_bgm()
play_bgm("Music/豪猪恶贼.wav", 0.2)
subanjian:movetoX(1500)
wait_twn(baishiba:movetoX(1750),subanjian:daze())
subanjian:jump()
subanjian:say("呵呵，也不知道贵⻔是否欢迎我")
luzhui:flip()
wait_twn(situ:movetoX(900),situ:daze())
situ:jump()
situ:say("哼，当然欢迎了，毕竟苏门主也是盛情款待了我们。")
subanjian:jump()
subanjian:say("呵呵，贵门几⽚叶⼦都不借！哼！那就别怪我苏半⻅先礼后兵了！")
luzhui:jump()
luzhui:say("当真是厚颜⽆耻，偷不到就抢！")
wait_twn(subanjian:movetoX(1300),subanjian:daze())
shake_stage()
subanjian:jump()
subanjian:say("哼，想必⿅姑娘还不知道吧，除了“借⽆还”这个称号外，⽼⼦还有⼀个称号叫“不借就抢”！")
wait_twn(baishiba:movetoX(1500),baishiba:daze())
baishiba:say("这也不好听啊⽼⼤……")
subanjian:jump()
subanjian:flip()
subanjian:say("江湖传闻你⻁焰⻔⼤⽓利落，现在看来就是个⼩⽓包⼦，⽼⼦想借⼏⽚树叶都不给，既然敬酒不吃吃罚酒，")
subanjian:flip()
subanjian:jump()
subanjian:say("那就修怪我⽆情了！")
situ:jump()
situ:say("江湖上谁不说我⻁焰⻔⼤⽓，但对于你们这种流氓⽆赖，⼩⽓都是抬举了你们！")
subanjian:say("呵呵，少说废话！我偏要尝尝这岁炙叶泡酒是个什么滋味！")
hide_all_stage_bubble()
situ:rotatetoZ(25)
subanjian:rotatetoZ(-25)
situ:movetoX(1100,1500)
subanjian:movetoX(1100,1500)

local diplomatic = require("Common/diplomatic")
diplomatic.declare_war("暮霭山庄", "player")

black_scene(0.25)
hide_stage()
set_flag("完成暮霭来袭")
light_scene(0.25)
