local subtitles = {"暮霭⼭庄"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("bg_15.png", "暮霭⼭庄")
set_bg_mat("ImgPaperFold")
light_scene(0.2)
play_bgm("Music/山雨欲来风满楼.wav", 0.2)

--初始化人物
local situ = actor("司徒来也")
local luzhui = actor("鹿追")

local subanjian = actor("苏半见")

--初始化位置和朝向
dark_all_actors()
situ:setPos(2500, 75)
situ:face_left()
luzhui:setPos(2700, 75)
luzhui:face_left()
subanjian:setPos(700, 75)
subanjian:face_left()

--剧情
situ:movetoX(1500)
wait_twn(luzhui:movetoX(1700),luzhui:daze())
situ:say("苏掌门，第三百⽚岁炙叶已经到⼿，按照约定，这借⾛的⼗九⽚叶⼦，是不是也该如数奉还了？")
subanjian:flip()
subanjian:say("莫急莫急！我作为⽕神树的虔诚信徒，最近⼀直苦⼼研究这岁炙叶，发现了⼀个增加其功效的好法⼦。")
luzhui:jump()
luzhui:say("什么法⼦？")
hide_all_stage_bubble();
subanjian:flip()
subanjian:movetoX(300)
wait_twn(subanjian:flip(),subanjian:flip(),subanjian:daze())
wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈，这你可就要⾔谢我了，我发现只要将这岁炙叶泡⼊酒中，便可直接提升阳⽓，使⼈功⼒⼤增。"))
subanjian:say("但⽬前还不确定，⽼夫不惜拿⾃⼰的⾝体做试验，这可是你们炙家族三百年不可修来的福⽓啊！")
luzhui:shake()
luzhui:say("你！岁炙叶乃是神圣之物，泡在酒中，岂不是腌臜了岁炙叶？！快还回来！")
wait_twn(subanjian:movetoX(500),subanjian:jump(),subanjian:daze())
subanjian:say("如若我偏要泡酒，不想还呢？")
hide_all_stage_bubble();
wait_twn(situ:movetoX(1100),situ:daze())
situ:say("怎么？苏掌⻔想做这失信之⼈？")
wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈哈哈！承诺值⼏个钱？"))
situ:jump()
situ:say("你如此信口雌黄，不守承诺，可想过暮霭⼭庄如何在江湖上⽴⾜？")
shake_stage()
subanjian:jump()
subanjian:say("我暮霭⼭庄在江湖上⽴⾜，⼜不是靠着信守承诺，⽼⼦之前也是守信之⼈，可⻅我守信于⼈，别⼈不⼀定守信于我！")
situ:say("怎么？这江湖之中，还有⼈能骗得过你借⽆还？")
subanjian:say("呵……如今的江湖哪⼉有这号⼈？")
luzhui:shake()
subanjian:say("只不过……那能将我骗过的兄弟，早已死在严寒之中……")
situ:say("真当是骗了你，⼜怎能称作是兄弟？")
subanjian:flip()
wait_twn(play_sfx("Voice/Male1_Sigh_1.wav"),subanjian:say("是啊……他说好⼀起名扬天下，不也将我⼀⼈丢于这世间，尝受这世间冷暖。"))
hide_all_stage_bubble()
wait_twn(luzhui:movetoX(1350),luzhui:daze())
luzhui:say("那⼈到底骗了你什么？")
subanjian:flip()
subanjian:say("⼀件⾐服……⼀件能够抵御严寒的红⾊棉⾐。")
luzhui:jump()
luzhui:say("就只是⼀件⾐服？")
wait_twn(subanjian:jump(),subanjian:shake())
subanjian:say("你⼜懂得什么？这哪⼉是⼀件⾐服……罢了罢了，我与你们说这些做什么？还不如我⼿中的温酒来的痛快。")
situ:say("那你死去的兄弟，看你⽇⽇招摇撞骗，在天之灵岂能安⼼？")
subanjian:shake()
wait_twn(play_sfx("Voice/Male1_Laugh_1.wav"),subanjian:say("哈哈，那个不守信的⼈，我何必求他安⼼……他活在⼈世时便已四处碰壁遭殃，所以才寒⼼离世。"))
subanjian:say("既然这江湖中事事都虚伪，⼈⼈都利⼰，那我苏半⻅⼜何须")
situ:jump()
situ:say("这么说你是不打算将这岁炙叶还给我了？")
subanjian:say("你可听说过，借⽆还有还过东西吗？")
situ:say("那就修怪我不客⽓了。")
subanjian:say("要战便战！")
hide_all_stage_bubble()
situ:rotatetoZ(25)
subanjian:rotatetoZ(-25)
situ:movetoX(700,1500)
subanjian:movetoX(700,1500)



local diplomatic = require("Common/diplomatic")
diplomatic.declare_war("player", "暮霭山庄")

black_scene(0.25)
hide_stage()
set_flag("完成讨要宣战")
light_scene(0.25)
