
show_stage("厨房.png", "厨房")
play_bgm("[override_map]:Music/抒情_柔情似水.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-400, 75)
situ:face_right()
liuming:setPos(1300, 75)
liuming:face_left()
zsniang:setPos(1000, 75)
zsniang:face_right()

wait_twn(situ:movetoX(600), situ:daze())

situ:emotion("KunHuo")
situ:say("三娘，近来饭菜里面都放了些什么啊？")
liuming:say("可不！简直要了命了！")
zsniang:flip()
zsniang:say("这饭菜怎么了？")
situ:emotion("HaiXiu")
situ:say("味道略微有些奇怪不说，似乎还颇有些“祛火润肠”的功效。")
liuming:say("是啊是啊！我这一下午，都跑三四趟了！哎呦，不行！还得去……")
hide_all_stage_bubble()
liuming:flip()
wait_twn(liuming:jump(), liuming:movetoX(3000))
zsniang:say("不应该啊，无非是见这几日燥热了些，所以想准备些药膳调理调理。")
situ:say("这……还是算了，当真虚不受补。")
zsniang:say("按着这药膳的方子，不应该有这样的情况才是，莫非是哪里出了问题？")
situ:say("三娘，虽说这是件好事，可能不能先另想个尝试的法子？")
zsniang:say("掌门，这可真是天大的冤枉！每次尝试新菜，我从来都是自己先尝过的！")
situ:say("那三娘你……当真没有任何问题？！")
zsniang:say("没有！")
situ:emotion()
situ:say("那倒当真奇了，兴许是这食物相生相克，你无意中又吃了能够化解的东西？")
zsniang:say("啊呀，那可就要好好想想了，这厨房中的每样食物，我都有亲自尝过的。")
situ:say("这一厨房的东西你都尝了个遍？")
zsniang:say("是啊，不然那些药膳我怎么敢轻易端给其他人吃？")
situ:say("唉……算了……或许，只是三娘你的体质当真异于常人吧。")
hide_all_stage_bubble()

situ:flip()
wait_twn(situ:jump(), situ:movetoX(-500))

change_favor_by_id("朱三娘", 1)
add_player_item("烧鱼", 1)

black_scene(0.25)
hide_stage()
set_flag("完成朱三娘剧情3")
light_scene(0.25)
