show_stage("虎焰山山洞.png", "虎焰山山洞")
set_bg_mat("ImgPaperFold")
play_bgm("Music/血魔老祖.wav")
light_scene(0.2)

local situ = actor("司徒来也")
local xuemolaozu = actor("血魔老祖")
local cike = actor("[speaker:刺客][img:hero_HeiYiRen]")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-500, 75)
situ:face_right()
xuemolaozu:setPos(1100, 75)
xuemolaozu:face_left()
cike:stylize("Silhouette")
cike:setPos(2500, 75)
cike:face_left()

cike:movetoX(1300)


wait_twn(situ:movetoX(400), situ:daze())
situ:say("老祖师父！小心身后——")
hide_all_stage_bubble()

play_sfx("Story/Slash.mp3")
xuemolaozu:flip()
xuemolaozu:spring_scale(1.5, 1, 1, 0.2)
wait_twn(xuemolaozu:movetoX(1400, 4000), cike:jumpTo(1800, 600), cike:movetoY(-600, 5000))
xuemolaozu:flip()
xuemolaozu:movetoX(1200, 4000)
wait_twn(situ:movetoX(800), situ:daze())
situ:say("老祖师父，没事吧？")
xuemolaozu:say("哈哈，不过是又一个送死的鼠辈。")
situ:say("老祖师父，是谁企图对您不利？")
xuemolaozu:say("行走江湖，总免不了有些血债。此次秘密前来虎焰山，只在豪猪长垄露面一次，不想竟引来了这些刺客。")
xuemolaozu:say("你师兄已先行一步，去查探真相了。")
situ:say("是。")
xuemolaozu:say("小娃娃徒儿，你来找我，有何要事？")
situ:say("老祖师父，自从得了您的神功真传，弟子感悟颇深。但江湖险恶，门派众多，弟子不知该如何应对？")
xuemolaozu:say("江湖之道，强者为尊。以弱胜强，需智勇双全。记住，真正的强者，不仅能以力破敌，更要用心。")
situ:say("请老祖师父指教。")
xuemolaozu:say("就拿那豪猪长垄来说，他们擅长使敌[流血]之术，若你不能及时应对，待你力竭之时，便是他们下杀手之际。")
xuemolaozu:say("他们的阵法严谨，前后呼应，需得细心应对。")
situ:say("老祖师父，弟子若是能避免[流血]，是否就能破解他们的阵法？")
xuemolaozu:say("不错，小娃娃徒儿果然聪明。武学之道，相生相克，你须细细领悟，方能洞悉其中奥妙。")
situ:say("多谢老祖师父点拨，弟子受教了。")

hide_all_stage_bubble()
add_player_item("武学札记", 1)

black_scene(0.25)
hide_stage()
set_flag("完成指点迷津")
light_scene(0.25)
