
show_stage("走廊.png", "圣剑门")
light_scene(0.2)

local jiyeman = actor("姬野蔓")
local yatong = actor("哑童")
local langzigui = actor("朗自归")
local fandaoping = actor("范道平")
local wanglong = actor("王珑")

--初始化位置和朝向
bright_all_actors()

jiyeman:setPos(500, 75)
jiyeman:face_right()
yatong:setPos(800, 75)
yatong:face_left()
langzigui:setPos(1100, 75)
langzigui:face_left()
fandaoping:setPos(1400, 75)
fandaoping:face_left()
wanglong:setPos(1700, 75)
wanglong:face_left()

langzigui:say("各位，都到齐了吧？")
jiyeman:say("除却执剑大人，其余都已在此。")
langzigui:say("执剑大人此次不会亲临，见字如面，其意自明。")
yatong:say("…")
fandaoping:say("执剑大人已久未露面，我等早已预料。")
wanglong:say("四大阁主能在此磨剑阁齐聚，实属难得。记得上次如此盛况，还是在去年寒冬时节。")
jiyeman:say("今年初五，我们也曾相聚，只是某人却因睡意朦胧，未能及时赶来。")
wanglong:say("不知是哪位阁主如此大意？")
jiyeman:say("除了你王珑，还能有谁？")
fandaoping:say("执剑大人已久未发布信条，看来息风谷确有大事发生。")
jiyeman:say("范阁主消息如此灵通，难道不知详情？")
fandaoping:say("且看执剑大人的指示吧。")
langzigui:say("虎焰门一夜之间灰飞烟灭，其原因尚不明朗。五大门仅余其四，息风谷各派恐将陷入动乱，正是圣剑出鞘之时。")
jiyeman:say("我昨日方才得知。")
fandaoping:say("我那日晚上便已得知。")
jiyeman:say("亮剑阁果然消息最为灵通。")
fandaoping:say("哪里哪里，朗阁主恐怕早已洞察一切。")
wanglong:say("虎焰门真的被灭门了？")
jiyeman:say("师兄，你这观剑阁莫非真是终日观灯赏月，不知江湖风波？")
wanglong:say("此事确是令人震惊。")
langzigui:say("此时正是扩张圣剑门版图的大好时机。")
jiyeman:say("抚剑阁得令！")
fandaoping:say("亮剑阁得令！")
wanglong:say("观剑阁得令！")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成圣剑门登场")
light_scene(0.25)
