local subtitles = {"圣剑门走廊"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("走廊.png", "圣剑门")
play_bgm("Music/热血_侠肝义胆高潮.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local wanglong = actor("王珑")
local langzigui = actor("朗自归")
local jiyeman = actor("姬野蔓")
local fandaoping = actor("范道平")
local yatong = actor("哑童")

--圣剑门/执剑人的秘密.lua

--初始化位置和朝向
bright_all_actors()

situ:setPos(2500, 75)
situ:face_left()

wanglong:setPos(2500, 300)
wanglong:face_right()
langzigui:setPos(2500, 300)
langzigui:face_right()
jiyeman:setPos(2500, 300)
jiyeman:face_right()
fandaoping:setPos(2500, 300)
fandaoping:face_right()

yatong:setPos(-500, 75)
yatong:face_right()

wanglong:moveTo(500,75,3500)
langzigui:moveTo(800,75,3500)
jiyeman:moveTo(1000,75,3500)
wait_twn(fandaoping:moveTo(1200,75,3500),fandaoping:daze())
fandaoping:jump()
fandaoping:flip()
fandaoping:say("这小子着实可恶…")
stage_narration("还未喘息片刻就见…")
wait_twn(situ:jumpTo(1750,75),situ:daze())
situ:jump()
fandaoping:flip()
situ:say("哼！你们已经退无可退了！")
situ:say("快说百里烟波在哪里？")
langzigui:say("百里大人就在这石门之后，你若是敢便去打开这石门吧！")
situ:jump()
situ:say("哼，百里烟波是怕了吗！")
fandaoping:jump()
fandaoping:say("不许你这样说执剑大人！")
hide_all_stage_bubble()
fandaoping:flip()
wait_twn(fandaoping:movetoY(-30),fandaoping:daze())
fandaoping:say("执剑大人！请您出山吧！这虎焰门小厮今日竟敢在我圣剑门如此叫嚣，您快出山将他们大卸八块！")
stage_narration("范道平说完就见石门中走出一人……")
situ:say("百里烟波，寻你还真是废了我九牛二虎之力啊！")
jiyeman:jump()
jiyeman:flip()
jiyeman:say("大人……是百里烟波大人吗……")
hide_all_stage_bubble()

langzigui:flip()
wanglong:flip()
jiyeman:movetoY(-30)

wait_twn(wanglong:movetoY(-30),langzigui:movetoY(-30),wanglong:daze())

wait_twn(yatong:movetoX(170),yatong:daze())

yatong:say("……")
situ:say("这……这就是百里烟波？")
jiyeman:movetoY(30)
langzigui:movetoY(30)
wanglong:movetoY(30)
wait_twn(fandaoping:movetoY(30),fandaoping:daze())
langzigui:jump()
langzigui:say("不……不对，不是百里烟波大人！")
fandaoping:say("哑童？……执剑人呢？！")

yatong:say("……")

situ:jump()
situ:say("此时微笑时何意？？百里烟波在哪儿？")

jiyeman:jump()
jiyeman:say("哑童！现在可不是开玩笑的时候！圣剑门就要覆灭了……执剑人他在哪里？")
situ:jump()
situ:say("你摊手是什么意思？执剑人呢？百里烟波呢？你倒是说话呀！")

jiyeman:say("这孩子真是哑巴，执剑人闭关这些年都是通过信笺，让哑童来传递指令的。")
fandaoping:say("可是执剑人没在里面，那是谁在给我们传递指令？")
--此处或许需要一个紫色火焰的特效来表示他死了

yatong:jump()
shake_stage()
yatong:shake()

wait_twn(play_sfx("Voice/Female1_Death_2.wav"),yatong:say("呃呃！！"))
yatong:hide()
langzigui:shake()
langzigui:say("这青色的火焰石什么！？这……好好的活人如何能在一瞬间就被这邪门东西烧成灰的？")
situ:say("青色火焰……夜鸦……")
hide_all_stage_bubble()
wait_twn(wanglong:movetoX(170),wanglong:daze())
wanglong:shake()
wanglong:say("果然如此……执剑人怕是早已不在了……")
fandaoping:jump()
fandaoping:say("胖子说什么？什么如你所料？你是不是知道什么？")
wanglong:flip()
wanglong:say("去年起，我就觉得执剑人不对劲了……不对，也许是更早的时候……")
jiyeman:jump()
jiyeman:say("什么？！你是说，百里大人早就不在里面了？")
wanglong:shake()
wanglong:say("百里大人也曾闭关修炼过，但从未这么久……想必，早已经遭遇不测。")

langzigui:say("快四年了，快四年没见过执剑大人了。")
wanglong:say("起初，我只是觉得腾云圣剑有些不对劲，以前执剑人哪怕是闭关，他也会把腾云圣剑插在执剑王座右手边的剑匣内，但这次没有……")
langzigui:shake()
langzigui:say("圣剑……我们居然没有发现！")
wanglong:say("而且近几年哑童传令时，听不到石门后密室内有任何动静，就连剑风的声音这两年都未能听到……我逐渐确定了自己的猜想，执剑人根本不在里面了……")
jiyeman:jump()
jiyeman:say("你不是说，执剑人的腾云圣剑遗落在野外，命令你去寻找吗？")
wanglong:shake()
wanglong:say("其实根本就没有这个任务！我……是说给有心之人。")

situ:say("你是说给哑童听的？")
wanglong:shake()
wanglong:say("是的，我这么说，就是要试探试探哑童身后，是不是真的有执剑人的存在，但我这个说法却没有得到任何反馈，所以……我知道里面应该是没有人了。")
hide_all_stage_bubble()
wait_twn(fandaoping:movetoX(500),fandaoping:daze())
fandaoping:jump()
fandaoping:say("王珑！你这家伙既然早就知道，怎么不早说！")
jiyeman:shake()
jiyeman:say("怪不得王阁主成天这么悠闲，原来是早就知晓……这么便说得通了。")
langzigui:jump()
langzigui:say("我们既然被骗了这么多年…那么执剑人……这哑童的背后，到底是谁在操控！")
wanglong:shake()
wanglong:say("我能想通百里大人遇害之事，可我一直没想通，息风谷谁能做到这一切……")

situ:say("是夜鸦……")
langzigui:flip()
fandaoping:flip()
jiyeman:flip()

langzigui:jump()
langzigui:say("夜鸦？！")

fandaoping:say("夜鸦……到底是何方人物……")
situ:say("刚才哑童身上的青色火焰，是夜鸦的伎俩！")

jiyeman:say("这就奇怪了，哑童足不出户，这夜鸦是怎么给哑童传信息的？")
langzigui:say("哑童每个月都会出门玩耍半天，那是之前执剑人给他的特权。")

situ:say("哑童每个月出门，会去哪里？")
wanglong:flip()
wanglong:say("哑童无父无母，在江湖上只有一个朋友，是一个年龄相仿的小书童。")
situ:say("那小书童可知晓下落？！")
wanglong:flip()
wanglong:say("画桥书苑里，何惧风的小书童。")
situ:flip()
situ:say("画桥……书苑……")
langzigui:jump()
langzigui:say("怎么？将我圣剑门搅得天翻地覆，就想一走了之？！")
situ:flip()
langzigui:jump()
situ:say("呵呵……险些忘了，其他人可以放过，倒是你……还有一笔账要还！")
langzigui:say("哼！要战便战！")
langzigui:movetoX(1500,5000)
situ:movetoX(1500,5000)

hide_all_stage_bubble()

black_scene(0.1)
hide_stage()
set_flag("完成执剑人的秘密")
light_scene(0.25)
