local subtitles = {"磨剑阁"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("室内书房.png", "磨剑阁")
play_bgm("Music/山雨欲来风满楼.wav", 0.1)
light_scene(0.2)

local langzigui = actor("朗自归")
local mabian = actor("马鞭")
local niuchui = actor("牛锤")


local situ = actor("司徒来也")
local qiu = actor("秋")

--初始化位置和朝向
bright_all_actors()
langzigui:setPos(-500, 75)
langzigui:face_right()
mabian:setPos(-800, 75)
mabian:face_right()
niuchui:setPos(-1100, 75)
niuchui:face_right()

situ:setPos(2500, 75)
situ:face_left()
qiu:setPos(2800, 75)
qiu:face_left()


--剧情
situ:movetoX(1450)
wait_twn(qiu:movetoX(1700),qiu:daze())
situ:jump()
situ:say("久闻朗阁主大名，今日特来拜访。")
hide_all_stage_bubble()
langzigui:movetoX(700)
mabian:movetoX(400)
wait_twn(niuchui:movetoX(200),niuchui:daze())
langzigui:say("无事不登三宝殿，几位这是……")
situ:say("想必朗阁主自是知晓我们为何前来。")
langzigui:flip()
langzigui:say("哼，诸位不请自来，朗某人又怎会知晓？")
situ:say("同为江湖中人，便不拐弯抹角了，此次前来，是为讨一笔债。")
langzigui:flip()
langzigui:say("哦？朗某可从未记得欠过什么。")
qiu:jump()
qiu:say("骗人！十七年前你敢说自己没有欠下一笔血债吗？")
langzigui:say("十七年前？")
hide_all_stage_bubble()

wait_twn(qiu:movetoX(1200,1500),qiu:daze())
qiu:jump()
qiu:say("十七年前的那对夫妇……怎么？不记得了？")
langzigui:shake()
langzigui:say("什么夫妇？不要胡说！")

qiu:say("当年你亲手杀死一对夫妻和一个襁褓中的婴儿，不记得了？")
langzigui:shake()
langzigui:say("无凭无据！休要诬陷好人！")
qiu:jump()
qiu:say("无凭无据？你可知那妇人为了求生，抱着孩子坠下山崖。终是苍天有眼，那个婴儿活了下来。")
langzigui:shake()
langzigui:say("莫非……")
qiu:say("不错，那孩子如今就站在你面前！")
mabian:jump()
mabian:say("那……那你怎么证明人是我们阁主害的？")
situ:say("笑话，冤有头债有主！难道我们虎焰门的人还能冤枉好人？")
mabian:jump()
mabian:say("这话还真说到点子上了！十七年了……当年的事情谁说得准？再说一个婴儿懂什么？怎可作数？若是记错了，又或是蓄意找茬……")
qiu:say("你！")
mabian:say("欲加之罪何患无辞，阁下不会是想栽赃吧？")
situ:say("胡说！")
mabian:jump()
mabian:say("笑话！那你们倒是拿出证据呀？不敢了吧……")
situ:say("朗阁主抢去的宝物就是物证！")
mabian:say("宝物？什么宝物！从来没有什么宝物！")
situ:say("罢了罢了，只是敢问一句，这鲜血浇灌出来的宝物，可真有传说中那般奇效？")
niuchui:say("别……别浑说！我们怎么会知道落梅金茎是何威力啊！见都没见过！")
situ:say("哦？我也只提的是宝贝，可从未提过落梅金茎，你为何知道是落梅金茎？")
niuchui:say("我……")
wait_twn(langzigui:flip(),langzigui:say("哼！就算是我做的又如何……这世间至宝，就应当配上世间至尊！"))
qiu:jump()
qiu:say("狡辩！")
langzigui:flip()
langzigui:jump()
langzigui:say("胡搅蛮缠的是你吧！弱肉强食，能者居上，本就是天道规律！是你一直看不清，逆天而为！")
qiu:jump()
qiu:say("简直一派胡言！")
langzigui:say("如今圣剑门是息风谷的王者至尊，只有圣剑门才能给息风谷带来最终的安宁，这个过程中总要献祭，这不是仇恨，这是荣誉！")
qiu:shake()
qiu:say("混蛋！我只知道“杀人偿命，天经地义”，这笔血债，定要你血偿！")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成杀父之仇")
light_scene(0.25)
