local subtitles = {"深夜 磨剑阁"}

--初始化场景和背景音乐
show_cg(subtitles)
show_stage("室内书房.png", "磨剑阁")
play_bgm("Music/阴冷_段小年.mp3", 0.1)
light_scene(0.2)


local langzigui = actor("朗自归")
local mabian = actor("马鞭")
local niuchui = actor("牛锤")

--初始化位置和朝向
bright_all_actors()
langzigui:setPos(-500, 200)
langzigui:face_right()
mabian:setPos(2400, 75)
mabian:face_left()
niuchui:setPos(2700, 75)
niuchui:face_left()

--剧情
stage_narration("远处传来两个人的声音")
mabian:movetoX(800)
wait_twn(niuchui:movetoX(1100),niuchui:daze())
mabian:flip()
mabian:shake()
mabian:say("唉……")
niuchui:jump()
niuchui:say("大晚上的怎么唉声叹气的，晦气不晦气？")
mabian:movetoX(900)
mabian:shake()
mabian:say("哎呀……这执剑人下令平了这息风谷，这原本是个肥差，可咱们阁主却……却偏选仙竹门这硬茬儿……这……")
niuchui:say("你这小子，莫非质疑阁主打不下来？！")
mabian:jump()
mabian:say("呸！我可没这么说！只听说那掌门南宫燕用毒可更厉害了，我这不是担心……")
niuchui:jump()
niuchui:say("担心屁！咱们磨剑阁可是门中最强！若不挑厉害的打，还不被其他那帮王八蛋笑死？再说你怎么就知道咱阁主就打不过？")
mabian:say("唉，要是十几年前朗阁主得到那宝贝的时候，没有献给执剑人，而是收为己用，别说区区一个南宫燕了，就算是这圣剑门……")
wait_twn(langzigui:moveTo(300,75,3000),langzigui:daze(0))
langzigui:jump()
langzigui:say("放肆！！")
mabian:flip()
niuchui:jump()
mabian:jump()
mabian:say("哎呦！阁……阁主！")
niuchui:say("这马兄弟也是无心多嘴……阁主！您已经赏了一巴掌，便别再计较了。")
langzigui:jump()
langzigui:say("执剑人掌管圣剑门中无上权利，从不容旁人置疑。又岂是你等能肆意议论的？若有二次，当心项上人头！")
mabian:say("是！是！谢阁主不杀之恩！ ")
hide_all_stage_bubble()
mabian:flip()
niuchui:flip()
mabian:movetoX(2000)
niuchui:movetoX(2000)


black_scene(0.25)
hide_stage()
set_flag("完成磨剑阁的忠诚")
light_scene(0.25)
