
show_stage("仙竹门.png", "仙竹门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local nangongyan = actor("南宫燕")
local lvpaoni = actor("绿袍尼")
local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")

--初始化位置和朝向
bright_all_actors()

situ:setPos(1100, 75)
situ:face_right()
qiliuge:setPos(800, 75)
qiliuge:face_right()
nangongyan:setPos(1400, 75)
nangongyan:face_left()
lvpaoni:setPos(1700, 75)
lvpaoni:face_left()

nangongyan:say("我…竟败了…")
situ:say("南宫燕，你梦寐以求的姑获鸟之瓶，如今已在我手。")
nangongyan:say("还给我！那本是我的！")
--司徒来也手一松，姑获鸟之瓶坠落下，砰的一声，碎片溅到了南宫燕的脸上
lvpaoni:say("什么？！")
nangongyan:say("你——")
situ:say("今日我特来告知，依赖掠夺生灵以增强己身之恶行，在息风谷断不可行！")
nangongyan:say("呵呵……你与(player:fname)雷那个老东西，真是父子情深……")
situ:say("你是指我父亲？")
nangongyan:say("二十年前，我发掘了黑水仙，修炼毒术，只为与他并肩作战，匹配他的武艺。你或许觉得荒谬。")
lvpaoni:say("……")
situ:say("你是说，你们本是恋人？")
nangongyan:say("他武艺高强，才华横溢，我心中不忿，欲与他比肩。")
situ:say("强弱本无定数，何必如此？")
nangongyan:say("黑水仙与我的体质相合，我乃天生的毒术奇才，方能与他并驾齐驱。")
situ:say("然而，真正的男子汉看重的是女子的心地。你如此修炼，岂非本末倒置？")
nangongyan:say("毒术有何不妥？其他武学不也是以伤人为先？")
situ:say("但你的内心，已被毒所侵蚀。")
nangongyan:say("你娘亲，当年必定也是这样迷惑了(player:fname)雷。")
situ:say("不可侮辱我娘亲！她即便是你的亲妹妹，也不应受此侮辱。")
nangongyan:say("我以为，你已经死了。")
situ:say("你在胡说些什么？")
nangongyan:say("黑水仙加麝香，孕者服用，胎儿必死。我亲眼见南宫紫饮下那碗汤，你怎能幸免？")
situ:say("你竟在我母亲孕期下此毒手！")
nangongyan:say("啊！我明白了，我明白了！")
situ:say("明白什么？")
nangongyan:say("你根本就……不是……")

destroy_menpai("仙竹门")

hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成仙竹门灭亡结局")
light_scene(0.25)
