show_stage("酒香亭.png", "酒家")
play_bgm("Music/秋.wav")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local qiliuge = actor("齐六哥")
local qiu = actor("秋")
local lai3 = actor("赖三")
local situ = actor("司徒来也")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:bright()
situ:setPos(-400, 75)
situ:face_right()

qiliuge:bright()
qiliuge:setPos(-600, 75)
qiliuge:face_right()
qiu:setOverrideName("？？？")
qiu:face_right()
qiu:setPos(1700, -600)
lai3:face_left()
lai3:setPos(3000, 75)

wait_twn(qiu:movetoY(75))

if not has_flag("酒香亭第一次招募") then

    wait_twn(lai3:movetoX(1500), lai3:offsetY(-50), lai3:flip())
    lai3:say("客官, 这是你点的酒菜")
    hide_all_stage_bubble()
    wait_twn(lai3:daze(0.2), lai3:offsetY(50))

    situ:offsetX(900)
    wait_twn(qiliuge:offsetX(900), qiliuge:daze())

    lai3:flip()

    qiliuge:say("此处地灵而人杰，便是先前提到过各路英雄豪杰隐逸之所了。")
    situ:flip()
    situ:say("难怪父亲闲暇时也常来此处逗留，为此还总被娘亲埋怨，原来是为了物色人才。")
    qiliuge:say("哈哈，说来惭愧，十年前我也在这里同老掌门聊了很久。")
    situ:emotion("WeiXiao")
    situ:say("这一晃，竟然有十年了呀……")
    wait_twn(lai3:offsetX(-600))
    situ:emotion()
    situ:flip()
    lai3:say("哎呀，竟是虎焰门的稀客！今天的酒记在我账上便是，就当是一点心意了。")
    qiliuge:say("得了吧老三，你挣点酒钱也不容易，近来道上动荡，很辛苦吧。")
    lai3:say("唉，若不是虎焰门罩着，我这铺子怕早关张了。这不？今天到现在，就那一位客人。")
else
    --不是第一次赖三就别出来了
    lai3:setPos(2400, 75)
    situ:offsetX(900)
    wait_twn(qiliuge:offsetX(900), qiliuge:daze())
end

situ:say("那个人，好生奇怪……")
qiu:bright()
wait_twn(qiu:shake(), qiu:flip())
stage_narration("靠墙而坐的蓬头长发少年似乎被冒犯到了，投来凶狠目光")
situ:emotion("JingYa")
situ:say("哇，这也能听见。")
qiu:say("何事？")
situ:say("哎呀，是我冒犯了……")
qiu:shake()
qiu:say("哼！")
wait_twn(situ:offsetX(430))
lai3:flip()
wait_twn(situ:offsetX(430))
situ:emotion("YaoYa")
situ:say("好凶……")
wait_twn(lai3:offsetX(60))
if not has_flag("酒香亭第一次招募") then
    lai3:say("这位少年来自北方丛林部落，故而不同于咱们中原人。")
    lai3:say("没什么事小的先退下了")
    hide_all_stage_bubble()
    wait_twn(lai3:offsetX(1500))
else
    qiu:say("……")
end
situ:emotion("WeiXiao")
situ:say("侠士莫动怒，在下只是见阁下气质不凡，敢问尊姓大名？")
qiu:say("……秋")
situ:say("？")
qiu:say("秋天的秋。")
qiu:setOverrideName("秋")
situ:say("阁下一人独饮恐无意趣，可介意在下同这位齐六哥相陪？")
qiu:say("……")
wait_twn(qiliuge:offsetX(800))
qiliuge:say("掌门，我听说他得部落收留，是被狼乳喂养大的孤儿，却不知为何在此。")
situ:emotion("JingYa")
situ:say("喝狼的乳汁长大？")
qiu:say("？")
situ:emotion("WeiXiao")
situ:say("哎呀，失礼、失礼了。")
qiu:say("无妨。何事？")
situ:say("相识便是缘分，故而想与侠士交个朋友。")
qiu:say("加入……你们？")
situ:say("这……哈哈，侠士直言直语，确实干脆。在下确有此意，只是不知意下如何？")
qiu:say("能复仇吗？")
situ:emotion()
situ:say("复仇？你的仇人是谁？")
qiu:say("杀害我父母？")
situ:say("杀害你父母的仇人？")
qiu:say("是。")
situ:emotion("BeiShang")
situ:say("实不相瞒，我和阁下一样。")
qiu:say("仇，报了吗？")
situ:say("君子报仇，十年不晚。")
qiu:say("不错……")
situ:emotion("WeiSuo")
situ:say("阁下为何递来这坛酒？莫非……")
qiu:say("朋友！")
situ:say("好！一醉方休！")
situ:emotion()

stage_narration("秋没有说话，而是给自己和(player:fullname)默默倒了酒……")

black_scene(1)
wait_twn(situ:offsetY(-100))
situ:standback()
wait_for_seconds(1)
light_scene(2)
stage_narration("许久后")

wait_twn(qiliuge:offsetX(50), qiliuge:offsetX(-50, 300), qiliuge:daze(), qiliuge:offsetX(50), qiliuge:offsetX(-50, 300), qiliuge:daze())
qiliuge:say("掌门！掌门？酒量明明不行……这都醉成什么样了。好沉，扛都扛不动……")
qiu:offsetX(-80)
qiu:say("我来。")
wait_twn(qiu:offsetY(-60), qiu:offsetY(60, 300))
wait_twn(situ:jumpTo(1730, 130), situ:flip())

qiu:say("回……虎焰门")

hide_all_stage_bubble()

qiu:movetoX(-500)
situ:movetoX(-500)
wait_twn(qiliuge:daze(1), qiliuge:flip(), qiliuge:movetoX(-500))

player_add_disciple("秋")

black_scene(0.25)
set_flag("酒香亭第一次招募")
set_flag("完成招募秋")
hide_stage()
light_scene(0.25)
