show_stage("庭院.png", "虎焰门外")
set_bg_mat("ImgPaperFold")
play_bgm("Music/舒缓_云淡风轻.wav")
light_scene(0.2)

local situlei = actor("[speaker:(player:fname)雷][img:hero_SiTuLei]")
local nangongzi = actor("[speaker:南宫紫][img:hero_NaoGongZi]")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
nangongzi:setPos(-400, 75)
nangongzi:face_right()
situlei:setPos(1700, -500)
situlei:face_left()

wait_twn(situlei:jumpTo(1400, 75))
situlei:say("夫人——")
wait_twn(hide_all_stage_bubble(), situlei:offsetX(-300, 500))
situlei:say("夫人——")
wait_twn(hide_all_stage_bubble(), situlei:flip(), situlei:offsetX(300, 500))
situlei:say("夫人——")
wait_twn(hide_all_stage_bubble(), situlei:flip(), situlei:offsetX(-300, 500))
wait_twn(nangongzi:movetoX(800, 2500), situlei:offsetX(100))
play_sfx("Story/Fist.mp3")
wait_twn(situlei:shake(65), situlei:daze(0.1))
situlei:say("夫人，您这是要往何处去？")
wait_twn(hide_all_stage_bubble(), situlei:offsetX(-50), situlei:offsetX(50, 300), situlei:offsetX(-50), situlei:offsetX(50, 300))
nangongzi:say("(player:fname)雷，你这是何等失态？身为一派掌门，岂能如此慌张？")
situlei:say("夫人，那小子在屋里安然无恙，您何必亲自前往？")
nangongzi:say("我儿，难道我还不能一见？")
situlei:say("自然，自然能。")
nangongzi:say("那你为何拦我？")
situlei:say("我……只是担心夫人您太过操劳。")
nangongzi:say("心神不宁，必有隐情。你们父子向来是一丘之貉，定是有事瞒我！")
nangongzi:say("让我过去看看！")
situlei:say("我这不是心疼夫人嘛……")
nangongzi:say("老娘我数到三！")
situlei:jump()
situlei:flip()
situlei:standback()
situlei:say("夫人请——")
wait_twn(hide_all_stage_bubble(), nangongzi:movetoX(3000))
situlei:say("儿子啊，你的小聪明终究是敌不过你娘的。")
situlei:say("得，还是去看看吧。若是紫妹真的生气了，我还得去劝劝……")
wait_twn(hide_all_stage_bubble(), situlei:movetoX(3000))

black_scene(0.25)
hide_stage()

show_stage("写意室内.png", "虎焰门东厢房")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local situlei = actor("[speaker:(player:fname)雷][img:hero_SiTuLei]")
local nangongzi = actor("[speaker:南宫紫][img:hero_NaoGongZi]")
local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
nangongzi:setPos(-400, 75)
nangongzi:face_right()
situlei:setPos(-700, 75)
situlei:face_right()
situ:setPos(1400, 75)
situ:stylize("Silhouette")
situ:face_right()
qiliuge:setPos(-700, 75)
qiliuge:face_right()

wait_twn(nangongzi:movetoX(1000))
nangongzi:say("儿子——")
situ:say("……")
nangongzi:say("(player:gname)，你这是何苦？")
situ:say("……")
nangongzi:say("(player:gname)，娘知道你心中不畅，被拘在此地，定是难受得很。")
situ:say("……")
nangongzi:say("但你若不顶撞娘亲，娘又怎舍得让你在房中闷上许久？")
situ:say("……")
nangongzi:say("那<color=red>得月楼</color>鱼龙混杂，你身为虎焰门的少门主，怎可轻易涉足？你竟还在那里与人争斗，这……这如何使得？")
situ:say("……")
nangongzi:say("江湖义气非是儿戏，虎焰门自有门规，若不惩你，门规何在？门人弟子又该如何看待？")
situ:say("……")
nangongzi:say("娘也不忍心，你若能认个错，此事便就此揭过，如何？")
situ:say("……")
nangongzi:say("(player:gname)，娘可要进去了——")
play_sfx("Story/OpenDoor.mp3")
hide_all_stage_bubble()
black_scene(1)
wait_for_seconds(1)
light_scene(1)
nangongzi:movetoX(1200)
wait_twn(situlei:movetoX(900, 2500))

situlei:say("夫人且慢！")

nangongzi:shake()
nangongzi:say("这是……")
nangongzi:say("假人？何人所为？")
situlei:say("完了，我果然劝不住……")
wait_twn(hide_all_stage_bubble(), nangongzi:flip(), nangongzi:movetoX(900), situlei:jumpTo(1100, 75), situlei:flip())
nangongzi:shake_bubble(65, 0.8)
nangongzi:shake(65, 0.8)

nangongzi:say("齐老六！")
wait_twn(qiliuge:movetoX(500))
qiliuge:emotion("KunHuo")
qiliuge:say("夫人，有何吩咐？")
nangongzi:say("去把(player:fullname)这个逆子给我抓回来！")
qiliuge:emotion("JingYa")
qiliuge:say("掌门，这……")
qiliuge:emotion()
situlei:say("老齐，我们一起去。")
nangongzi:flip()
nangongzi:say("你站住！你也别想置身事外！")
situlei:say("好吧。")
nangongzi:flip()
qiliuge:say("不知大少爷在何处……")
situlei:say("唉——")
situlei:say("他去了得月楼！")
hide_all_stage_bubble()
set_flag("完成调虎离山")
wait_twn(qiliuge:flip(), qiliuge:movetoX(-500))

black_scene(0.25)
hide_stage()
light_scene(0.25)
