show_stage("百草清涧.png", "虎焰门郊外")
set_bg_mat("ImgPaperFold")
play_bgm("[override_map]:Music/日常_烟火人间.wav", 1)
light_scene(0.25)

local qiliuge = actor("齐六哥")
local liangsheng = actor("梁胜")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
bright_all_actors()
qiliuge:setPos(700, -500)
qiliuge:face_right()
liangsheng:setPos(700, -500)
liangsheng:stylize("Silhouette")
liangsheng:setOverrideName("？？？")
liangsheng:face_right()
wait_twn(qiliuge:jumpTo(700, 75), qiliuge:offsetX(250))
qiliuge:say("大少爷，得月楼！")
wait_twn(hide_all_stage_bubble(), qiliuge:movetoX(3000))
wait_twn(liangsheng:jumpTo(700, 75), liangsheng:offsetX(250))
stop_bgm(1)
liangsheng:say("桀桀桀，前面那就是虎焰门的齐老六！")
liangsheng:say("跟紧了！")
wait_twn(hide_all_stage_bubble(), liangsheng:movetoX(3000))

black_scene(0.25)
hide_stage()
set_flag("完成尾随其后")
unlock_menpai("虎焰门", false)
light_scene(0.25)
executefile("Guide/夜访佳人_引导")
