show_stage("厨房.png", "厨房")
set_bg_mat("ImgPaperFold")
play_bgm("Music/日常_烟火人间.wav", 0.1)
light_scene(0.2)

local qiliuge = actor("齐六哥")
local situ = actor("司徒来也")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-400, 75)
situ:face_right()
qiliuge:setPos(-700, 75)
qiliuge:face_right()
liuming:setPos(540, -500)
liuming:face_left()
zsniang:setPos(540, -500)
zsniang:face_right()

wait_twn(liuming:jumpTo(1100, 75), zsniang:jumpTo(800, 75))
zsniang:say("说话便说话，休得手脚不老实。")
wait_twn(liuming:jumpTo(1000, 75), liuming:daze())
liuming:say("哦？现在才嫌弃？嘿嘿，后悔？晚喽！")
zsniang:shake()
zsniang:say("你呀，真是我命中注定的冤家。")
liuming:say("再说，这里就咱俩人，搂一下怎么了？")
situ:movetoX(600)
wait_twn(qiliuge:movetoX(300), qiliuge:daze())
situ:emotion("HaiXiu")
qiliuge:emotion("HaiXiu")
situ:say("谁说只有你们两个？")
situ:emotion()
liuming:jump()
zsniang:flip()
wait_twn(zsniang:jump(), zsniang:daze())
qiliuge:say("咳咳……咳咳……")
qiliuge:emotion()
zsniang:offsetX(150)
liuming:offsetX(100)
liuming:say("大、大少爷？！齐总管？！这……俺……她……")
situ:say("罢了罢了，不用解释了。这地方也不是只有你们来过，下次注意就是。")
zsniang:say("大少爷，难道你一直知道这个地方？")
situ:say("当然，这西耳房的角门通街，夹道又僻静，私相授受的，不都是挑这边行方便？")
liuming:say("难怪大少爷你走得如此轻车熟路？")
situ:emotion("WeiXiao")
situ:say("你嘀咕了句什么？")
liuming:say("俺是说大少爷你怎么还知道这里的门路？")
situ:emotion()
situ:say("哦，那当然是躲……嘿，你俩这事儿还没完呢，问这么多干什么？")
qiliuge:say("大少爷所言甚是！禁酗禁赌、男女大防，门中上下一视同仁。")
situ:emotion("WeiSuo")
situ:say("可不？你们俩这事儿……")
liuming:offsetY(-100)
wait_twn(zsniang:offsetY(-100), zsniang:daze())
zsniang:say("大少爷，齐总管，我们……")
liuming:say("俺同三娘三娘虽还未婚配，但也是真心相爱。")
qiliuge:emotion("NaoHuo")
qiliuge:say("可夫人有严令！便是不论男女之事，伙工、厨娘假职务之便渎职，这可徇不得私！")
qiliuge:emotion()
situ:emotion()
situ:say("不过……")
liuming:say("大少爷？")
zsniang:say("？")
qiliuge:say("？")
situ:emotion("BeiShang")
situ:say("若母亲问起如何发现这二人私情，又怎么解释？这边偏僻却也进出方便，若真被封了禁了……")
qiliuge:emotion("JingYa")
qiliuge:say("大少爷，您还敢偷摸往外跑啊？掌门可还“押”在夫人那儿呢……")
liuming:say("齐总管，掌门怎么被“押”了？")
qiliuge:say("此事说来话长……")
qiliuge:emotion()
situ:emotion()
situ:say("哎……")
qiliuge:say("大少爷？")
situ:emotion("WeiXiao")
situ:say("刘明！朱三娘！")
situ:say("这次便罢了！")
situ:emotion()
liuming:say("!")
zsniang:say("！")
qiliuge:say("你俩还不散了？")
liuming:offsetY(100)
wait_twn(zsniang:offsetY(100), zsniang:daze())
liuming:say("大少爷简直再生父母！")
zsniang:say("谢大少爷！")
hide_all_stage_bubble()
zsniang:flip()
wait_twn(zsniang:jump(), zsniang:movetoX(2100))
wait_twn(liuming:flip(), liuming:jump(), liuming:movetoX(1200), liuming:daze())
situ:say("刘明！你站住！")
liuming:flip()
liuming:say("大少爷？")
situ:say("你也是该成家立室了。挑个吉日，将三娘娶回家吧。")
hide_all_stage_bubble()
stop_bgm()
shake_stage(20, 1)
zsniang:say("啊——")
wait_twn(liuming:flip())
play_bgm("Music/山雨欲来风满楼.wav")
liuming:shake_bubble(65)
liuming:shake(65)
liuming:say("三娘！")
hide_all_stage_bubble()
wait_twn(liuming:movetoX(1500))
qiliuge:say("怎么了？！")
situ:say("什么事？！")
hide_all_stage_bubble()
liuming:movetoX(2500)
qiliuge:movetoX(2500)
wait_twn(situ:movetoX(2500))

black_scene(0.25)
hide_stage()

show_stage("bg_166.png", "虎焰门大堂")
set_bg_mat("ImgPaperFold")

-- local filter = add_camera_filter("CameraFilterPack_AAA_BloodOnScreen")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-600, 75)
situ:face_right()
qiliuge:setPos(-800, 75)
qiliuge:face_right()
zsniang:setPos(-400, 75)
zsniang:face_right()
liuming:setPos(-200, 75)
liuming:face_right()

zsniang:movetoX(1500)
liuming:movetoX(1300)
situ:movetoX(1000)
wait_twn(qiliuge:movetoX(700), qiliuge:daze())

qiliuge:emotion("JingYa")
qiliuge:say("这……这是怎么回事？一切还好好的，怎么一夜之间……")
liuming:say("怎么会这样？大堂怎么会变成这样？")
zsniang:say("死了……都、都死了……虎焰门上下，难道遭遇了不测？")

stage_narration("虎焰门中横七竖八的躺着被杀死的门人，看上去都没有打斗的痕迹，全部是一击毙命。")

situ:emotion("JingYa")
situ:say("……")
zsniang:movetoX(1700)
wait_twn(liuming:movetoX(1500), liuming:daze())
liuming:say("虎焰堂怎么也会遭受此等横祸？")
wait_twn(zsniang:offsetY(-100), zsniang:daze())
zsniang:say("这门槛上还有三道划痕！")
zsniang:offsetY(100)
qiliuge:say("莫非掌门同夫人也……")
qiliuge:emotion()
hide_all_stage_bubble()
situ:emotion()
situ:movetoX(3000)
qiliuge:movetoX(3000)
zsniang:movetoX(3000)
wait_twn(liuming:movetoX(3000))

black_scene(0.25)
-- remove_camera_filter("CameraFilterPack_AAA_BloodOnScreen")
hide_stage()

play_bgm("Music/ThunderRain.mp3")
show_stage("写意室内.png", "虎焰门东厢房")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-200, 75)
situ:face_right()
situ:emotion("KuQi")
qiliuge:setPos(-400, 75)
qiliuge:face_right()
zsniang:setPos(-200, 75)
zsniang:face_right()
liuming:setPos(-400, 75)
liuming:face_right()

wait_twn(situ:movetoX(1300), situ:daze())
situ:say("爹——娘——")
wait_twn(qiliuge:movetoX(1000), qiliuge:daze())
qiliuge:say("掌门！夫人！怎么……怎么也……")
qiliuge:say("怎么办……")
situ:emotion("BeiShang")
situ:say("怎么办？")
situ:emotion("KuQi")
situ:say("怎么办……")
qiliuge:say("大少爷，掌门同夫人……都已经……去了")
hide_all_stage_bubble()
--环视四周
for i = 1, 3 do
    wait_twn(situ:flip(0.2), situ:daze())
end
situ:say("怎么办？")
hide_all_stage_bubble()
situ:offsetY(-200)
wait_twn(shake_stage(20, 3))
black_scene(1)
situ:standback()
wait_for_seconds(1)
light_scene(1)
liuming:movetoX(600)
wait_twn(zsniang:movetoX(400), zsniang:daze())
qiliuge:flip()
qiliuge:emotion("KunHuo")
qiliuge:say("刘明？朱三娘？你们怎么受伤了？")
qiliuge:emotion()
zsniang:say("大少爷！齐总管！外面，外面！有人挑衅！")
stage_narration("虎焰门的怂包！快滚出来拜见你爷爷！")
situ:emotion("NaoHuo")
situ:say("欺人太甚！")
hide_all_stage_bubble()
wait_twn(situ:offsetY(200), situ:movetoX(-500))
qiliuge:emotion("NaoHuo")
qiliuge:say("大少爷！")
qiliuge:emotion()
hide_all_stage_bubble()
wait_twn(qiliuge:movetoX(-500))
liuming:say("那帮混蛋！俺跟你们拼了！")
zsniang:say("明哥小心！")
hide_all_stage_bubble()
liuming:flip()
wait_twn(liuming:movetoX(-500), zsniang:flip(), zsniang:movetoX(-500))

role_add_affix("司徒来也", "身负血仇")
pop_tip(string.i18_format("(player:fullname)惨遭灭门，{0}！", affix_tip_link("身负血仇", "身负血仇", "#00A5FF")))
player_add_disciple("刘明")
player_add_disciple("朱三娘")

black_scene(0.25)
hide_stage()
set_flag("完成暗度陈仓")
light_scene(0.25)

executefile("Story/开局剧情/6_豪猪长垄偷袭")