show_stage("bg_166.png", "虎焰门大堂")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local qiliuge = actor("齐六哥")
local situ = actor("司徒来也")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(800, -125)
situ:face_right()
qiliuge:setPos(500, 75)
qiliuge:face_right()
liuming:setPos(1100, 75)
liuming:face_left()
zsniang:setPos(1300, 75)
zsniang:face_left()

stage_narration("许久后，(player:fullname)醒来。")
situ:standfront()
wait_twn(situ:offsetY(200), situ:daze())
qiliuge:say("大少爷，门中兄弟们都入土为安了。")
zsniang:say("苏嫣嫣姑娘受了重伤，也送回了得月楼，现在仍在昏迷之中。")
qiliuge:say("得月楼虽是风月之地，却也不乏情义。")
liuming:say("大少爷，掌门与夫人若在天有灵，定会保佑俺们……")
zsniang:say("明哥……别说了……")
situ:say("刘明，朱三娘……")
liuming:say("大少爷？")
zsniang:say("大少爷？")
situ:say("谢了……")
zsniang:flip()
zsniang:movetoX(3000)
wait_twn(liuming:flip(), liuming:movetoX(3000))
situ:emotion("BeiShang")
situ:say("爹……娘……孩儿不孝……")
wait_twn(qiliuge:movetoX(600), qiliuge:daze())
qiliuge:say("大少爷，您得振作起来啊……")
situ:say("六哥……你说是不是因为我，爹娘才会……都怪我！娘还劝我莫要与人纷争，可我……")
situ:shake()
situ:emotion("KuQi")
situ:say("我真不是东西！我不是东西！")
qiliuge:say("大少爷！大少爷！")
situ:say("别拦我！让我随爹娘去了！")
qiliuge:shake_bubble(65, 0.8)
qiliuge:shake(65, 0.8)
qiliuge:emotion("NaoHuo")
qiliuge:say("(player:fullname)！")
situ:flip()
situ:emotion("KuQi")
situ:say("齐、齐六哥？")
qiliuge:say("大少爷寻死觅活，可是掌门与夫人愿意见到的吗？可是死去的门中子弟愿意看到的吗？！")
situ:emotion("BeiShang")
situ:say("我……")
qiliuge:emotion()
qiliuge:say("而今虎焰门正值倾覆之际，危难之间……")
play_bgm("Music/决心_仗剑天涯.wav")
situ:say("……")
situ:jump()
situ:say("没错…… ")
situ:say("在这个时候……")
situ:jump()
situ:say("我怎么能如此懦弱！")
situ:say("六哥你说的对。爹娘的死，灭门的仇，我便是将这息风谷翻遍，也要揪出真凶！")
situ:emotion("NaoHuo")
situ:say("哼，是人也好，是神也罢，毁我虎焰门者，血债……血偿！")
situ:emotion()
qiliuge:say("大少爷、不，掌门！这往后——")
liuming:flip()
liuming:movetoX(1000)
wait_twn(zsniang:flip(), zsniang:movetoX(1200))
situ:flip()
zsniang:say("往后我朱三娘愿誓死效忠掌门！")
liuming:say("俺也一样！")
situ:emotion("HaiXiu")
situ:say("你们？")
situ:emotion()
zsniang:say("我们虽是粗人，但也懂江湖道义。欠债还钱，杀人偿命！这仇，我们不敢忘，也不能忘！")
liuming:say("不错！俺三代人都是火工，幸得老掌门收留，待我不薄还教我武功。如今我怎么能忘恩负义？")
situ:say("说得好！就算只有四人，那也是江湖上“如虎无惧，如焰长燃”的虎焰门！")
qiliuge:say("如虎无惧！如焰长燃！")
liuming:say("如虎无惧！如焰长燃！")
zsniang:say("如虎无惧！如焰长燃！")
situ:say("几位，这虎焰门之仇尚有疑点，想来需得细细查探。可苏姑娘的仇人，却就在眼前！")
situ:say("便从豪猪长垄开始！让这“虎焰复燃”的星星之火到燎原之势。")
hide_all_stage_bubble()
unlock_menpai("豪猪长垄", true)
black_scene(0.25)
remove_camera_filter("CameraFilterPack_Atmosphere_Rain_Pro")
hide_stage()
set_flag("完成立志复仇")
light_scene(0.25)

executefile("Guide/埋葬悲伤_引导")