
show_stage("bg_158.png", "虎焰堂郊外")
play_bgm("Music/舒缓_云淡风轻.wav")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local doctor = actor("老郎中")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-300, 75)
situ:face_right()
qiliuge:setPos(-700, 75)
doctor:setPos(1100, 75)
doctor:face_right()
qiliuge:face_right()

wait_twn(doctor:offsetX(200, 60))
doctor:say("行医悬壶济苍生。")
qiliuge:say_narration("舍己挽救疾病悲。")
doctor:flip()
doctor:say("良药苦方集妙手。")
situ:offsetX(1200)
wait_twn(qiliuge:offsetX(1200), qiliuge:daze())
wait_twn(qiliuge:offsetX(100))
qiliuge:say("医者仁心救人非。")
situ:say("老先生，虎焰门弟子特来拜访，有事相求。望先生能帮助我们，治病救人。")
doctor:say("虎焰门？老夫喜游江湖，自在逍遥，何须加入门派，定居一地？")
qiliuge:say("老先生，我们欲复兴虎焰门，必将有众多弟子战斗受伤，导致<color=red>状态不满</color>，急需先生妙手回春。")
situ:say("先生恩情，我们铭记于心。我门绝不束缚先生自由，愿以金银财宝，或先生所需之物，作为回报。")
doctor:say("金银财宝，非我所求。惟愿能助更多苍生，若贵门能行善积德，老夫愿助一臂之力。")
situ:say("老先生放心，虎焰门誓将行善积德，助危扶困。")
doctor:say("老夫欲救人行医，需购买药材，使用药方制作良药，服之方能回复状态。")
doctor:say("若受伤之人颇多，亦可带往老夫的医馆进行疗养，不过消耗的药材资源将会更多，需贵门提供更多的支持。")
situ:say("老先生，我门愿提供所需<color=red>银两</color>，以支持老先生救死扶伤。")
qiliuge:say("我门若找寻到珍稀药方，也一并交予老先生，以助老先生行医。")
doctor:say("既如此，若贵门能保我自由，提供所需资源与保护，老夫愿为贵门效力。")
doctor:say("老夫这里有一些药材，可以为贵门提供一些药品，以备不时之需。")
situ:say("多谢老先生。")
hide_all_stage_bubble()

add_player_item("金疮药", 3)
add_player_item("猛虎丹", 2)
add_player_item("灵龟丹", 2)
add_player_item("升龙丹", 2)
add_player_item("苍狼丹", 2)
black_scene(0.25)
hide_stage()
set_flag("已解锁药店")

restore_api.add_fire_point(5)
light_scene(0.25)

avg_talk("齐六哥","掌门，我们现在可以通过<color=yellow>[购买药品]</color>治疗受伤之人了。")
