show_stage("龙湾门大堂.png", "龙湾门大堂")
light_scene(0.2)
play_bgm("Music/回忆.wav")

local dongfangzhouyu = actor("东方骤雨")
local longwanying = actor("龙万莹")
local dongfangsha = actor("东方鲨")
local dongfangtun = actor("东方豚")
local dongfangli = actor("东方狸")
local laosong = actor("老宋")

--初始化位置和朝向
dark_all_actors()
dongfangzhouyu:setPos(1300, 75)
dongfangzhouyu:face_right()
longwanying:setPos(1100, 75)
longwanying:face_right()
dongfangsha:setPos(800, 75)
dongfangsha:face_right()
dongfangtun:setPos(500, 75)
dongfangtun:face_right()
dongfangli:setPos(200, 75)
dongfangli:face_right()
laosong:setPos(2600, 75)
laosong:face_left()

wait_twn(laosong:movetoX(1600), laosong:daze())

laosong:say("不好了！大事不好了！虎焰门已经攻陷了海狸湾！")
dongfangsha:say("什么大惊小怪的，没大没小的。")
longwanying:say("鲨儿，住口。老宋，你辛苦了，先下去休息吧。")
laosong:say("遵命，夫人。")
hide_all_stage_bubble()
laosong:flip()
wait_twn(laosong:movetoX(3000))
longwanying:say("夫君，虎焰门来势汹汹，这三个孩子的实力恐怕抵挡不住。")
dongfangzhouyu:flip()
dongfangzhouyu:say("哼！三个没用的东西！为夫亲自出马，让虎焰门知道，海狸湾不是他们可以撒野的地方。")
longwanying:say("夫君英勇，妾身自然放心。但此去凶险，不如让豚儿和狸儿随你一同前往，也好有个照应。")
dongfangtun:say("父亲，孩儿愿往！")
dongfangli:say("我也愿随父亲一战！")
dongfangsha:say("娘，那我呢？")
longwanying:flip()
longwanying:say("鲨儿和我留守龙湾，以待夫君凯旋。")
longwanying:flip()
dongfangzhouyu:say("就依夫人所言，豚儿和狸儿随我前去，鲨儿和夫人留守龙湾。")

hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成海狸湾失陷")
light_scene(0.25)
