show_stage("仙竹门.png", "仙竹门")
play_bgm("Music/山雨欲来风满楼.wav")
light_scene(0.2)

local situ = actor("司徒来也")
local nangongyan = actor("南宫燕")
local duanxiaonian = actor("段小年")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-500, 75)
situ:face_right()
nangongyan:setPos(1100, 75)
nangongyan:face_left()
duanxiaonian:stylize("Silhouette")
duanxiaonian:setPos(2500, 75)
duanxiaonian:face_left()

duanxiaonian:movetoX(1300)


wait_twn(situ:movetoX(400), situ:daze())
situ:say("姨母！小心身后——")
hide_all_stage_bubble()

play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
nangongyan:flip()
nangongyan:spring_scale(1.5, 1, 1, 0.2)
wait_twn(nangongyan:movetoX(1400, 4000), duanxiaonian:jumpTo(1800, 600), duanxiaonian:movetoY(2500, 5000))
nangongyan:flip()
nangongyan:movetoX(1200, 4000)
nangongyan:offsetY(-80)
wait_twn(situ:movetoX(900), situ:daze())
situ:say("姨母！这伤……怎会如此严重？！莫非是黑血魔骨所伤？解药在哪儿，我去寻！")
nangongyan:say("来……来不及了，毒已入骨，不可能有救了……")
situ:say("怎……怎会如此？")
nangongyan:say("这或许就是报应，当年我害了至亲挚爱，现在便都是报应！")
situ:say("报应？什、什么意思？")
nangongyan:say("也罢，如今是你来找我，恐怕这就是天意啊。")
nangongyan:say("有一件事情，我一直想找个合适的机会跟你坦白，如今再不说…就没有机会了。你、你可听好……")
situ:say("好……我听着……")
nangongyan:say("十九年前……也就是南宫紫怀着你的时候，我因妒忌被你父亲选择结婚生子的妹妹……送了一碗凌花汤给她。")
situ:say("凌花汤？")
nangongyan:say("那是导致产妇堕胎的毒药，我骗南宫紫说是补身子的。那个傻丫头，居然真的喝了下去。")
situ:say("什……什么？")
nangongyan:say("我那时年轻气盛，就是……不想司徒雷同别人有孩子……更何况还是自己的妹妹……实在是……对不起！")
situ:say("罢了罢了……姨母莫要激动，当心剧毒攻心……")
situ:say("老祖师父，弟子若是能避免[流血]，是否就能破解他们的阵法？")
nangongyan:say("但让我百思不得其解的是，本不能降世的你……却如常人一般的活了下来。")
situ:say("这……对呀，我不也活生生站在这里吗？")
nangongyan:say("那日妹妹明明喝下毒药，这个事情，我想了许久，觉得只有两种可能。")
nangongyan:say("第一种可能就是，你司徒来也天生就百毒不侵的种。")
situ:say("我，百毒不侵？可是…")
nangongyan:say("这种猜想如今已经可以推翻了，先前你对黑水仙的反应，证明你并不能够抵抗毒性。")
situ:say("那…您说的第二种可能又是什么？")
nangongyan:say("(player:gname)……你靠近点，再让我仔细看看你的脸。")
wait_twn(situ:movetoX(1000), situ:daze())
situ:say("怎……怎么了？")
nangongyan:say("果然……是第二种……")
situ:say("姨母？")
nangongyan:say("妹妹，这一世姐姐对不住你，这便……去给你赔罪了……")
nangongyan:movetoY(-600, 5000)
kill_disciple("南宫燕")
situ:say("姨母？姨母！")

hide_all_stage_bubble()

set_menpai_leader("仙竹门", "绿袍尼")

black_scene(0.25)
hide_stage()
set_flag("完成南宫燕被刺杀")
light_scene(0.25)
