
show_stage("仙竹门.png", "仙竹门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local nangongyan = actor("南宫燕")
local lvpaoni = actor("绿袍尼")
local shaoyao = actor("芍药")

--初始化位置和朝向
bright_all_actors()

nangongyan:setPos(900, 75)
nangongyan:face_right()
lvpaoni:setPos(600, 75)
lvpaoni:face_right()
shaoyao:setPos(2500, 75)
shaoyao:face_left()

wait_twn(shaoyao:movetoX(1200), shaoyao:daze())
shaoyao:say("门主！门主！不好了！")
nangongyan:say("什么事儿这么慌张？")
shaoyao:say("蜘蛛洞的玄铁门腐化了！段小年逃跑了！！")
nangongyan:say("玄铁门怎么可能被腐化？！")
nangongyan:say("千真万确。")
nangongyan:flip()
lvpaoni:say("据属下所知，再坚硬的利器也无法破坏那玄铁门，除非……")
nangongyan:say("除非什么？")
lvpaoni:say("只有黑血魔骨的力量才能腐蚀玄铁门……")
nangongyan:say("你的意思是……段小年习得了黑血魔骨？！")
shaoyao:say("她怎会有如此大的本事？！")
lvpaoni:say("这黑血魔骨修炼条件苛刻，关窍极多，极其不易，她怎会在这么短的时间内……")
nangongyan:say("我何尝不知？修炼黑血魔骨既要黑水仙提升功法，更关键的是需要姑获鸟之瓶祛除体内毒素……莫非……")
lvpaoni:say("门主的意思是，姑获鸟之瓶仍在她手，可是当日——")
nangongyan:say("当日确实没有从她身上搜出来！只怕是她诡计多端，用了些手段连我都瞒了过去。")
lvpaoni:say("而且蜘蛛洞内有生长了不少黑水仙。")
nangongyan:say("但是没有鲜血，姑获鸟之瓶也无法发挥作用……")
lvpaoni:say("处子……处子之血……尚可。")
nangongyan:say("居然真的让这个小贱人练成了神功！")
shaoyao:say("那岂不是要让段小年称霸武林了？")
lvpaoni:say("她……难不成会回来报仇？")
nangongyan:flip()
nangongyan:say("闭嘴！")

hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成小年失踪")
set_flag_int("小年失踪回合数", get_game_round())
light_scene(0.25)
