
show_stage("bg_219.png", "虎焰堂")
play_bgm("Music/阴冷_段小年.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local duanxiaonian = actor("段小年")
local liuming = actor("刘明")

--初始化位置和朝向
bright_all_actors()

situ:setPos(800, 75)
situ:face_right()
qiliuge:setPos(500, 75)
qiliuge:face_right()
liuming:setPos(2200, 75)
liuming:face_left()
duanxiaonian:setOverrideName("？？？")
duanxiaonian:setPos(2400, 130)
duanxiaonian:face_left()

liuming:movetoX(1000)
wait_twn(duanxiaonian:movetoX(1200), duanxiaonian:daze())
liuming:say("掌门，我和朱三娘在虎苇地丛林深处的小溪边发现了一位负伤昏迷的姑娘，我们便将她救了回来。")
qiliuge:say("你们跑到那么偏僻的地方去干什么？")
situ:flip()
situ:say("别问了，先看看受伤姑娘的情况。")
situ:flip()
wait_twn(duanxiaonian:jumpTo(1300, 75), duanxiaonian:daze())
wait_twn(liuming:movetoX(200), liuming:flip())
duanxiaonian:say("(player:fname)……(player:fname)掌门……")
qiliuge:say("这不是仙竹门追杀的那位姑娘吗？")
situ:say("对，姑娘，她们为何要不顾一切地追杀你呢？")
duanxiaonian:say("是因为……因为这个……")
situ:say("这是何物？")
duanxiaonian:say("这个瓶子是南洋的邪物，(player:fname)掌门你……你一定要……救我。")
situ:say("姑娘别急，慢慢说。")
duanxiaonian:say("南宫燕掌门为了……为了提升自己的毒术……她……用这个姑获鸟之瓶来炼制丹药。")
qiliuge:say("南宫燕的毒术已经独步息风谷了，还要提升吗？")
duanxiaonian:say("她想达到黑血魔骨的境界。")
situ:say("黑血磨骨，那是个什么境界？")
duanxiaonian:say("达到了黑血魔骨境界，触碰到的任何生灵都会被毒死，功力也会急剧大增，连百里烟波都将不是她的对手。")
situ:say("非要变得那么强吗？")
duanxiaonian:say("关键是南宫燕用来炼丹药的必须是……是……新生婴儿的胎血。")
situ:say("什么？！")
duanxiaonian:say("所以，南宫燕对周围村里许多孕妇下了……下了毒手。")
liuming:say("这个臭娘们也太残忍了吧！！")
duanxiaonian:say("有一部分门徒私下议论纷纷，但又不敢阻止。")
liuming:say("让俺去灭了她！")
duanxiaonian:say("我不忍看到村里的婴儿和孕妇一个个被害，原本……原本是准备偷偷把这姑获鸟之瓶找个地方藏起来，好让南宫燕断了这个念头。")
situ:say("对，没有这个邪恶的瓶子，南宫燕就不会去残害婴儿了。")
duanxiaonian:say("没想到，被芍药师姐发现了……于是一路追杀我到了这。")
qiliuge:say("原来是这样啊。")
situ:say("敢问姑娘芳名？")
duanxiaonian:setOverrideName("段小年")
duanxiaonian:say("我叫段小年……")
situ:say("小年姑娘，你就暂且留在我们虎焰门避险吧。")
qiliuge:say("掌门？")
situ:say("南宫燕，是我的姨母，但我们家族早已和她断了亲戚关系，就连爹娘被害，她也没有出现。")
situ:say("听母亲说过她是一个非常狠的女人，但我没想到她狠毒到草菅人命这种地步。")
duanxiaonian:say("小女子谢过(player:fname)掌门大恩，这个瓶子，必须交给掌门。")
situ:say("好，这瓶子可能事关众多婴孩性命，就让我来替你保管，南宫燕想要拿回的话，先要问问我(player:fullname)！")
hide_all_stage_bubble()
player_add_disciple("段小年")

black_scene(0.25)
hide_stage()
set_flag("完成小年投报")
light_scene(0.25)
