show_stage("夜晚豪猪长垄.png", "芭蕉洞")
play_bgm("Music/阴冷_段小年.wav")
light_scene(0.2)

local nangongyan = actor("南宫燕")
local alasuo = actor("阿拉索")
local duanxiaonian = actor("段小年")

--初始化位置和朝向
bright_all_actors()

nangongyan:setPos(700, 75)
nangongyan:face_right()
alasuo:setPos(1000, 75)
alasuo:face_right()
duanxiaonian:setPos(1300, 75)
duanxiaonian:face_left()

nangongyan:say("可是搜仔细了？")
alasuo:flip()
alasuo:say("回主人，她的身上确实没有姑获鸟之瓶。")
nangongyan:say("没有？想不到你还挺会藏！说！东西到底在哪里！")
alasuo:flip()
duanxiaonian:say("哼，那瓶子的下落，我是绝对不会说的！")
nangongyan:say("段小年！最好还是乖乖把东西交出来，兴许看在你识趣的份上，还能放你一马。")
duanxiaonian:say("怎么？你那么看重瓶子，若是给了你，你会放过我？真以为我会相信你的鬼话？")
nangongyan:say("呸！信不信我现在就让你喂这满洞的蜘蛛！")
duanxiaonian:say("哼，这东西对你这么重要，你当真敢动手？毕竟，若我死了，姑获鸟之瓶的下落可就再没人知道了。")
nangongyan:say("打！给我狠狠打！打到她交代为止！")
alasuo:say("是！主人！")
hide_all_stage_bubble()
play_sfx("Story/Slash.mp3")
wait_twn(alasuo:offsetX(100), alasuo:offsetX(-100), alasuo:shake(), alasuo:shake())
play_sfx("Story/Slash.mp3")
wait_twn(duanxiaonian:shake(), duanxiaonian:shake(), duanxiaonian:shake(), duanxiaonian:shake())
duanxiaonian:say("哼……咳咳，这点手段……根本不值一提！南宫燕，你是不可能赢过我的！")
nangongyan:say("当真是不知死活！我倒要看看是你的嘴硬还是你的命硬！来人！给我看紧洞口！我要让这孽徒困死在这蜘蛛洞中，求生不得，求死不能！")
nangongyan:say("还有！加紧去找寻姑获鸟之瓶！就是把她所经的地方都翻个遍，也要把东西给我找出来！")
alasuo:say("是！主人！")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成捉回叛徒")
light_scene(0.25)
