
show_stage("仙竹门.png", "仙竹门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local nangongyan = actor("南宫燕")
local shaoyao = actor("芍药")
local alasuo = actor("阿拉索")

--初始化位置和朝向
bright_all_actors()

nangongyan:setPos(800, 75)
nangongyan:face_right()
shaoyao:setPos(1300, 75)
shaoyao:face_left()
alasuo:setPos(2500, 75)
alasuo:face_left()

nangongyan:say("没用的东西！一个段小年都抓不回！")
shaoyao:say("掌门饶命，我本已经追上了逆贼段小年，都怪那(player:fullname)半路杀出来捣乱，才……")
nangongyan:say("(player:fullname)，又是(player:fullname)，二十年前，他就应该死的！")
shaoyao:say("掌门，接到消息，段小年带着姑获鸟之瓶已经……")
nangongyan:say("已经什么？！")
shaoyao:say("已经投奔了虎焰门……")
nangongyan:say("好你个(player:fullname)。")
nangongyan:say("阿拉索！")
wait_twn(alasuo:movetoX(1000), alasuo:daze())
alasuo:say("在，主人。")
nangongyan:say("把这个没用的芍药，关进芭蕉洞里去喂蜘蛛。")
alasuo:flip()
wait_twn(alasuo:movetoX(1400), alasuo:offsetY(-60), alasuo:offsetY(60, 300))
shaoyao:flip()
wait_twn(shaoyao:jumpTo(1200, 130))
shaoyao:say("不要啊！掌门饶命啊！那里面都是剧毒蜘蛛！掌门！不要！")
nangongyan:say("阿拉索，你去虎焰门，带的人由你挑，帮我带两样东西回来。")
nangongyan:say("一个是姑获鸟之瓶，一个是(player:fullname)的人头。")
alasuo:say("是！")
hide_all_stage_bubble()

alasuo:movetoX(2500)
wait_twn(shaoyao:movetoX(2500))

local diplomatic = require("Common/diplomatic")
diplomatic.declare_war("仙竹门", "player")

black_scene(0.25)
hide_stage()
set_flag("完成毒女之怒")
light_scene(0.25)
