
show_stage("仙竹门.png", "仙竹门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local nangongyan = actor("南宫燕")
local mudan = actor("牡丹")
local dizi = actor("仙竹门玉竹侍")

--初始化位置和朝向
bright_all_actors()

nangongyan:setPos(-500, 75)
nangongyan:face_right()
mudan:setPos(800, 75)
mudan:face_left()
dizi:setPos(1100, 75)
dizi:face_left()

dizi:say("师姐，这里的竹子真多真漂亮啊，有如人间仙境一般。")
mudan:say("所以咱们的门派叫仙竹门啊。不过，别光顾着看风景，赶紧练功，别让掌门发现了，否则有你受的。")
dizi:say("嗯嗯……这竹子上的紫褐色斑点可真奇怪。")
mudan:say("你肯定不会知道这色斑是怎么来的吧。")
dizi:say("我听说过呢，传说很久以前，有一位仙子在这竹林里哭了一整夜，泪水把整片竹林都染上了斑色。")
mudan:say("你可知道这传说中的仙子是谁吗？")
dizi:say("这个，师妹还真不清楚。")
mudan:say("偷偷告诉你一个秘密，这个仙子啊，其实就是咱们的掌门大人。")
dizi:say("啊！是南宫燕掌门吗，她年轻时一定是个大美人吧，可掌门大人这么刚强的一个人，为何会在这流泪一整夜呢。")
mudan:say("这你就不知道了吧，南宫燕掌门年轻的时候深深地爱过一个男人。")
dizi:say("嘻嘻~原来掌门也喜欢过男人呀。")
mudan:say("他就是虎焰门的前任掌门(player:fname)雷。")
dizi:say("(player:fname)雷！")
mudan:say("是的，但是听说这个(player:fname)雷是个负心郎，他移情别恋爱上了掌门的妹妹南宫紫，而且……还和南宫紫成了婚。")
dizi:say("怪不得——")
mudan:say("就在(player:fname)雷和南宫紫成婚的那天，咱们的掌门南宫燕在这里哭了一整夜，泪水洗遍了整片竹林，所有的竹子上都染上了紫褐色的斑点。")
dizi:say("多么凄美的爱情故事啊~")
mudan:say("后来南宫燕掌门与妹妹南宫紫断绝了关系，自己创立了仙竹门，也从此和虎焰门势不两立。")
dizi:say("原来是这样啊。")
mudan:say("对啊，南宫掌门不想让人知道这段往事，所以就编造了泪雨斑竹这个传说。")
mudan:say("知道这件事的人没有几个，你可千万别到处乱讲啊。")
dizi:say("好的，一定不敢乱讲。")
hide_all_stage_bubble()
wait_twn(nangongyan:movetoX(500), nangongyan:daze())
nangongyan:say("我倒看看是哪位好弟子在这里飞短流长、搬弄是非！")
dizi:offsetY(-80)
mudan:flip()
wait_twn(mudan:offsetY(-80), mudan:daze())
mudan:say("掌门，弟子该死！")
nangongyan:jumpTo(800, 75)
wait_twn(mudan:jumpTo(900, 30), mudan:daze())
nangongyan:say("原来是我的爱徒牡丹啊——（她掐住牡丹的脸）")
mudan:say("掌门，我不敢了……不敢了……")
nangongyan:say("小牡丹，你这小嘴儿，红润如牡丹花瓣，可惜就是话太多了些！")
mudan:shake()
mudan:say("啊！啊！啊——（惨叫声响彻整片竹林）")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成泪雨斑竹")
light_scene(0.25)
