show_stage("龙湾门大堂.png", "龙湾门大堂")
set_bg_mat("ImgPaperFold")
play_bgm("Music/密谋_夜郎.wav")
light_scene(0.2)

local dongfangzhouyu = actor("东方骤雨")
local longwanying = actor("龙万莹")
local dongfangsha = actor("东方鲨")
local dongfangtun = actor("东方豚")
local dongfangli = actor("东方狸")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
dongfangzhouyu:setPos(400, 75)
dongfangzhouyu:face_right()
longwanying:setPos(700, 75)
longwanying:face_left()
dongfangsha:setPos(2200, 75)
dongfangsha:face_left()
dongfangtun:setPos(2400, 75)
dongfangtun:face_left()
dongfangli:setPos(2600, 75)
dongfangli:face_left()

longwanying:say("夫君，那虎焰门都已经是残兵败将成不了气候，如何还要夫君费心谋划？")
dongfangzhouyu:say("那虎焰门虽然已经败落，但到底还有些能耐，自然大意不得。")
longwanying:say("哎呀，有三个孩子在，夫君有什么好担心的？")
dongfangzhouyu:say("唉！和虎焰门斗了这么些年，谁想竟是这么个结果。")
longwanying:say("虎焰门的前掌门孤高自诩，现在自然是失道寡助，夫君又何必作“司马牛之叹”呢？")
dongfangzhouyu:say("夫人有所不知——")
longwanying:say("夫君？")
dongfangzhouyu:say("罢了罢了，这清扫虎焰门残余的事情，打打杀杀的，还是免得惊吓到夫人。")
longwanying:say("夫君若不愿说便罢了，幸而妾身这三个孩儿可不像虎焰门的那位，应当能替夫君担当些。")
dongfangsha:movetoX(1000)
wait_twn(dongfangtun:movetoX(1300), dongfangtun:daze(), longwanying:flip())
dongfangtun:say("父亲！孩儿愿意出战清理虎焰门残余，为爹娘分忧！")
dongfangzhouyu:say("好！不愧是我东方骤雨的儿子！")
dongfangsha:flip()
dongfangsha:say("二弟，你不过是因你那佳人另有倾心故而妒忌那小子，争风吃醋的私人恩怨却说是为爹娘分忧，这不好吧？")
dongfangtun:say("什么私人恩怨？别乱说！我、我只是一心只想为龙湾门铲除死敌！")
dongfangsha:flip()
dongfangsha:say("爹，这一战还是我去吧，让孩儿为咱们龙湾门吃掉这块难啃的骨头！")
dongfangzhouyu:say("也好。")
dongfangtun:say("爹！不必大哥，我去便是！")
dongfangsha:say("爹，我是家中长子，于情于理，还是让孩儿出战最为稳妥！")
stage_narration("角落的柱子旁传来一声轻蔑的哼声，一名冷俊的长发年轻男子站在那里，是东方骤雨的三儿子")
wait_twn(dongfangli:movetoX(1700), dongfangli:daze())
dongfangli:say("哼！")
wait_twn(dongfangsha:flip(), dongfangtun:flip())
dongfangtun:say("三弟，你什么时候来的？")
dongfangli:say("原本不想来的，可想着家中实在无人可用，这才来看看。")
dongfangsha:say("老三，平时不见人也就罢了，如今正是为家里效力的时候，你阴阳怪气算什么意思？")
dongfangli:say("那三弟倒是想请教大哥，当初虎焰门那老掌门还活着的时候，怎未见大哥如此骁勇？")
dongfangsha:say("你——")
dongfangli:say("如今眼见有这能欺弱立威的便宜，便都争先恐后，可真是难看啊。")
dongfangsha:say("老三你别太过分！")
dongfangtun:flip()
dongfangtun:say("大哥你消消气，三弟你也是，怎么跟大哥说话呢？")
dongfangli:say("呦，有这拉偏架的口才，怎么就哄不了西门家的一个娘们儿呢？")
dongfangtun:flip()
dongfangtun:say("你这话什么意思！")
dongfangzhouyu:say("够了！")
dongfangsha:flip()
dongfangtun:flip()
dongfangsha:say("……")
dongfangtun:say("……")
dongfangli:say("……")
dongfangzhouyu:say("如今江湖动荡，我们东方家没准就变成下一个虎焰门！你们还在这里争一时长短！")
dongfangsha:say("孩儿只是心念龙湾门的将来，故而一时失了分寸。")
dongfangtun:say("是啊是啊，我们也是心中一时着急……")
dongfangli:say("……")
dongfangzhouyu:say("罢了罢了，但愿你们能明白“兄弟阋墙，外御其侮”！")
dongfangsha:say("父亲的话，孩儿一定谨记！")
dongfangzhouyu:say("虎焰门被灭实在蹊跷，其中内情一时虽未参透，可前车之鉴，不得不防啊。")
dongfangli:say("所以父亲此时借着清理残余，是想以攻为守，抢占先机？")
dongfangzhouyu:say("老三到底心思细些，为父正是在为此事踌躇。")
dongfangtun:say("那要如何对付虎焰门那边？")
dongfangzhouyu:say("这件事，我自有道理。")

hide_all_stage_bubble()
set_flag("完成东方狸登场")
hide_stage()
light_scene(0.25)
