show_stage("龙湾门大堂.png", "龙湾门大堂")
set_bg_mat("ImgPaperFold")
play_bgm("Music/密谋_夜郎.wav")
light_scene(0.2)

local dongfangsha = actor("东方鲨")
local dongfangtun = actor("东方豚")
local xiaren = actor("龙湾门下人")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
dongfangsha:setPos(700, 75)
dongfangsha:face_right()
xiaren:setPos(1700, 75)
xiaren:face_left()
dongfangtun:setPos(2400, 75)
dongfangtun:face_left()

dongfangsha:say("今天的蛤蜊是谁烤的？")
wait_twn(xiaren:movetoX(1200), xiaren:offsetY(-50), xiaren:daze())
xiaren:say("报告大少爷，是新来的厨子老宋。")
xiaren:offsetY(50)
dongfangsha:shake()
dongfangsha:say("给我去狠打他一顿，没断根指头别停下来！")
xiaren:say("这…")
dongfangsha:say("愣着干嘛？快去给我打！")
xiaren:offsetY(-50)
xiaren:say("遵命。")
hide_all_stage_bubble()
xiaren:offsetY(50)
wait_twn(xiaren:flip(), xiaren:movetoX(3000))
stage_narration("厨房里传来一阵呜呜啊啊的救命声…")
dongfangsha:say("烤海鲜居然放了两颗盐，这不是皮痒吗，这无知的做法肮脏了我的味蕾，真是坏了一天的大好心情。")
wait_twn(dongfangtun:movetoX(1100), dongfangtun:daze())
dongfangtun:say("大哥，新来的厨子是犯了什么事儿了，在院子里被打得直嚎？")
dongfangsha:say("烤蛤蜊居然放细盐，你说这不是皮痒吗？")
dongfangtun:say("哎呀，什么粗盐细盐的，有分别吗？")
dongfangsha:say("你懂个屁！连个粗盐细盐都吃不出来，你那脑袋上镶的是个窟窿吗？")
dongfangtun:say("在吃这方面，小弟确实甘拜下风……可人活着也不全为吃吧？那不成饭桶了？")
dongfangsha:say("呦，还会跟你大哥顶嘴了？心情不好？是鹤岭门那大小姐的事儿吧？")
dongfangtun:say("哥，你咋知道的？")
dongfangsha:say("咋知道的？一提女人，看你那没出息的样子！")
dongfangtun:say("是没出息，可我就是稀罕她啊，为啥她偏偏跟虎焰门那小子定亲了呢？")
dongfangsha:say("你也别丧气！哥这儿有件喜事儿，你听不听？")
dongfangtun:say("什么喜事儿？")
dongfangsha:say("虎焰门被灭了，这亲事，我看八成是黄了。")
dongfangtun:say("哎呦！还有这事儿！来人！快上些好酒好菜！哥，可得仔细跟弟弟说说！")
hide_all_stage_bubble()
unlock_menpai("龙湾门", true)

black_scene(0.25)
hide_stage()
set_flag("完成烤海鲜")
light_scene(0.25)
