show_stage("龙湾门大堂.png", "龙湾门大堂")
set_bg_mat("ImgPaperFold")
play_bgm("Music/密谋_夜郎.wav")
light_scene(0.2)

local dongfangzhouyu = actor("东方骤雨")
local longwanying = actor("龙万莹")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
dongfangzhouyu:setPos(700, 75)
dongfangzhouyu:face_right()
longwanying:setPos(1100, 75)
longwanying:face_left()

longwanying:say("夫君，我们与虎焰门的争斗如此激烈，这龙虎二门间的仇恨，究竟从何而来呢？")
dongfangzhouyu:say("这些年来，与虎焰门的争斗已成为习惯，那仇恨似乎已融入我们的血液。若不是你提起，我几乎忘记了它的起源。")
longwanying:say("总该有个起因吧？")
dongfangzhouyu:say("那是二十年前的事了。")
longwanying:say("这么久了呀。")
dongfangzhouyu:say("我和(player:fname)雷原本是师兄弟。")
longwanying:say("这个我好像听说过。")
dongfangzhouyu:say("我们共同的师父，是隐居在狴犴观的章仙人。")
longwanying:say("章仙人……听起来就像是个神仙。")
dongfangzhouyu:say("章仙人一生低调，从未立门建派，但我们自幼便跟随他学武，对他充满敬意。")
dongfangzhouyu:say("即使我们各自成为掌门后，仍每日前往狴犴观向他请教。")
longwanying:say("原来夫君的一身武艺，都是得自仙人的真传。")
dongfangzhouyu:say("后来章仙人年事已高，我们便轮流去探望他。但有一天，我看到的却是师父倒在血泊中的尸体。")
longwanying:say("师父他……")
dongfangzhouyu:say("据我推断，师父是前夜遇害的。而前一天，只有(player:fname)雷去过狴犴观。")
longwanying:say("(player:fname)雷他……谋害了章仙人？")
dongfangzhouyu:say("他对此事竟然毫无痛惜之意，除了他，还能有谁！")
longwanying:say("那(player:fname)雷为何要杀害自己的师父呢？")
dongfangzhouyu:say("师父曾留下一本名为《狴犴经》的内功心法，(player:fname)雷为了得到它，竟不惜杀害师父。")
longwanying:say("没想到(player:fname)雷是这样的人。")
dongfangzhouyu:say("我誓要为师父报仇，但(player:fname)雷得到《狴犴经》后，功力大增，虎焰门也日益壮大。")
longwanying:say("那你岂不是很吃亏？")
dongfangzhouyu:say("我的武功本就略胜一筹，这些年来，我精心经营龙湾门，只待时机成熟，一举灭掉虎焰门。")
longwanying:say("这一斗就是二十年啊。")
dongfangzhouyu:say("(player:fname)雷作恶多端，上天也不会眷顾他。他只有一个儿子，而我却有三位贤子，龙湾门的实力已逐渐超过虎焰门。")
longwanying:say("这么说来，这都是我的功劳呀。")
dongfangzhouyu:say("夫人说得对，感谢你给我带来了三位优秀的儿子。")
dongfangzhouyu:say("但没想到夜鸦先动手了，没能让我亲手杀了(player:fname)雷。")
dongfangzhouyu:say("不过，他的儿子(player:fullname)，我也绝不会放过。谁能消灭虎焰门的最后一丝火苗，我必有重赏。")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成龙虎恩怨")
light_scene(0.25)
