show_stage("火神树林.png", "火神树林")
play_bgm("Music/少女鹿追.wav")
light_scene(0.2)

local qiliuge = actor("齐六哥")
local situ = actor("司徒来也")
local luzhui = actor("鹿追")

--初始化位置和朝向
dark_all_actors()
situ:bright()
situ:setPos(-300, 75)
situ:face_right()
qiliuge:setPos(-600, 75)
qiliuge:face_right()
luzhui:setOverrideName("？？？")
luzhui:face_right()
luzhui:setPos(1400, 2000)

situ:offsetX(800)
wait_twn(qiliuge:offsetX(800), qiliuge:daze())
situ:say("每当我心绪不宁，来到此处，总能寻得一丝宁静。")
qiliuge:say("火神之树，正如此刻，随风摇曳，“沙沙”作响，总能令人心旷神怡。")
situ:offsetY(50)
situ:emotion("KunHuo")
situ:say("咦，树上似乎有人？")
qiliuge:offsetY(50)
stage_narration("只见火神之树上，一个娇小的橙衣少女，正攀爬在枝头，手握红叶，脚下树枝却摇摇欲坠……")
hide_all_stage_bubble()
situ:offsetY(-50)
qiliuge:offsetY(-50)

local careful_options = {"试着提醒少女", "静观其变"}
local care_idx = show_quick_selections(careful_options)
if care_idx == 1 then
    situ:emotion("JingYa")
    situ:say("姑娘, 当心脚下！")
    --鹿追轻功下树
    luzhui:say_narration("哎呀……哎呀呀！")
    wait_twn(luzhui:flip(), luzhui:jumpTo(1000, 600, 50, 3000), luzhui:flip() , luzhui:jumpTo(1400, 400, 50, 3000), luzhui:flip(), luzhui:jumpTo(1000, 200, 50, 3000), luzhui:flip(), luzhui:jumpTo(1400, 75, 50, 3000))
    luzhui:say("呼……好险。")
    luzhui:flip()
    qiliuge:say("姑娘，好身手！")
    wait_twn(situ:flip())
    situ:emotion("YaoYa")
    wait_twn(qiliuge:shake(), qiliuge:daze(), situ:flip())
    wait_twn(situ:offsetX(600))
    situ:emotion("WeiSuo")
    situ:say("姑娘，没事吧?")
    luzhui:say("多谢刚刚公子出言提醒，我没事啦。")
    situ:say("不必客气，姑娘无恙便好。只是这树如此之高，姑娘为何要冒险而上？")
    luzhui:say("唔……若是假借他人之手，便是我的心不诚了！")
    situ:say("什么诚不诚的……莫非，你也信奉火神之树？")
    luzhui:say("哎，你知道<color=red>火神之树</color>，难道你也供奉火神大人吗？")
    situ:say("这……也算是吧。可这跟你爬那么高又有什么关系呀？")
    luzhui:say("我、我只是想摘那片最红的叶子，这不？就这片！还好摔下来之前摘到了！")
    situ:emotion("KunHuo")
    situ:say("这叶子难道有什么讲究吗？")
else
    luzhui:say_narration("哎呀呀！")
    luzhui:flip()
    situ:emotion("JingYa")
    situ:say("喂，小心呀！")
    --少女从树上坠下，(player:fullname)大步流星冲了上去，双手接住少女的腰部和腿，并第一时间瞅向少女的脸。还算得上好看）
    situ:jumpTo(1300, 500, 50, 3000)
    wait_twn(luzhui:moveTo(1400, 600, 3000))
    luzhui:offsetY(-425)
    wait_twn(situ:offsetY(-425))
    luzhui:say("啊…(>_<)")
    situ:emotion("WeiXiao")
    situ:say("姑娘，没事吧？")
    luzhui:say("多谢公子，这树枝看着粗实，竟如此脆弱。")
    situ:say("姑娘无恙便好。只是这树如此之高，姑娘独自攀爬，可是有何要事？")
    luzhui:say("唔……若是假借他人之手，便是我的心不诚了！")
    situ:say("什么诚不诚的……莫非，你也信奉火神之树？")
    luzhui:say("哎，你知道<color=red>火神之树</color>，难道你也供奉火神大人吗？")
    situ:say("这……也算是吧。可这跟你爬那么高又有什么关系呀？")
    luzhui:say("我……我只是想摘那片最红的叶子，这不？就这片！还好摔下来之前摘到了！")
    situ:emotion("DaXiao")
    situ:say("哈哈哈哈，叶子有什么好摘的，真不懂你们这些少女。")
    situ:emotion("WeiSuo")
    luzhui:say("对了公子，你就这么一直抱着我聊吗？怪不好意思的。")
    hide_all_stage_bubble()
    local lust_options = {"小手不是很老实, 再感受下少女的曲线", "放下少女"}
    local lust_idx = show_quick_selections(lust_options)
    if lust_idx == 1 then
        change_favor_by_id("司徒来也", 1)
        luzhui:say("（梨花带雨）公子……")
    end
    situ:emotion("WeiXiao")
    situ:say("哦……也是……只是觉得，很顺手，抱歉姑娘。")
    wait_twn(luzhui:offsetY(-100))
    luzhui:offsetX(100)
    wait_twn(situ:offsetX(-150), situ:daze())
    situ:say("这叶子难道有什么讲究吗？")
end
luzhui:say("那片最红的叶子叫做岁炙叶。每年秋天都要由家族中选出负责侍奉火神大人的侍奉人亲自摘下来呢！到我这一代，可是已经收集了两百多片岁炙叶了。")
situ:emotion("KunHuo")
situ:say("原来姑娘便是那位侍奉人，真是了不得。")
luzhui:say("那当然，我可是家中最年轻的侍奉人呢！")
situ:say("听起来很厉害呀。")
luzhui:say("那当然！选拔的考核可是很严格的哦！再怎么说也是世代生长在火神树下的炙家族，侍奉火神大人这种事情，不认真对待怎么行？")
wait_twn(qiliuge:offsetX(700), qiliuge:daze())
qiliuge:say("掌门，炙家族是火神之树的原生族，世代生长在火神树下。")
situ:emotion("WeiXiao")
situ:say("这么说来，我们家也是世代生长在火神树下的……")
luzhui:say("公子似乎对火神之事颇为熟悉，不知公子是何门何派？")
situ:say("在下(player:fullname)，虎焰门现任掌门。")
wait_twn(luzhui:jump())
luzhui:say("啊，怪不得……")
situ:emotion("KunHuo")
situ:say("怪不得什么？")
luzhui:say("没……没什么。")
luzhui:say("今日多谢公子，没有什么事情的话，小女子就先行离开了。")
situ:emotion("HaiXiu")
situ:say("哎！姑娘！你还没有告诉我你的名字呢！")
luzhui:setOverrideName("鹿追")
luzhui:say("小女子叫<color=red>鹿追</color>！公子可记住了。")
hide_all_stage_bubble()
wait_twn(luzhui:flip(), luzhui:movetoX(3000, 1000))
situ:say("喂，怎么这么快就跑了？")
qiliuge:say("看来掌门你的“威名”如雷贯耳，吓着人小姑娘了。")
wait_twn(situ:flip())
situ:emotion("NaoHuo")
situ:say("你这张嘴，真是让人不省心。")
situ:emotion()
qiliuge:emotion("JingYa")
qiliuge:say("是是是，我这嘴就是欠抽，掌门训斥的是, 看我抽烂这破嘴。")
hide_all_stage_bubble()

play_sfx("Story/Wave.mp3")
wait_twn(qiliuge:shake(), qiliuge:daze())
play_sfx("Story/Wave.mp3")
wait_twn(qiliuge:shake(), qiliuge:daze())
play_sfx("Story/Wave.mp3")
wait_twn(qiliuge:shake(), qiliuge:daze())

situ:say("好了好了，这么多年了我还不了解你么，你不嘴碎我还觉得缺点什么。")
qiliuge:emotion("HaiXiu")
qiliuge:say("[挠了挠头]嘿嘿。")
situ:say("罢了，回去吧。")
qiliuge:emotion( )
qiliuge:say("好的, 掌门!")
hide_all_stage_bubble()

wait_twn(situ:flip())
situ:movetoX(3000)
wait_twn(qiliuge:movetoX(3000))

black_scene(0.25)
hide_stage()
set_flag("完成初遇鹿追")
light_scene(0.25)