show_stage("bg_186.png", "鹿追的房间")
play_bgm("Music/少女鹿追.wav")

local situ = actor("司徒来也")
local luzhui = actor("鹿追")

--初始化位置和朝向
dark_all_actors()
situ:bright()
situ:setPos(600, 75)
situ:face_right()
situ:emotion("BeiShang")

luzhui:face_left()
luzhui:setPos(2300, 55)

wait_twn(situ:offsetX(200, 100), situ:spring_scale(1.03, 1.03, 1, 0.7))
situ:say("啊……－O－")
wait_twn(luzhui:movetoX(950, 2500), situ:shake())
luzhui:say("夫君！(突然撞进(player:fullname)怀里)")
situ:emotion("WeiXiao")
situ:say("啊哈哈…鹿追姑娘。")
luzhui:say("夫君是不是没睡好呀？")
situ:say("睡得甚好，自鹿追姑娘踏入虎焰门，我便夜夜好梦。")
luzhui:say("胡说，刚才还打哈欠呢。")
situ:say("我精神着呢，我可是息风谷五门中最年轻有为的掌门人。")
luzhui:say("夫君，我看你平时和大家一起的时候，都嘻嘻哈哈的很有精神，但一个人的时候又时常眉头紧锁，一定是有很多心事吧。")
situ:emotion("HaiXiu")
situ:say("啊，你…")
luzhui:say("夫君我说得不对吗？")
situ:emotion("BeiShang")
situ:say("鹿追姑娘，你不要观察我这么仔细呀，就让我做一个潇洒大气的(player:fullname)吧。")
luzhui:say("夫君这种表面的潇洒，会不会很累啊。")
situ:say("你年纪轻轻，为什么言语却总能触动我心。")
luzhui:say("如果我让夫君不舒服了，请夫君惩罚我。希望夫君在小鹿面前，就不需顾虑男子汉的颜面了，能屈能伸方为大丈夫，夫君若有心事，不便与他人说，尽管向我倾诉。")
situ:emotion("HaiXiu")
situ:say("好…好…好久没有这种感觉了。")
luzhui:say("嘻嘻，夫君，加油，你可是最年轻有为的掌门！")
situ:emotion()
situ:say("是的，总有一天，我会让虎焰门重现辉煌。")

change_favor_by_id("鹿追", 1)
change_favor_by_id("司徒来也", 1)

pop_tip("对鹿追的称呼改为“小鹿”")

black_scene(0.25)
hide_stage()
set_flag("完成鹿追剧情3")
light_scene(0.25)
