
show_stage("禁地.png", "训练场")
play_bgm("Music/密谋_夜郎.wav")
light_scene(0.2)

local situ = actor("司徒来也")
local npc = actor("朱鹮儿")
local qiliuge = actor("齐六哥")

--初始化位置和朝向
bright_all_actors()
situ:setPos(1000, 75)
npc:setPos(800, 75)
qiliuge:setPos(2200, 75)
situ:face_right()
npc:face_right()
qiliuge:face_left()

wait_twn(situ:offsetX(200), situ:daze())
npc:say("嘿！小(player:gname)，别跑！")
situ:flip()
situ:say("谁跑了？我只是恰好路过这里。")
npc:say("自从上次射箭输给我，你就一直躲着我。是不是不好意思面对我这位神箭手了？")
situ:say("小鹮儿，你可别太得意，射几只麻雀不算什么。能射穿万雀溪谷的才是真正的英雄。")
npc:say("你答应过我的，那把比这好十倍的弓呢？可不能说话不算数。")
situ:say("我答应你的事，自然会做到。")
npc:say("可是都已经过去这么久了。")
wait_twn(qiliuge:movetoX(1500), qiliuge:daze())
qiliuge:say("掌门！掌门！找到了。")
situ:say("你看，这不就来了。")
qiliuge:say("掌门，这就是您让我去找的那把弓。找它可费了不少劲，幸好没有被那场大火烧毁。")
npc:say("这把弓虽然看起来有些旧，但材质和纹路确实非常精致。")
situ:say("这把弓是我娘亲用过的，小时候，她经常带着这把弓带我去火神树林射斑鸠。现在，我把它送给你。")
npc:say("谢谢小(player:gname)！这把弓叫什么名字呢？")
situ:say("娘亲从未给它取过名字。既然现在它属于你了，那就叫它“振雀弓”吧！")
npc:say("振雀弓！好名字！")

hide_all_stage_bubble()

change_favor_by_id("朱鹮儿", 1)

black_scene(0.25)
hide_stage()
set_flag("完成朱鹮儿剧情5")
light_scene(0.25)
