show_stage("火神树林.png", "火神树林外围")
play_bgm("Music/少女鹿追.wav")
light_scene(0.2)

local qiliuge = actor("齐六哥")
local situ = actor("司徒来也")

--初始化位置和朝向
dark_all_actors()
situ:bright()
situ:setPos(-400, 75)
situ:face_right()
qiliuge:setPos(-700, 75)
qiliuge:face_right()

--先一起走过去
situ:movetoX(1100)
wait_twn(qiliuge:movetoX(800), qiliuge:daze())

situ:flip()
qiliuge:say("掌门，你看上去似乎有些心事？")
situ:say("唉，父亲传下的武学秘籍，我至今仍未窥其堂奥。若不能领悟，又如何能光大我派？")
qiliuge:say("掌门可曾记得火神之树？")
situ:say("父亲生前曾言，火神之树四季常红，犹如不灭之火。你此刻提起，难道此树有甚玄机？")
qiliuge:say("火神之树乃火神之化身，火神庇佑众生，息风谷中亦有信徒奉其为至高神明，他们相信火神之树能赐予力量。")
situ:say("赐予力量……")
qiliuge:say("掌门似有所悟？")
situ:say("我虽不迷信鬼神，但若真能“有求必应”，那火神之树或许真与武学修炼有所关联……哈哈，不过也只是臆测而已。")
qiliuge:say("正是此意，老掌门亦有此猜测，故而在修炼武学之时，对火神之树格外留心。我疑心虎焰门之祸，或与此树有关。")
situ:say("火神之火本应庇佑苍生，虎焰门却在其庇护下化为灰烬，真是讽刺。")
qiliuge:say("掌门可知“以火攻火”之法？")
situ:say("此言何意？")
qiliuge:say("传说邪火侵体，唯有以更猛烈的火焰方能压制。")
qiliuge:say("夜鸦虽行踪诡秘，手段狠辣，但其火焰终究是阴火。以火攻火，以明火制阴火，我虎焰门定能成为压制阴火的希望之光。")
situ:say("说得好！虎焰门的复仇之火，正是为此而燃！")
hide_all_stage_bubble()
situ:flip()
situ:movetoX(3000)
wait_twn(qiliuge:movetoX(3000))

black_scene(0.25)
hide_stage()
set_flag("完成火神之树")
light_scene(0.25)
