show_stage("bg_192.png", "虎焰堂")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")

--初始化位置和朝向
dark_all_actors()
situ:setPos(1100, 75)
situ:face_left()
qiliuge:setPos(700, 75)
qiliuge:face_right()

qiliuge:say("掌门，今日让我为您细细道来，我们江湖中的外交、好感度、宣战与结盟之术。")
situ:say("六哥，但说无妨，我正想听听这江湖外交有何奥妙。")
qiliuge:say("这外交之道，如同与邻里相处，需时常问候，以礼相待，方能维系和睦。好感度越高，对方越可能对我们抱有善意。")
situ:say("原来这好感度，便是江湖中的“撩”技啊！")
qiliuge:say("正是如此。至于宣战，那可是一场关乎生死的大事。就如同您与饭馆老板翻脸，摔盘子“砸”，关系必然恶化。在我们江湖中，宣战需慎重考虑，一步走错，满盘皆输。")
situ:say("我明白了。那结盟呢？是否意味着我们要“联手”对抗强敌？")
qiliuge:say("正是如此。结盟便是寻找志同道合的伙伴，共同面对江湖中的强敌。")
situ:say("原来如此，好感是“撩”，宣战是“砸”，结盟是“联手”，六哥这说法，简单易懂！")
hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成远交近攻")
light_scene(0.25)
