show_stage("bg_219.png", "虎焰门大堂")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-200, 75)
qiliuge:setPos(-400, 75)
liuming:setPos(-200, 75)
zsniang:setPos(-400, 75)
situ:face_right()
qiliuge:face_right()
liuming:face_right()
zsniang:face_right()

--先一起走过去
situ:offsetX(1000)
wait_twn(qiliuge:offsetX(1000), qiliuge:daze())

qiliuge:say("曾经的虎焰堂是如何显赫，可惜如今却只剩下这片废墟……")
situ:flip(0.2)
situ:say("六哥，倒也不必伤感这残垣断壁，重建虎焰堂之后，一样可以重现往日风光啊。")
qiliuge:say("好！要干活那人自然越多越好，我叫人来！刘明！朱三娘！")
qiliuge:flip(0.2)
qiliuge:say("刘明，朱三娘你们一起来吧。")

liuming:offsetX(600)
wait_twn(zsniang:offsetX(600), zsniang:daze())
liuming:say("来了！")
zsniang:say("齐总管有何吩咐？")
situ:say("果然还是“众人拾柴火焰高”啊。")
hide_all_stage_bubble()

wait_twn(situ:flip(), situ:offsetX(800), situ:daze())
wait_twn(qiliuge:flip(), qiliuge:offsetX(500), qiliuge:daze())
wait_twn(liuming:offsetX(200), liuming:daze())

stage_narration("虎焰门众人热火朝天地清理起了废墟")

black_scene(1)
wait_for_seconds(1)
light_scene(1)

liuming:say("俺发现了个东西！")
qiliuge:say("那是什么？")
wait_twn(liuming:offsetY(-100), liuming:daze())
liuming:say("俺不识得，像是本书。")
hide_all_stage_bubble()
liuming:offsetY(100)
wait_twn(zsniang:offsetX(100), zsniang:daze())
zsniang:say("看上去是一份画着红色的树叶标志的手稿，上面还有些字呢。")
situ:flip()
wait_twn(situ:offsetX(-800), situ:standfront())
situ:say("“其疾如风，侵略如火……”，后面的字就模糊看不清了，仿佛是《疾风烈焰掌》的口诀？")
hide_all_stage_bubble()
show_card{"疾风烈焰掌·残"}
add_player_item("疾风烈焰掌·残", 1)
zsniang:say("掌门，你看这手稿里面还包着一枚有点像钥匙的令牌。这上面的标记兴许跟这手稿也有关系？")
hide_all_stage_bubble()
show_card{"有点像钥匙的令牌"}
add_player_item("有点像钥匙的令牌", 1)
qiliuge:flip()
wait_twn(qiliuge:offsetX(-100), qiliuge:daze())
qiliuge:say("岁炙叶，这是岁炙叶的标志，看来我们虎焰门和炙家族应该有某种联系。")
situ:say("上次那个叫鹿追的女孩，在火神树林里面采摘岁炙叶。")
qiliuge:say("掌门，我们不妨再去火神树林探探究竟。")
situ:say("好，事不宜迟。我们收拾一下，带上这份手稿和令牌，去火神树林看看。")

change_favor_by_id("刘明", 1)
change_favor_by_id("朱三娘", 1)
change_favor_by_id("齐六哥", 1)

black_scene(0.25)
hide_stage()
set_flag("完成重建虎焰堂")
light_scene(0.25)
