show_stage("禁地.png", "训练场")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-400, 75)
situ:face_right()
qiliuge:setPos(-700, 75)
qiliuge:face_right()

--先一起走过去
situ:movetoX(1100)
wait_twn(qiliuge:movetoX(800), qiliuge:daze())

situ:flip()
situ:say("虎焰门此次遭劫，连训练场也未能幸免于难。那些珍贵的武器防具，也被毁得支离破碎……")
qiliuge:say("掌门莫愁，我知一处隐秘之所，尚存有一些武器防具。")
situ:say("哦？这四周一览无遗，难道还有什么机关不成？")
qiliuge:say("掌门聪慧。你往东方行去，立于震位之上。我这就去取来。")
hide_all_stage_bubble()
wait_twn(situ:flip(), situ:offsetX(300), situ:daze())
wait_twn(qiliuge:offsetX(100), qiliuge:offsetY(-100), qiliuge:daze())
qiliuge:say("掌门，东西已经取到了。")
hide_all_stage_bubble()
qiliuge:offsetY(100)
add_player_item("精良轻甲", 1)
add_player_item("精良中甲", 1)
wait_twn(situ:flip(), situ:offsetX(-200), situ:daze())
situ:say("哈哈，这些武器防具果然非凡，正是我门中所需。")
qiliuge:say("正是，掌门。如今有了这些装备，我们便可着手重建训练场。")
situ:say("六哥，我们就此重建训练场，待它落成之日，我等便可在此磨砺武功，培养门下英才。")
qiliuge:say("好的，掌门。我们共同努力，必能让虎焰门重现辉煌。")

hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成重建训练场")

pop_tip("现在可以 <color=red>训练下属</color>（消耗银两快速提升角色）了")
light_scene(0.25)
