show_stage("庭院.png", "虎焰堂外")
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local liuming = actor("刘明")

--初始化位置和朝向
dark_all_actors()
situ:setPos(1000, 75)
situ:face_left()
qiliuge:setPos(650, 75)
qiliuge:face_right()
liuming:setPos(1350, 75)
liuming:face_left()

qiliuge:say("掌门，龙湾门近日气焰嚣张，东方家三兄弟似乎对我们虎视眈眈，东方豚一事未了，东方鲨又蠢蠢欲动。")
situ:say("东方家的老大与老二，一个嗜食如命，一个情根深种，皆不足为患。倒是那老三东方狸，行踪诡秘，心思难测。")
qiliuge:say("还有他们那位威名远扬的父亲。")
liuming:say("掌门，让俺刘明去会会他们！")
situ:flip()
situ:say("老刘，你的勇气可嘉，但江湖险恶，非同小可。")
liuming:say("六哥，除了龙湾门，其他门派近况如何？")
qiliuge:say("江湖上，圣剑门仍旧一家独大。")
situ:flip()
situ:say("圣剑门，一直是江湖中的佼佼者。")
qiliuge:say("他们的掌门人百里烟波，行踪飘忽，如同传说中的息风谷第一高手，无人得见其真容，但他的威名却如影随形。")
situ:say("百里烟波，究竟是何方神圣，终有一日，我要亲自领教。")
qiliuge:say("听闻圣剑门已将司南地宫与摇舟半岛纳入麾下。")
situ:say("那两个地方，不是被夜鸦所毁吗？")
qiliuge:say("正是，江湖中人对此地避之不及，多年来已成荒芜。")
situ:say("圣剑门此举，无疑是在展露其野心。")
qiliuge:say("如此看来，同样受夜鸦所害的虎焰门，恐怕也在百里烟波的算计之中。")
liuming:say("掌门，让俺去除了这个百里烟波。")
situ:flip()
situ:say("老刘，江湖之事，非一人之力所能解决。你还是先专心练好你的武功吧。")
hide_all_stage_bubble()
add_player_item("烧鱼", 1)
black_scene(0.25)
hide_stage()
set_flag("完成饭桌闲聊")
light_scene(0.25)
