
show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local pinger = actor("[speaker:萍儿][img:ai2_female_20]")
local ximenxiang = actor("西门香")
local dongfangtun = actor("东方豚")

--初始化位置和朝向
bright_all_actors()

dongfangtun:setPos(100, 75)
dongfangtun:face_right()
pinger:setPos(1200, 75)
pinger:face_right()
ximenxiang:setPos(1500, 75)
ximenxiang:face_left()

pinger:say("小姐，这位莫非是龙湾门的东方二公子？")
ximenxiang:say("哦？这么远你都能认出来？")
pinger:say("像东方公子这样风度翩翩的少年英雄，息风谷又有几个呢？")
ximenxiang:say("瞧你这副花痴的模样。")
wait_twn(dongfangtun:movetoX(800), dongfangtun:daze())
dongfangtun:say("西门小姐，龙湾门东方豚有礼了。久仰西门小姐芳名，今日特来拜访。")
pinger:flip()
pinger:say("真的是东方公子呢。")
ximenxiang:say("你怎么来了？")
dongfangtun:say("奉家父之命，特来鹤岭门拜访，以表龙湾门与鹤岭门近年来的友谊，同时也带来了一些薄礼。")
pinger:say("有什么礼物，有送给小姐的吗？")
dongfangtun:say("有的，这枚黄玉簪，是特别为西门小姐挑选的，不知小姐是否喜欢。")
ximenxiang:say("谢谢，不过，颜色不太合我意。")
pinger:flip()
pinger:say("小姐……")
dongfangtun:say("没关系，我稍后会把这些礼品呈给西门掌门，里面还有一些银器和食品，西门小姐可以去挑选，看看有没有喜欢的。")
ximenxiang:say("那辛苦你了，我父亲现在在茶室休息，你去见见他吧。")
dongfangtun:say("那就先告辞了，谢谢西门小姐。")
ximenxiang:say("不客气。")
dongfangtun:flip()
wait_twn(dongfangtun:movetoX(-500))
pinger:say("小姐。")
ximenxiang:say("嗯？")
pinger:say("你对东方公子怎么这么冷淡啊？")
ximenxiang:say("冷淡吗？")
pinger:say("够冷淡的，我都尴尬得起鸡皮疙瘩了。")
ximenxiang:say("哎，好像也是。有些人虽然才貌双全又彬彬有礼，但就是心底里喜欢不起来。")
pinger:say("当然了，小姐心里最喜欢的只有虎焰门的(player:fname)公子。")
ximenxiang:flip()
ximenxiang:say("哎，不知道他怎么样了……")
hide_all_stage_bubble()

change_both_friendship("龙湾门", "鹤岭门", 20)

black_scene(0.25)
hide_stage()
set_flag("完成东方豚访鹤岭")
light_scene(0.25)
