
show_stage("西门香的房间.png", "西门香的房间")
play_bgm("Music/回忆.wav")
light_scene(0.2)

local situ = actor("司徒来也")
local npc = actor("西门香")
local pinger = actor("[speaker:萍儿][img:ai2_female_20]")

--初始化位置和朝向
bright_all_actors()
pinger:setPos(-400, 75)
pinger:face_right()
situ:setPos(-700, 75)
situ:face_right()
npc:setPos(1200, 75)
npc:face_left()

wait_twn(pinger:movetoX(900), pinger:daze())

pinger:say("小姐，我历尽千山万水，终于找到你了。")
npc:say("萍儿，你怎么来了？")
pinger:say("小姐，自你离家那日起，我便追随你的脚步。我猜想你定是投奔了虎焰门。")
npc:say("此事说来话长，不过我在这里过得也不错。")
pinger:say("小姐，我离开之时，听说老爷已决意将你许配给龙湾门的东方豚公子。")
npc:shake()
npc:say("什么？！我爹怎会擅自做出这样的决定？")
pinger:say("是的，小姐。老爷已然前往龙湾门，这门亲事似乎已成定局。")
npc:say("我绝不会嫁给东方豚，我已心有所属！我已经是(player:fullname)的人了。")
pinger:say("啊！小姐，你和(player:fullname)已经成亲了？")
npc:say("我们本身就是有婚约的，只是因为虎焰门的事情，我们一直没成婚。你快回去告诉我爹，我绝不会屈从于他的安排。")
pinger:say("小姐放心，我会回去告诉老爷的。有任何什么风吹草动，我也会第一时间告诉你。")
npc:say("谢谢你，萍儿。")
hide_all_stage_bubble()
npc:flip()
wait_twn(pinger:movetoX(2500))
wait_twn(situ:movetoX(900), situ:daze())
situ:say("香儿，你们的对话我都听到了。")
npc:flip()
npc:say("(player:fullname)，我如今真是无家可归了。")
situ:say("香儿，你不必担心，我绝不会让你孤苦无依。")
npc:say("我爹突然废除了我们的婚约，加之我离家出走，更将虎焰门视为仇敌。")
situ:say("西门坡前辈向来精明，他日虎焰门定能让他刮目相看，不必过于忧虑。")
npc:say("我爹此番前往龙湾门，恐怕不只是为了订婚一事，就怕二强连横，将虎焰门置于危险之地。")
situ:say("香儿，你不必过于担忧了……")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成萍儿告密")
light_scene(0.25)
