
show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav")
light_scene(0.2)

local ximenpo = actor("西门坡")
local ximenting = actor("西门霆")
local ximenxiang = actor("西门香")

--初始化位置和朝向
bright_all_actors()

ximenting:setPos(600, 75)
ximenting:face_right()
ximenpo:setPos(1000, 75)
ximenpo:face_left()
ximenxiang:setPos(1400, 75)
ximenxiang:face_left()

ximenpo:say("什么？(player:fname)兄竟也遭了毒手？")
ximenting:say("是的，父亲，据可靠消息，(player:fname)掌门与南宫夫人，均已不幸遇害。")
ximenxiang:say("那…那…")
ximenting:say("姐姐放心，(player:fullname)幸免于难，听说那日他恰好不在虎焰门中。")
ximenpo:say("虎焰门何等威名，竟在一夜之间遭遇此劫，这背后究竟是何等势力作祟？")
ximenting:say("听闻昔日息风谷两大门派，也是一夜之间因一场神秘鬼火而毁。")
ximenpo:say("夜鸦……")
ximenting:say("夜鸦？")
ximenpo:say("这个名字，已被江湖遗忘多年。")
ximenxiang:say("爹，我想前往虎焰门一探究竟。")
ximenpo:flip()
ximenpo:say("你给我站住！")
ximenxiang:say("(player:fname)家与我们西门家世代交好，我与(player:fullname)更是有婚约在身。如今虎焰门遭遇此难，我怎能不去？")
ximenpo:say("现在去也无济于事。")
ximenxiang:say("我与(player:fullname)即将完婚，难道要等到他也遭遇不幸，我才能去看他冰冷的尸骨不成？")
ximenpo:say("香儿，你须知夜鸦的恐怖，此刻你若执意前往虎焰门，便是将我西门家拖入险境。")
ximenting:say("姐姐，父亲言之有理，我们还需保全自身，再考虑其他。")
ximenxiang:say("西门霆，你怎么也变得如此冷漠！")
ximenpo:flip()
ximenpo:say("即日起，西门家全员戒备，任何人不得擅自外出！")
hide_all_stage_bubble()
-- unlock_menpai("鹤岭门", true)

black_scene(0.25)
hide_stage()
set_flag("完成鹤岭门登场")
light_scene(0.25)
