show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local ximenpo = actor("西门坡")
local ximenting = actor("西门霆")
local hangong = actor("韩恭")
local zhaorang = actor("赵让")

--初始化位置和朝向
dark_all_actors()
ximenpo:setPos(800, 75)
ximenpo:face_right()
ximenting:setPos(500, 75)
ximenting:face_right()
hangong:setPos(2400, 75)
hangong:face_left()
zhaorang:setPos(2700, 75)
zhaorang:face_left()

hangong:movetoX(1200)
wait_twn(zhaorang:movetoX(1500), zhaorang:daze())

hangong:say("韩某有愧门主所托……")
ximenpo:say("韩长老不必内疚，没想到(player:fullname)那小子武功竟如此高深！")
ximenting:say("师父，姐姐是不回来了吗？")
ximenpo:flip()
ximenpo:say("什么姐姐！如此不肖女，我权当作没有生养过！")
ximenting:say("姐姐一贯温婉大方善解人意，对那(player:fullname)想必是真情……父亲何苦拆散一对情侣，本来就有婚约在先……")
ximenpo:say("你这个不肖子！")
ximenting:say("啊！父亲！")
zhaorang:say("请门主手下留情，切勿伤了父子和气！")
ximenpo:flip()
ximenpo:say("都说虎父无犬子！我怎么儿女一个个如此不成器！")
zhaorang:say("霆儿年纪尚小，不懂门主一片苦心，日后请韩右使多加教导便是，定不负门主期待。")
ximenpo:say("哼，若不是门中事务繁重，我疏于对这双儿女的管教。这小子若在我手底下长大也不会如此妇人之仁了。")
zhaorang:say("是，门主说得对……我先带霆儿下去冷静。")
hide_all_stage_bubble()
wait_twn(zhaorang:movetoX(700))
zhaorang:flip()
zhaorang:movetoX(3000)
wait_twn(ximenting:movetoX(3000))
wait_for_seconds(1)
wait_twn(hangong:movetoX(1100), hangong:daze())
hangong:say("门主，现下小姐已留在虎焰门中，世人眼中我们两派已然结仇，接下来的计划也好开展了。")
ximenpo:say("哼！这男欢女爱哪有一门存亡重要，怪只怪虎焰门惹上了不该惹的！")
ximenpo:say("这便以讨要鹤岭门大小姐西门香为由，向虎焰门宣战！韩长老，接下来还要辛苦你了。")
hangong:say("定不负门主重托！")
hide_all_stage_bubble()

local diplomatic = require("Common/diplomatic")
diplomatic.declare_war("鹤岭门", "player")

black_scene(0.25)
hide_stage()
set_flag("完成鹤岭宣战")
light_scene(0.25)
