show_stage("bg_166.png", "虎焰门大堂")
play_bgm("Music/山雨欲来风满楼.wav")
light_scene(0.2)

local ximenpo = actor("西门坡")
local ximenting = actor("西门霆")
local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")

--初始化位置和朝向
bright_all_actors()

ximenpo:setPos(-400, 75)
ximenpo:face_right()
ximenting:setPos(-700, 75)
ximenting:face_right()
situ:setPos(1100, 75)
situ:face_left()
qiliuge:setPos(1400, 75)
qiliuge:face_left()

ximenpo:movetoX(700)
wait_twn(ximenting:movetoX(400), ximenting:daze())

ximenpo:say("(player:fname)贤侄，今日我父子二人特来告知，你与爱女西门香之间的婚姻之约，就此作罢。")
qiliuge:say("西门掌门，此举是为何故？")
ximenpo:say("(player:fullname)，你应该明了，虎焰门已然覆灭，(player:fname)雷亦已遭遇不幸。你现在还有什么资格与我女儿成婚？")
qiliuge:say("西门掌门，你如此看重权势，未免太过势利了吧。")
wait_twn(ximenting:jumpTo(900, 75))
qiliuge:offsetX(100)
wait_twn(situ:offsetX(100))
ximenting:say("(player:fullname)，你不过是个丧家之犬，有何资格与我西门家联姻？")
situ:emotion("NaoHuo")
situ:say("西门霆，你说话放尊重些。")
ximenpo:say("(player:fullname)，我今日来，就是要告诉你，你与我女儿的婚约，就此解除。你若是还有一丝自尊，就请你离开，不要再出现在我女儿的面前。")
situ:say("西门掌门，你如此绝情，我也无话可说。三十年河东，三十年河西，莫欺少年穷。")
ximenpo:say("那就看你有没有这个本事了。")
hide_all_stage_bubble()

local diplomatic = require("Common/diplomatic")
diplomatic.neutral("鹤岭门", "player")
--离开
ximenpo:flip()
ximenpo:movetoX(-500)
ximenting:flip()
wait_twn(ximenting:movetoX(-500))

black_scene(0.25)
hide_stage()
set_flag("完成鹤岭悔婚")
light_scene(0.25)
