
show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local ximenpo = actor("西门坡")
local hangong = actor("韩恭")
local zhaorang = actor("赵让")

--初始化位置和朝向
dark_all_actors()
ximenpo:setPos(800, 75)
ximenpo:face_right()
hangong:setPos(2400, 75)
hangong:face_left()
zhaorang:setPos(2700, 75)
zhaorang:face_left()

hangong:movetoX(1200)
wait_twn(zhaorang:movetoX(1500), zhaorang:daze())

hangong:say("参见门主！")
zhaorang:say("参见门主！")
ximenpo:say("赵左使？韩右使？二位长老忽然前来，难道有何要事？")
hangong:say("实不相瞒，我等乃是为前日虎焰门被灭一事而来。")
zhaorang:say("我等听闻门主近些时日加强戒备，又严禁内外传递消息，恕属下直言……莫非是忌惮江湖中那方势力要于我鹤岭门不利？")
ximenpo:say("唉……两位也是门中元老，自先父接任掌门时便多有襄助，自然也经历过当年惨状……如今香儿霆儿还都年轻，也该明白这鹤岭门的无奈……")
hangong:say("如今江湖动荡，我等自是心系门中安危，故而前来与门主相商。")
ximenpo:say("哦？莫非二位长老有何高见？")
zhaorang:say("如今江湖动荡，我鹤岭门虽有些势力，但到底也要提防谨慎些才是。")
zhaorang:say("尤其虎焰门这样的势力都在一夕之间覆灭，可想这背后的势力纷争，更是让人忌惮……")
ximenpo:say("正是如此啊！我鹤岭门与虎焰门联合，算是一条出路，可如今，谁能想竟引火烧身。")
hangong:say("门主倒也不必为此事烦心，当年立定婚约之时，也只是口头承诺，虎焰门在场之人已然逝去。")
ximenpo:say("此话甚是有理！当真如拨云见日，使我茅塞顿开。")
zhaorang:say("此事有关香儿的终身幸福，也关系到鹤岭门的名声，自然是反悔不得！")
hangong:flip()
hangong:say("强强联合本就是一桩美谈，如今虎焰门败了，便算不得名门。鹤岭门门主之女，可从未许配过江湖之中的破落帮派之子！")
zhaorang:say("事关香儿的婚姻，仍需从长计议。")
hangong:flip()
ximenpo:say("两位长老这一路奔波，想来也累了，先去休息吧。容我思虑一番。")
hangong:say("门主，属下告退。")

hide_all_stage_bubble()
zhaorang:flip()
zhaorang:movetoX(3000)
hangong:flip()
wait_twn(hangong:movetoX(3000))

black_scene(0.25)
hide_stage()

show_stage("河边.png", "河边")
play_bgm("Music/密谋_夜郎.wav", 0.1)
light_scene(0.2)

local hangong = actor("韩恭")
local zhaorang = actor("赵让")

--初始化位置和朝向
bright_all_actors()
hangong:setPos(2700, 75)
hangong:face_left()
zhaorang:setPos(2400, 75)
zhaorang:face_left()

zhaorang:movetoX(900)
wait_twn(hangong:movetoX(1200), hangong:daze())

zhaorang:flip()
zhaorang:say("韩右使此番到底是何盘算？")
hangong:say("赵左使此言何意？")
zhaorang:say("倘若真按韩右使此番安排，置香儿于何境地？")
hangong:say("东方家的老二东方豚对大小姐情有独钟，必会全心全意呵护大小姐。更何况龙湾门的龙夫人与我曾有交情，她定会玉成此事。")
zhaorang:say("香儿可是我一手带大的徒儿，她的婚姻自然还是得以她的意愿为准。")
hangong:say("那是自然，我教霆儿武功时，大小姐同霆儿总在一处，也算是我看着长大，又怎么会害她？")
zhaorang:say("但愿如此，不然别怪我为了爱徒，不讲同僚情面！")
hangong:say("这门婚事本来就是为大小姐觅得佳婿，更何况又有你这个师父照拂，还有什么不放心的？")
zhaorang:say("如此倒也在理。")

hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成鹤岭二老劝婚")
light_scene(0.25)
