show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local ximenpo = actor("西门坡")
local hangong = actor("韩恭")
local zhaorang = actor("赵让")

--初始化位置和朝向
dark_all_actors()
ximenpo:setPos(800, 75)
ximenpo:face_right()
hangong:setPos(500, 75)
hangong:face_right()
zhaorang:setPos(2700, 75)
zhaorang:face_left()

wait_twn(zhaorang:movetoX(1200), zhaorang:daze())

zhaorang:say("门主！你竟然真要将香儿嫁给龙湾门？")
ximenpo:say("正是如此，不日韩右使便要去龙湾门议亲。")
hangong:say("如今已解除与虎焰门的婚约。龙湾门的二少爷生得风流倜傥，家世显赫，品行一流，正是门主为大小姐觅得的佳婿。")
zhaorang:say("可是如此安排万万不可！")
hangong:say("赵左使莫非对门主的安排有什么异议？")
zhaorang:say("门主请三思，江湖局势诡谲，此前我们与虎焰门结盟才得了几分喘息余地。")
zhaorang:say("如今虎焰门灭门后我们立即悔婚，着实落得不忠不义不信的口舌啊。")
hangong:say("呵，现在江湖谁不知道虎焰门灭门，前任掌门夫妇横死，只剩这个毛头小子。")
hangong:say("这样的家室出身，又怎么能配得上我鹤岭门的大小姐、您赵左使的爱徒呢？")
zhaorang:say("门主，若大小姐就这般嫁入龙湾门，天下人会如何背后说我们鹤岭门？")
hangong:say("哟，赵让，想不到你沽名钓誉的本事倒是比武功更胜一筹啊！")
ximenpo:say("不过是些浮名！这乱世之中，能保全自身才是重中之重！")
hangong:say("门主说得对，我看大小姐嫁入龙湾门正是合适，如今龙湾门势头正好，为何不搭上这股东风？")
zhaorang:say("那又置大小姐于何处？大小姐又如何在龙湾门中自处？")
hangong:say("这世道君子无立锥之地，赵让你在门中安生了太久，只知道小恩小惠！")
zhaorang:say("韩恭！同为门中长老，我可不是怕了你！")
hangong:say("那你就说道，西门香嫁入龙湾门有何不可？")
zhaorang:say("韩恭，我辅佐鹤岭门两代掌门，这条命就是与鹤岭门休戚与共！香儿一直心有所属，如今强行悔婚，于礼于亲都无益啊！")
hangong:say("满嘴仁义道德，实则不过帮你徒弟徇私！如今若能借到龙湾门之势，才是鹤岭门壮大的正道！旁得，又何必在意？")
zhaorang:say("香儿霆儿也是你从小看着长大，你为何如此不近人情！")
hangong:say("因为我一心只有鹤岭门！")
zhaorang:say("水能载舟亦能覆舟。这么简单的道理你如何不懂，人心向背不过一念之间。")
zhaorang:say("若因虎焰门破败便悔婚违约，岂非出尔反尔？鹤岭门又如何在江湖中立足？")
hangong:say("赵让，你真是越活越老糊涂了！照你之言，难道我们鹤岭门尽是背信弃义、趋炎附势之流？")
zhaorang:say("你！你这是胡搅蛮缠！")
ximenpo:say("两位长老慎言！此事多说无益，都暂且退下去吧。")

hide_all_stage_bubble()
zhaorang:flip()
wait_twn(zhaorang:movetoX(3000))
wait_twn(hangong:movetoX(3000))

black_scene(0.25)
hide_stage()

show_stage("龙湾门大堂.png", "龙湾门大堂")
set_bg_mat("ImgPaperFold")
play_bgm("Music/密谋_夜郎.wav")
light_scene(0.2)

local hangong = actor("韩恭")
local dongfangzhouyu = actor("东方骤雨")
local dongfangtun = actor("东方豚")
local longwanying = actor("龙万莹")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
hangong:setPos(-500, 75)
hangong:face_right()
dongfangzhouyu:setPos(1000, 75)
dongfangzhouyu:face_right()
dongfangtun:setPos(2500, 75)
dongfangtun:face_left()
longwanying:setPos(2800, 75)
longwanying:face_left()

wait_twn(hangong:movetoX(600), hangong:daze())
dongfangzhouyu:flip()
hangong:say("东方门主，韩恭有礼了。")
dongfangzhouyu:say("贵客到访，有失远迎！来来来，韩长老，我已吩咐门中设宴，为长老接风洗尘！")
hangong:say("东方门主客气了！我不过是个媒人罢了，我家门主西门坡，久闻令郎东方豚少侠英名，武艺高强，侠义心胸，实为江湖少有的英杰。")
hangong:say("有意将小女西门香，配与少侠为偶，共结良缘，以固两家之谊。")
dongfangzhouyu:say("韩长老，此乃终身大事，非同儿戏。豚儿虽有些许薄名，但西门小姐乃是的名门闺秀，才貌双全，豚儿岂敢妄自高攀？")
wait_twn(dongfangtun:movetoX(1300, 2500), dongfangtun:daze())
dongfangzhouyu:flip()
dongfangtun:say("爹，孩儿愿意。若能得西门小姐为妻，此生无憾。")
dongfangzhouyu:say("豚儿不得无礼！")
hangong:say("哪里的话，二公子直言直语，当真性情中人也！")
dongfangzhouyu:flip()
dongfangzhouyu:say("见笑了韩长老，我这犬子自从遥遥见过西门姑娘一面，自此便魂牵梦萦，念念不忘啊……")
dongfangzhouyu:say("如今终于如愿以偿，一时妄言，当真越发不出息了……")
hangong:say("哪里哪里！东方二公子一表人才，又用情至深，想必与大小姐定是佳偶天成！")
dongfangzhouyu:say("哈哈哈哈哈，且看东方西门，一龙一鹤，正是绝配！")
hangong:say("自然，龙湾门如今如日中天，东方家族家学渊源深厚，若香儿嫁入东方家，我们两门喜结连理，更是江湖上的一段佳话。")
dongfangzhouyu:say("韩长老，请移步席上，我们且饮且叙。")
dongfangzhouyu:flip()
dongfangtun:flip()
hangong:movetoX(700)
wait_twn(longwanying:movetoX(1500), longwanying:daze())
hangong:say("龙夫人，好久不见。听闻夫人平素与江湖中各派交好，以后成了亲家，还需仰仗你多多引荐。")
longwanying:say("……")
dongfangtun:say("娘，您怎么了？")
longwanying:say("韩长老，许久不见，没想到犬子与西门香小姐……")
dongfangtun:say("娘，您面色苍白可是身体有何不适？")
longwanying:say("……")
dongfangzhouyu:say("想必夫人今日身体不适，来人，带夫人下去休息先。韩长老，且去里间，我们父子与你一同畅饮畅谈！")
hangong:say("那就却之不恭了！")

hide_all_stage_bubble()
stage_narration("月光洒在龙万莹的脸上，阴晴不定，如同她心上的波浪。")
change_both_friendship("鹤岭门", "龙湾门", 50)

black_scene(0.25)
hide_stage()

show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local ximenpo = actor("西门坡")
local hangong = actor("韩恭")
local ximenxiang = actor("西门香")
local dongfangzhouyu = actor("东方骤雨")
local dongfangtun = actor("东方豚")

--初始化位置和朝向
dark_all_actors()
ximenpo:setPos(800, 75)
ximenpo:face_right()
hangong:setPos(-500, 75)
hangong:face_right()
ximenxiang:setPos(-800, 75)
ximenxiang:face_right()
dongfangzhouyu:setPos(2400, 75)
dongfangzhouyu:face_left()
dongfangtun:setPos(2700, 75)
dongfangtun:face_left()

dongfangzhouyu:movetoX(1200)
wait_twn(dongfangtun:movetoX(1500), dongfangtun:daze())

dongfangzhouyu:say("西门兄，今日特地带犬子上门提亲。")
ximenpo:say("小女有这个福气与二公子共结连理，对我鹤岭门而言真是天大的喜事。")
dongfangzhouyu:say("西门兄客气了，与鹤岭门结亲，于我龙湾门也是一桩喜事。")
hide_all_stage_bubble()
hangong:movetoX(500)
wait_twn(ximenxiang:movetoX(200), ximenxiang:daze())
ximenpo:flip()
hangong:say("门主，已将大小姐请来。")
ximenpo:flip()
ximenpo:say("香儿，这是龙湾门的掌门，你的东方伯父。这是你的未来夫君，东方伯父的二公子东方豚。今日且见过吧。")
dongfangtun:say("西门、西门小姐！来啦！")
dongfangzhouyu:say("让西门兄见笑了。")
ximenpo:say("年少慕艾，人之常情，看出二公子对香儿是一片真心。谁不希望儿女有个好归宿呢？我们这做父母的，也就安心了。")
dongfangtun:say("西门伯父，我定将好好对西门小姐，一生一世保护她！")
ximenxiang:say("……")
dongfangzhouyu:say("大小姐今日一见，果然蛾眉皓齿，兰心蕙质，端得有大家之风！不愧是西门兄教养出来的大家闺秀。")
dongfangzhouyu:flip()
dongfangzhouyu:say("豚儿，先前准备的东西呢？")
dongfangzhouyu:flip()
dongfangtun:say("先前的既然小姐不喜欢，这是特地寻遍名匠特地雕琢的一方粉玉芙蓉，还望小姐收下。")
ximenxiang:say("……")
ximenpo:say("这芙蓉……我们收下了，以此作为订亲的信物。")
dongfangzhouyu:say("好！好！今日龙湾门便与鹤岭门订立婚约，择日成亲。")
hide_all_stage_bubble()

local diplomatic = require("Common/diplomatic")
set_both_friendship("龙湾门", "鹤岭门", 100)
diplomatic.make_ally("龙湾门", "鹤岭门")

black_scene(0.25)
hide_stage()
set_flag("完成龙鹤结盟")
light_scene(0.25)


