
show_stage("门派宫殿.png", "飞星云顶")
play_bgm("Music/.mp3", 0.1)
light_scene(0.2)

local moguang = actor("墨光")
local moying = actor("墨影")
local heruyan = actor("贺如烟")
local zijinfeng = actor("子瑾风")

--初始化位置和朝向
bright_all_actors()

moguang:setPos(500, 75)
moguang:face_right()
moying:setPos(800, 75)
moying:face_left()
heruyan:setPos(1100, 75)
heruyan:face_left()
zijinfeng:setPos(1400, 75)
zijinfeng:face_left()

moguang:say("大老远便见到有人在这边，原来是如烟师姐。")
moying:say("师姐如何要亲自做些挑水的粗重活？")
moguang:say("可不？师姐如今是阴阳王面前的大红人，这么多年只收了师姐这唯一的女弟子，可见有多看重师姐了。")
heruyan:say("不……不是那般……")
moguang:say("不是哪般？谁能看不出来掌门多喜欢师姐？墨影你说是不是？")
moying:say("掌门一直惦念如烟师姐，我同墨光还从未见过阴阳王对旁人有过这样的心思。")
heruyan:say("我……你们……")
zijinfeng:say("你们不去勤加苦练，倒是有这闲暇乱嚼口舌？")
moguang:say("师兄，我们不过是……")
zijinfeng:say("不过什么？闲言碎语调侃师姐，可见心地不纯！若被掌门听去了，有你们好看！")
moying:say("是……师兄……")
moguang:say("罢了罢了……墨影，走吧……")
zijinfeng:say("这两个平时是有些不管不顾的，师妹可别往心里去。")
heruyan:say("如烟谢过师兄……既无其他要事，如烟也先告退。")
zijinfeng:say("嗯，师妹好走。")
hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成女徒贺如烟")
light_scene(0.25)
