show_stage("殿内.png", "??")
light_scene(0.2)
play_bgm("Music/密谋_夜郎.wav")

local jing = actor("鲸")
local yelang = actor("夜郎")

--初始化位置和朝向
dark_all_actors()
jing:setOverrideName("??")
jing:stylize("Silhouette")
jing:setPos(700, 75)
jing:face_right()
yelang:setOverrideName("??")
yelang:stylize("Silhouette")
yelang:setPos(1100, 75)
yelang:face_left()

jing:say("此次行动，虎焰门内知情者无一生还。只是那(player:fname)雷当真嘴严，根本问不出什么。")
yelang:say("无妨，(player:fname)雷夫妇不是软骨头，此番倒也是意料之中。")
jing:say("继司南地宫和摇舟半岛后，虎焰门亦无进展，会否于<color=red>主公</color>大计无益？")
yelang:say("这倒不必在意，虎焰门此番一无所获，反倒印证了一些推断。")
jing:say("还有一事，属下不知当不当报……")
yelang:say("讲。")
jing:say("(player:fname)雷还留有一子，当日不在门中，因而……")
yelang:flip()
yelang:say("哦？(player:fname)雷与南宫紫的儿子？这倒新鲜。")
jing:say("属下失职，此番一定戴罪补过。")
yelang:say("不必，暂且先留他一命。")

black_scene(0.25)
hide_stage()
set_flag("完成夜郎登场")
light_scene(0.25)
