show_stage("bg_219.png", "虎焰门大堂")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local situ = actor("司徒来也")
local laoyu = actor("[speaker:老妪][img:ai_old_female_2]")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
situ:setPos(900, 75)
situ:face_right()
laoyu:setPos(2400, 75)
laoyu:face_left()

wait_twn(laoyu:movetoX(1400), laoyu:daze())
laoyu:say("少侠，万雀溪谷正在举办“观鱼赏花大会”，吸引大量村民前去围观。")
situ:say("正好，我想要去看看，这请柬就送到了。")
hide_all_stage_bubble()
black_scene(0.25)
hide_stage()

show_stage("bg_92.png", "万雀溪谷")
play_bgm("Music/密谋_夜郎.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local zhuhuaner = actor("朱鹮儿")
local lbx1 = actor("[speaker:村民][img:pawn_CunMing_male_4]")
local lbx2 = actor("[speaker:村民][img:pawn_CunMing_female_2]")
local wanhecheng = actor("万壑成")
local dingxuan = actor("丁宣")
local wanque1 = actor("[speaker:万雀溪谷弟子][img:pawn_WanQueXiGu_male_2]")
local wanque2 = actor("[speaker:万雀溪谷弟子][img:pawn_WanQueXiGu_male_3]")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-500, 75)
situ:face_right()
zhuhuaner:stylize("Silhouette")
zhuhuaner:setOverrideName("？？？")
zhuhuaner:setPos(-500, 75)
zhuhuaner:face_right()
lbx1:setPos(700, 75)
lbx1:face_right()
lbx2:setPos(1500, 75)
lbx2:face_left()
wanhecheng:setPos(1300, -500)
wanhecheng:face_left()
dingxuan:setPos(1600, -500)
dingxuan:face_left()
wanque1:setPos(2500, 75)
wanque1:face_left()
wanque2:setPos(-500, 75)
wanque2:face_right()


lbx1:say("这万雀溪谷之中花草繁茂，竟然是这样一番别致景色！")
lbx2:say("这是我这辈子见过最好看的鱼！")
wait_twn(situ:movetoX(500), situ:daze())
situ:say("万壑成此举，这葫芦里到底卖的什么药？")
wait_twn(zhuhuaner:movetoX(200), zhuhuaner:daze())
zhuhuaner:say("万壑成这个老匹夫，如今搞这观鱼赏花大会，也不知又有什么盘算。")
situ:flip()
situ:say("咦？")
zhuhuaner:hide()
--一起跳出来
wait_twn(wanhecheng:jumpTo(1000, 75), dingxuan:jumpTo(1300, 75), dingxuan:daze())
situ:flip()
wanhecheng:say("诸位！大家赏脸参加我万雀溪谷这观鱼赏花的盛会，万某实在荣幸之至！")
wanhecheng:say("唉，近来江湖中对我溪谷颇有些风言风语，故而才借着今次的契机，澄清万某之心啊！")
dingxuan:say("正是！近来江湖之中风波不断，我谷主不过顺应天时，却不想被小人诋毁，实在无辜。如今借着此番盛会，也想借大家一点声势可好？")
hide_all_stage_bubble()
shake_stage(20, 3)
black_scene(0.5)
wait_for_seconds(0.5)
lbx1:offsetY(-200)
lbx2:hide()
zhuhuaner:show()
zhuhuaner:stylize()
zhuhuaner:setPos(2500, 75)
zhuhuaner:face_left()
light_scene(0.5)
situ:say("不对……这谷中似乎有异？莫非——")
dingxuan:say("谷主此计当真高明，如今这谷中之人皆这谷中所布之阵法控制，祭祀之人便是要多少有多少了！")
wanhecheng:flip()
wanhecheng:say("天师还不派人速速拿下这些四散奔逃的村民，今番万不可让一人逃脱！")
wanque2:movetoX(300)
wait_twn(wanque1:movetoX(1700), wanque1:daze())
wanque1:say("快快快！把这些人都给我逮起来！莫走漏了一个！老子还要拿这些刁民同天师讨赏呢！")
wanque2:say("抓起来，都抓起来，荣华富贵就在眼前！")
stage_narration("还是先讨条活命吧！看箭！")
wanque1:say("啊——")
wait_twn(wanque1:movetoY(-600, 5000))
dingxuan:flip()
wanque2:say("什、什么人！")
wait_twn(zhuhuaner:movetoX(1600), zhuhuaner:daze())
zhuhuaner:say("自然是路见不平之人！万雀溪谷以生人献祭，天理不容！")
dingxuan:say("臭丫头！莫非一直就是你从中作梗，挡了我谷中气运？")
zhuhuaner:say("哼！一帮神棍搅得江湖中乌烟瘴气，今日我朱鹮儿偏要替天行道，清理你们这些妖魔鬼怪！")
wanhecheng:say("大胆！我万雀溪谷岂容你一个野丫头造次！")
hide_all_stage_bubble()
dingxuan:jumpTo(1000, 75)
wait_twn(wanhecheng:jumpTo(1000, 600, 300, 3000), wanhecheng:jumpTo(1400, 75, 300, 3000), zhuhuaner:offsetY(-150))
zhuhuaner:say("我难道还怕了你这个老神棍不成？")
dingxuan:say("小丫头倒是嘴硬，看你孤零零一个人到底能撑多久！")
hide_all_stage_bubble()
situ:flip()
wait_twn(situ:jumpTo(1000, 600, 300, 3000), situ:jumpTo(1400, 75, 300, 3000), wanhecheng:jumpTo(1200, 75))
situ:say("谁说她是一个人的？")
hide_all_stage_bubble()
--战斗
local ret = start_preset_battle("万雀救难之战")
if ret == 1 then
else
end

zhuhuaner:say("你真是个喜欢管闲事的人……")
situ:say("小姑娘，你先退出谷中，我留下断后。")
zhuhuaner:setOverrideName("朱鹮儿")
zhuhuaner:say("今次……今次算我欠你的，我朱鹮儿可轻易不欠人情的！")
hide_all_stage_bubble()
zhuhuaner:offsetY(150)
zhuhuaner:flip()
wait_twn(zhuhuaner:movetoX(3000, 500))
situ:say("告辞了。")
hide_all_stage_bubble()
wait_twn(situ:jumpTo(1600, 600, 300, 3000), situ:jumpTo(1800, 2000, 300, 3000))
wanhecheng:say("来人！给我追——")

black_scene(0.25)
hide_stage()
set_flag("完成万雀救难")
light_scene(0.25)
