
show_stage("百草清涧.png", "百草清涧")
play_bgm("Music/密谋_夜郎.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local zhuhuaner = actor("朱鹮儿")
local laoyu = actor("[speaker:老妪][img:ai_old_female_2]")
local dingxuan = actor("丁宣")
local wanque1 = actor("[speaker:万雀溪谷弟子][img:pawn_WanQueXiGu_male_1]")
local wanque2 = actor("[speaker:万雀溪谷弟子][img:pawn_WanQueXiGu_male_2]")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-500, 75)
situ:face_right()
zhuhuaner:setOverrideName("？？？")
zhuhuaner:setPos(1100, 2000)
zhuhuaner:face_right()
laoyu:setPos(900, 75)
laoyu:face_right()
dingxuan:setPos(2500, 75)
dingxuan:face_left()
wanque1:setPos(600, 75)
wanque1:face_right()
wanque2:setPos(1400, 75)
wanque2:face_left()

laoyu:say("求求您，大爷，我的孩子无辜，请您高抬贵手！")
laoyu:flip()
laoyu:say("求求您！大爷！放了我家的孩子吧！")
wanque1:say("罗嗦什么！滚开！快滚开！")
wait_twn(dingxuan:movetoX(1700), dingxuan:daze())
laoyu:flip()
wanque2:flip()
dingxuan:say("你们还在磨蹭什么？连这点小事都处理不了，真是废物一群！")
wanque2:say("禀告天师，我们抓了些童男童女，但这老妪纠缠不清，却死死缠住我们不放！")
dingxuan:say("哼！没用的东西！")
hide_all_stage_bubble()
wait_twn(dingxuan:movetoX(1400), wanque2:jumpTo(1700, 75), wanque2:flip())
laoyu:say("求求您！大爷！还了我的孩儿吧……")
dingxuan:say("他娘的！少罗嗦！")
hide_all_stage_bubble()
wait_twn(dingxuan:jumpTo(1600, 600, 300, 3000), dingxuan:jumpTo(1100, 75, 300, 3000))
wait_twn(laoyu:offsetY(-100))
play_bgm("Music/决心_仗剑天涯.wav")
wait_twn(zhuhuaner:flip(), zhuhuaner:jumpTo(1800, 600, 300, 3000), zhuhuaner:flip(), zhuhuaner:jumpTo(1100, 75, 300, 3000), dingxuan:jumpTo(1300, 75))
zhuhuaner:say("住手！你们这群混账东西！")
dingxuan:say("大胆！你是什么人！竟敢插手万雀溪谷的事！")
zhuhuaner:say("路见不平，拔刀相助！有必要知道我是谁吗？")
dingxuan:say("反了！反了！你们几个，还愣着干嘛！还不赶快把她抓起来！")
wanque1:offsetX(100)
wanque2:offsetX(-100)
zhuhuaner:say("哼！就凭你们这几个人！")
hide_all_stage_bubble()
local options = {
  "路见不平，拔刀相助！",
  "冷眼旁观。"
}
local idx = show_quick_selections(options)
switch(idx) {
  ["1"] = function()
    wait_twn(situ:movetoX(700, 2500), wanque1:jumpTo(500, 75))
    zhuhuaner:flip()
    situ:say("小姑娘，我来助你一臂之力！")
    hide_all_stage_bubble()
    --战斗
    local ret = start_preset_battle("路见不平之战")
    if ret == 1 then
      wanque1:say("啊——我的妈呀！")
      wait_twn(wanque1:movetoY(-600, 5000), laoyu:offsetY(100))
      dingxuan:say("妈的，遇到硬茬！兄弟们快撤！")
      hide_all_stage_bubble()
      dingxuan:flip()
      wanque2:flip()
      dingxuan:movetoX(3000)
      wanque2:movetoX(3000)
      laoyu:flip()
      situ:say("此地不宜久留，老人家快回家去吧！")
      laoyu:say("少侠，求您救救我的孩子们。")
      situ:say("放心。你一有线索来虎焰堂找我。")
      hide_all_stage_bubble()
      laoyu:movetoX(-500)
      situ:say("小姑娘，你似乎受伤了。")
      zhuhuaner:say("走开！不用你多管闲事！")
      situ:say("我没别的意思，我只是想帮忙……")
      zhuhuaner:say("你们走开！我才不要你们帮忙，走开！")
      hide_all_stage_bubble()
      zhuhuaner:flip()
      wait_twn(zhuhuaner:movetoX(1500, 500), zhuhuaner:daze())
      situ:say("小姑娘，你的伤势……")
      zhuhuaner:movetoX(3000)
      set_flag("完成阻止丁宣抢劫少女")
    else
      wait_twn(situ:offsetY(-150), situ:daze())
      situ:emotion("BeiShang")
      situ:say("可恶！竟输给了这帮妖人！")
      situ:emotion()
      zhuhuaner:say("可恶！使得什么妖法？让我动弹不得！")
      dingxuan:say("无知小儿和无用老妇不要，把少女绑回去！")
      dingxuan:flip()
      wait_twn(dingxuan:offsetY(-60), dingxuan:offsetY(60, 300))
      wait_twn(zhuhuaner:jumpTo(1250, 130))
      dingxuan:say("我们快点走，不要耽误正事！")
      hide_all_stage_bubble()
      dingxuan:movetoX(3000)
      zhuhuaner:movetoX(3000)
      wanque2:movetoX(3000)
      wanque1:movetoX(3000)
      situ:say("站住！可恶！")
    end
  end,
  ["2"] = function()
    wait_twn(dingxuan:jumpTo(1600, 600, 300, 3000), dingxuan:jumpTo(1200, 75, 300, 3000))
    wait_twn(zhuhuaner:jumpTo(1000, -60))
    zhuhuaner:say("可恶！使得什么妖法？让我动弹不得！")
    dingxuan:say("把这嘴硬的少女绑回去！")
    dingxuan:flip()
    wait_twn(dingxuan:offsetY(-60), dingxuan:offsetY(60, 300))
    wait_twn(zhuhuaner:jumpTo(1100, 130))
    dingxuan:say("我们快点走，不要耽误正事！")
    hide_all_stage_bubble()
    dingxuan:movetoX(3000)
    zhuhuaner:movetoX(3000)
    wanque2:movetoX(3000)
    wait_twn(wanque1:movetoX(3000))
  end
}

hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成路见不平")
light_scene(0.25)
