show_stage("夜晚豪猪长垄.png", "豪猪长垄")
set_bg_mat("ImgPaperFold")
play_bgm("Music/豪猪恶贼.wav")
light_scene(0.2)

local hemeng = actor("何猛")
local panmazi = actor("潘麻子")
local liangsheng = actor("梁胜")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
hemeng:setPos(700, 75)
hemeng:face_right()
panmazi:setPos(2200, 75)
panmazi:face_left()
liangsheng:setPos(2400, 75)
liangsheng:face_left()

wait_twn(panmazi:movetoX(1000), liangsheng:movetoX(1200), liangsheng:daze())
hemeng:say("老二，老三，你们来了？")
panmazi:say("老大唤我们来，是有什么要紧事？")
liangsheng:say("有什么事情，老大尽管吩咐就是！")
hemeng:say("那个人，那个人出现了……")
panmazi:say("老大是说<color=red>威老大</color>？")
liangsheng:say("威老大？那不是老大的亲哥哥吗？当年一声不响便消失了，怎么如今终于有信儿了？")
hemeng:say("威老大并未出面，只是差人传令：“虎焰门必须铲除”。")
liangsheng:say("夜鸦就够麻烦的了，如今非但夜鸦查不出线索，还出现了个更大的麻烦。")
panmazi:say("威老大既然要我们动手，那他为何自己不出面？")
hemeng:say("威老大行事，向来神秘莫测，他此举恐怕是为了试探我们，也可能是为了在江湖上布局更大的棋局。")
liangsheng:say("既然命令下来了，我们就听命好了。横竖趁他病要他命，虎焰门那些家伙，早就该好好教训一顿了。")
hemeng:say("威老大既然发话了，要我们动手，不仅是虎焰门！便是与这事儿相关的，都不能留！")
hemeng:say("我们不仅要进攻虎焰门，还要做得干净利落，不给威老大留下话柄。")
panmazi:say("老大说得对，我们得做得漂亮，让威老大知道我哥几个的手段。")
hemeng:say("老三，你负责联络兄弟们，此事需谨慎，不可走漏风声。")
liangsheng:say("是！那我这便去发灭门令，凡豪猪长垄的兄弟，得令即到，不容迟误！")
hide_all_stage_bubble()
liangsheng:flip()
wait_twn(liangsheng:movetoX(3000))
hemeng:say("老二，你说咱们兄弟三个，怎么就……")
panmazi:say("老大，我感觉威老大的目的绝不会这么简单。")
hemeng:flip()
hemeng:say("我只怕是最后是卸磨杀驴，兔死狗烹啊！不行，还是得早些为咱们自己做些谋算。")

black_scene(0.25)
hide_stage()
set_flag("完成三猪齐聚")
light_scene(0.25)
