show_stage("夜晚豪猪长垄.png", "豪猪长垄")
set_bg_mat("ImgPaperFold")
play_bgm("Music/豪猪恶贼.wav")
light_scene(0.2)

local hemeng = actor("何猛")
local panmazi = actor("潘麻子")
local liangsheng = actor("梁胜")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
hemeng:setPos(700, 75)
hemeng:face_right()
panmazi:setPos(2200, 75)
panmazi:face_left()
liangsheng:setPos(2400, 75)
liangsheng:face_left()

wait_twn(panmazi:movetoX(1000), liangsheng:movetoX(1200), liangsheng:daze())
panmazi:say("老大！兄弟们都已经到齐了！")
liangsheng:say("是啊老大！就等你一句话了！")
hemeng:say("好！为了咱们豪猪长垄！不留余孽，斩尽杀绝！")
local diplomatic = require("Common/diplomatic")
local playerMenpai = get_player_menpai()
local targetMenpai = get_menpai_by_id("豪猪长垄")
diplomatic.declare_war(targetMenpai, playerMenpai)
panmazi:say("老大发话了！兄弟们！斩尽杀绝！")
liangsheng:say("斩尽杀绝！")
hide_all_stage_bubble()
wait_twn(hemeng:movetoX(3000), panmazi:flip(), panmazi:movetoX(3000), liangsheng:flip(), liangsheng:movetoX(3000))

black_scene(0.25)
hide_stage()
set_flag("完成不宣而战")
light_scene(0.25)
