show_stage("夜晚豪猪长垄.png", "豪猪长垄")
set_bg_mat("ImgPaperFold")
play_bgm("Music/豪猪恶贼.wav")
light_scene(0.2)

local hemeng = actor("何猛")
local panmazi = actor("潘麻子")
set_all_actors_mat("ImgPaperFold")

--初始化位置和朝向
dark_all_actors()
hemeng:setPos(700, 75)
hemeng:face_right()
panmazi:setPos(2500, 75)
panmazi:face_left()

wait_twn(panmazi:movetoX(1100), panmazi:daze())
wait_twn(panmazi:offsetY(-50))
panmazi:say("老、老大！老大！")
wait_twn(panmazi:offsetY(50))
hemeng:say("不就是去虎焰门找回场子，你怎么搞成这副德性？")
panmazi:shake()
panmazi:say("老大，大事不好了！")
hemeng:say("放肆！休得胡言！")
--（酌情呈现何猛向潘麻子攻击的画面效果）
hemeng:say("老子好得很！休要用你那乌鸦嘴乱咒！")
panmazi:shake()
panmazi:say("麻子该死！只是，虎焰门，虎焰门好像被灭了！")
hemeng:say("哦？这倒新鲜。(player:fname)雷夫妇不是一贯谨慎行事？怎会落得如此下场？")
panmazi:say("麻子所知有限，但是……")
hemeng:say("别啰嗦！有话快说！")
panmazi:say("老大，那虎焰门被屠的情景，与当年那件事如出一辙。")
hemeng:flip()
hemeng:say("当年？你是说……")
hemeng:flip()
hemeng:shake()
hemeng:say("不可能！那都多少年前的事了？再说虎焰门这些年来也没少结仇……")
panmazi:say("可那三道青焰焦痕，麻子看得清清楚楚！")
hemeng:say("当真？！")
panmazi:say("麻子怎敢欺瞒？原本按您的吩咐，带着得月楼那骚娘们去的时候，虎焰门已是残破不堪。")
panmazi:say("到了正堂，一眼就看到了那三道痕迹。当时怕惹火烧身，才没敢出声。")
hemeng:say("这么说确有点邪乎……")
panmazi:say("就不知虎焰门……")
hemeng:say("给老子闭嘴！虎焰门之事，若真是那人所为，下一个，下一个可别是我们……")
--（酌情呈现何猛攻击了一下潘麻子的效果）
panmazi:say("老大，咱们现在怎么办？")
hemeng:say("娘希匹的！这事儿八成是虎焰门那帮鸟人惹出来的！不过管他呢，现在当然有现在的要紧事。")
panmazi:say("老大的意思是？")
hemeng:say("不过是个半残的虎焰门，趁他病要他命，咱们得趁机搞事啊！")

wait_twn(hemeng:jump())

hemeng:say("小的门，都给老子躁起来！")
hemeng:say("先把虎焰门那边的宝贝搬空、钱财抢光、女人都拉回来当奴！")
hemeng:flip()
hemeng:say("对了，别忘了还有把那颗他们当宝贝什么鸟红叶子树也给砍了搬回来当柴烧！")

black_scene(0.25)
hide_stage()
set_flag("完成何猛登场")
light_scene(0.25)
