show_stage("bg_39.png", "窑洞")
light_scene(0.2)
play_bgm("Music/决心_仗剑天涯.wav")

local tangcaidie = actor("汤彩蝶")
local nvzi1 = actor("[speaker:金英][img:ai2_female_17]")
local nvzi2 = actor("[speaker:川药][img:ai2_female_15]")
local situ = actor("司徒来也")
local tangbainiu = actor("汤白牛")

--初始化位置和朝向
bright_all_actors()
tangcaidie:setPos(900, 75)
tangcaidie:face_right()
nvzi1:setPos(200, -500)
nvzi1:face_right()
nvzi2:setPos(0, -500)
nvzi2:face_right()
situ:setPos(1500, 2000)
situ:face_left()
tangbainiu:setPos(2500, 75)
tangbainiu:face_left()

--环视四周
for i = 1, 3 do
  wait_twn(tangcaidie:flip(0.2), tangcaidie:daze(), tangcaidie:say("姐妹们——"))
end

--一起跳出来
wait_twn(nvzi1:jumpTo(600, 75), nvzi2:jumpTo(400, 75), nvzi2:daze())

tangcaidie:say("姐妹们，今夜，我们将共谋大事。此事关乎我们生死存亡，绝不能有丝毫闪失。")
nvzi1:say("汤姐姐，我们皆已准备好，听从你的吩咐。只是，这豪猪长垄守卫森严，我们如何才能得手？")
tangcaidie:say("我已探得消息，豪猪长垄的守卫在子时最为松懈。我们便在那时动手，趁机潜入。")
nvzi2:say("可是，我们人数有限，如何应对众多守卫？")
tangcaidie:say("川药妹妹不必担心。我已给上次进攻豪猪长垄的侠士留下线索，期望他们来与我们汇合。")
tangcaidie:say("届时我们一起趁机潜入，刺杀豪猪长垄的首领。")
nvzi1:say("汤姐姐，你的计策果然高明。我们必定能够成功！")
hide_all_stage_bubble()
play_bgm("Music/抉择_一念之间.wav")
wait_twn(situ:flip(), situ:jumpTo(1800, 600, 300, 3000), situ:flip(), situ:jumpTo(1500, 75, 300, 3000))
wait_twn(tangbainiu:movetoX(1200, 2500), tangbainiu:daze())
tangbainiu:say("阿姊，你安然无恙，真是太好了！")
tangcaidie:flip()
tangcaidie:say("阿弟！真的是你！")
tangbainiu:say("阿姊，(player:fname)掌门带我前来，正是为了拯救被豪猪长垄掳去的女子。")
tangcaidie:say("(player:fname)掌门的大恩大德，汤彩蝶永志不忘。")
situ:say("汤神医言重了。豪猪长垄与我等本有深仇大恨，此次行动，义不容辞。")
tangcaidie:flip()
tangcaidie:say("现在，我们要分头行动。金英，你带领一部分姐妹负责制造混乱，分散守卫的注意力。川药，你潜入豪猪长垄内部，寻找被囚禁的女子。")
tangcaidie:say("(player:fname)掌门、阿弟，我们则直捣黄龙，一举摧毁豪猪长垄的老巢。")
hide_all_stage_bubble()
black_scene(0.25)
hide_stage()

show_stage("夜晚豪猪长垄.png", "夜晚豪猪长垄")
light_scene(0.2)
play_bgm("Music/决心_仗剑天涯.wav")

local hemeng = actor("何猛")
local panmazi = actor("潘麻子")
local liangsheng = actor("梁胜")
local tangcaidie = actor("汤彩蝶")
local tangbainiu = actor("汤白牛")
local situ = actor("司徒来也")

--初始化位置和朝向
bright_all_actors()
hemeng:setPos(900, 75)
hemeng:face_right()
panmazi:setPos(600, 75)
panmazi:face_right()
liangsheng:setPos(300, 75)
liangsheng:face_right()
tangcaidie:setPos(2300, 75)
tangcaidie:face_left()
tangbainiu:setPos(2600, 75)
tangbainiu:face_left()
situ:setPos(2900, 75)
situ:face_left()

tangcaidie:movetoX(1200)
tangbainiu:movetoX(1500)
wait_twn(situ:movetoX(1800), situ:daze())

tangcaidie:say("何猛！潘麻子！梁胜！今日我就要为姐妹们讨回公道！")
hemeng:say("彩蝶仙子，我本想让你为我兄弟疗伤，奉你为座上宾。哪知你却勾结虎焰门，意图灭我豪猪长垄！")
liangsheng:say("你丫的，什么狗屁彩蝶仙子！当时在选妃桥老子就该把你扔河里去！")
situ:say("何猛！今日我就要用你的血来洗刷你犯下的罪恶！")
hide_all_stage_bubble()
local ret = start_preset_battle("夜刺豪猪之战")
if ret == 1 then
  hemeng:say("二弟，三弟，你们快走！豪猪长垄的事我一人担着。")
  liangsheng:say("老大，做兄弟的，有今生没来世！")
  panmazi:say("走！留着青山在，不怕没柴烧！")
  liangsheng:flip()
  liangsheng:movetoX(-500)
  panmazi:flip()
  wait_twn(panmazi:movetoX(-500))
  situ:say("多行不义必自毙，何猛，你的末日到了！")
  hemeng:say("哈哈哈！能拖这么多人下地府，我也不算白来江湖一场！")
  hide_all_stage_bubble()
  hemeng:offsetY(-300)
  occupy_menpai("虎焰门", "豪猪长垄")
  set_flag("完成灭亡豪猪长垄")
  set_flag("完成斩杀何猛")
  destroy_menpai("豪猪长垄")
  black_scene(0.25)
  hide_stage()
  set_flag("完成夜刺豪猪")
  light_scene(0.25)
else
  tangbainiu:say("掌门，我们被围困于此，恐难生还。")
  hemeng:say("虎焰门，也不过如此！今日，你们的火焰将被我豪猪长垄彻底熄灭！")
  situ:say("可恶…就这么…结束了吗。")
  situ:say("天要灭我虎焰门，我(player:fullname)不怕死，只是爹……娘……孩儿去了那边，又有什么脸面相聚啊！（拔剑自刎）")
  situ:offsetY(-300)
  black_scene(0.25)
  hide_stage()
  game_over()
end
