show_stage("夜晚豪猪长垄.png", "豪猪长垄")
light_scene(0.2)
play_bgm("Music/豪猪恶贼.wav")

local hemeng = actor("何猛")
local panmazi = actor("潘麻子")
local situ = actor("司徒来也")

--初始化位置和朝向
bright_all_actors()
hemeng:setPos(700, 75)
hemeng:face_right()
panmazi:setPos(1000, 75)
panmazi:face_left()
situ:setPos(2200, 75)
situ:face_left()

panmazi:say("老大，你看这次找的小娘子是你想要的不？")
hemeng:say("辛苦你搜罗了这么多姑娘来……只是我与你说的样貌形容，哪点对上了？")
panmazi:say("这山野乡间，寻这样的货色也算难得了，眼光也忒高了些……")
hemeng:say("呸！我找人可是另有打算！谁像你脑子里只想着那点事儿？")
panmazi:say("谁还不是为了那点事儿？成！老大要的人，便是翻遍了这息风谷，也定搜出来！")
hemeng:say("外面什么声音？")
panmazi:say("好像是虎焰门的人？")
panmazi:flip()
wait_twn(situ:movetoX(1400), situ:daze())
situ:say("何猛，快把你掠上来的姑娘都给放了！")
hemeng:say("是你小子？我三弟梁胜一只眼睛的仇还没同你算，倒是自己跑上来了？")
situ:say("我来豪猪长垄只取三样东西：梁毒眼儿的招子，潘麻子的狗命，你何猛的黑心！")
hemeng:say("放肆！我豪猪之王的地盘可容是你叫嚣的？")
situ:say("何猛！倒要见识见识你的手段！")

hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag_int("攻打豪猪长垄阵型", 2)
set_flag("完成已占据豪猪长垄一个据点")
light_scene(0.25)
