show_stage("夜晚豪猪长垄.png", "豪猪长垄")
light_scene(0.2)
play_bgm("Music/豪猪恶贼.wav")

local tangcaidie = actor("汤彩蝶")
local hemeng = actor("何猛")
local panmazi = actor("潘麻子")
local liangsheng = actor("梁胜")
local situ = actor("司徒来也")

--初始化位置和朝向
bright_all_actors()
hemeng:setPos(800, 75)
hemeng:face_right()
panmazi:setPos(500, 75)
panmazi:face_right()
liangsheng:setPos(300, 75)
liangsheng:face_right()
tangcaidie:setPos(1400, 75)
tangcaidie:face_left()
situ:setPos(2400, 75)
situ:face_left()

tangcaidie:say("放开我！")
panmazi:say("好好好！可就算放了你，你又能跑到哪儿去？")
hemeng:say("听说息风谷出了个专门除蠹医病的彩蝶仙子，就是你吧？")
tangcaidie:say("……")
hemeng:say("我这个兄弟被伤了一只眼睛，不知大夫妙手，能不能治好这伤势呢？")
tangcaidie:say("呸！那都是为恶的报应，我若治了，岂不是逆天而行？")
liangsheng:say("你丫的，什么狗屁彩蝶仙子！当时在选妃桥老子就该把你扔河里去！")
hemeng:say("三弟莫急。人家大夫，又是女子，得以礼相待。你且好好说说，自然就能治了不是？")
liangsheng:say("大哥这文绉绉的，我可做不来。")
tangcaidie:say("……")
panmazi:say("哈哈哈哈，三弟，这大夫青春美貌又如此手段。怎么想，你可都不亏啊。")
hemeng:say("外面什么声音？")
panmazi:say("好像是虎焰门的人。")
hemeng:say("又是虎焰门。")
wait_twn(situ:movetoX(1200), situ:daze())
situ:say("野山猪们！来做个了结吧！")

hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag_int("攻打豪猪长垄阵型", 3)
set_flag("完成攻打豪猪长垄最后一个据点")
light_scene(0.25)
