show_stage("夜晚豪猪长垄.png", "豪猪长垄")
light_scene(0.2)
play_bgm("Music/豪猪恶贼.wav")

local hemeng = actor("何猛")
local situ = actor("司徒来也")

--初始化位置和朝向
bright_all_actors()
hemeng:setPos(800, 75)
hemeng:face_right()
situ:setPos(2400, 75)
situ:face_left()

wait_twn(situ:offsetX(-1200), situ:daze())
situ:say("何猛，我且问你一事。")
hemeng:say("你这是在试探我吗？")
situ:say("江湖传言，虎焰门那场惊天大火，乃是夜鸦所为。这夜鸦神秘莫测，究竟是人是鬼，你可知道？")
hemeng:say("夜鸦是人是鬼，我亦好奇。只可惜他似乎不近女色，否则定会先来我豪猪长垄一睹佳人风采。")
situ:say("你还有心思谈笑风生，那些被你残害的女子，你又该如何交代？")
hemeng:say("我日御五女，你且算算，我何猛究竟祸害了多少无辜？")
situ:say("难怪附近的女子闻“豪猪”之名便心惊胆战，你果然是个恶魔！")
hemeng:say("恶魔之称，我何猛担当得起。")
situ:say("你就此在这里等死吧！")
hemeng:say("恶魔又何尝不想做个普通人。")
situ:say("你……")
hemeng:say("你可曾体会过，精神和肉体被压迫至极致的感觉？")
situ:say("你就是这样折磨人的？")
hemeng:say("我自幼便受此折辱，日复一日。")
situ:say("谁？")
hemeng:say("养育我、折磨我至极之人，正是我的兄长——何威。")
situ:say("这兄弟之情，当真诡异。")
hemeng:say("在那黑暗里，脸紧贴着肮脏的墙，脸上流下来的液体，你不知道它是汗还是血，滴到脚背上，你也没有用手去擦拭的机会，只有无尽的绝望和窒息。")
situ:say("……")
hemeng:say("或许，从那时起，我心中便种下了恶魔的种子。")
situ:say("你那兄长，如今在何处？")
hemeng:say("若他还活着，我定要找到他，亲自了结这段恩怨！")

hide_all_stage_bubble()

pop_tip("解锁副本：豪猪寨")

black_scene(0.25)
hide_stage()
set_flag("完成豪猪王的回忆")
light_scene(0.25)
