show_stage("酒香亭.png", "酒家")
play_bgm("Music/回忆.wav")
set_bg_mat("ImgPaperFold")
light_scene(0.2)

local cnt = get_flag_int("豪猪破坏酒香亭次数")

local lai3 = actor("赖三")
lai3:face_left()
lai3:setPos(3000, 75)

if cnt < 2 then
    local haozhu1 = actor("豪猪长垄弟子")
    local haozhu2 = actor("豪猪长垄弟子二")

    set_all_actors_mat("ImgPaperFold")

    dark_all_actors()
    haozhu1:setOverrideName("豪猪长垄弟子")
    haozhu2:setOverrideName("豪猪长垄弟子")
    haozhu1:setPos(700, 75)
    haozhu1:face_right()
    haozhu2:setPos(1000, 75)
    haozhu2:face_right()

    wait_twn(lai3:movetoX(1300), lai3:offsetY(-50))
    if cnt == 0 then
        lai3:say("两位大爷，这一路风尘仆仆，定是辛苦了。我们酒香亭虽小，却也有上好的佳酿，不知能否为两位解解乏？")
        haozhu1:say("少他娘的废话，快把你们最好的酒拿出来，今儿个我们哥俩儿要喝他个痛快！")
        haozhu2:say("对，赶紧把酒端上来，别他娘的拿些猫尿来应付老子们！")
        lai3:say("是是是，喝酒就得喝个痛痛快快。我这就去拿，两位稍等片刻。")
        hide_all_stage_bubble()
        lai3:offsetY(50)
        lai3:flip()
        wait_twn(lai3:movetoX(3000))
        haozhu1:say("这小子，还算识相。")
        haozhu2:say("嗯，比那些一见到咱们就尿裤子的人强多了。")
        lai3:flip()
        wait_twn(lai3:movetoX(1300))
        lai3:say("两位大爷，这酒香亭虽小，可也是江湖中人的聚集地。两位要是能在这喝个开心，那也是给我们酒香亭长脸了。")
        haozhu1:say("你这家伙，嘴还挺甜。今儿个就给你这个面子，以后这酒香亭就是我们哥俩儿的歇脚处了，你可得好好招待。")
        lai3:say("那是当然，有两位大爷的光临，我们酒香亭的生意想不火都难。")
        haozhu2:say("你小子聪明，知道怎么做人。但要是敢在背后搞鬼，这酒香亭就不用开了。")
        lai3:say("两位放心，我赖三别的不会，伺候人的本事还是有的。只要两位大爷高兴，我这酒香亭就是两位的第二个家，绝不敢有半点差池。")
    elseif cnt == 1 then
        haozhu1:say("小子，把你们最烈的酒给爷们儿拿出来，今儿个我们哥俩儿要喝他个天翻地覆！")
        haozhu2:say("对，赶紧把酒端上来，别他娘的拿些兑水的货色来应付爷们儿！")
        lai3:say("大爷说的是，喝酒就得喝个痛痛快快。我这就去拿，两位大爷稍等片刻。")
        hide_all_stage_bubble()
        lai3:offsetY(50)
        lai3:flip()
        wait_twn(lai3:movetoX(3000))
        haozhu1:say("这小子，还挺机灵，挺对爷们的胃口。")
        haozhu2:say("咱们在酒香亭的日子，可得过得舒舒服服的，不能亏待了自己。")
        lai3:flip()
        wait_twn(lai3:movetoX(1300))
        lai3:say("大爷们，只要你们在酒香亭喝得开心，我赖三就算没白忙活。")
        haozhu1:say("你小子，哈哈哈，有两下子，不错，不错。")
        haozhu2:say("哈哈哈，你这小子，嘴皮子挺利索，挺会来事儿。")
    end
else
    local liangsheng = actor("梁胜")
    local dizi = actor("豪猪长垄弟子")
    local situ = actor("司徒来也")

    set_all_actors_mat("ImgPaperFold")

    dark_all_actors()
    liangsheng:setPos(700, 75)
    liangsheng:face_right()
    dizi:setPos(400, 75)
    dizi:face_right()
    situ:setPos(-500, 75)
    situ:face_right()

    wait_twn(lai3:movetoX(1300), lai3:daze())
    lai3:say("大爷，有什么需要小的服务的？")
    liangsheng:say("小的们，把酒香亭这个酒家烧了！把所有人全部赶到豪猪长垄！")
    lai3:say("大爷，小的这地儿只是个喝酒打尖的小地方，不敢劳烦动这么大干戈。")
    liangsheng:say("怪就怪你在酒香亭这个地方。快，小的们，行动起来！")
    lai3:say("妖魔鬼怪受死吧！看我“降魔掌”！")
    hide_all_stage_bubble()
    wait_twn(lai3:jumpTo(1300, 600, 300, 3000), lai3:jumpTo(800, 75, 300, 3000))
    dizi:jumpTo(300, -60)
    wait_twn(liangsheng:jumpTo(600, -60), liangsheng:daze())
    liangsheng:say("想不到，在小小的酒香亭还隐藏着绝世高手……")
    liangsheng:say("快撤！")
    hide_all_stage_bubble()
    liangsheng:movetoX(3000)
    wait_twn(dizi:movetoX(3000))
    wait_twn(situ:movetoX(500), situ:daze())
    situ:say("赖三兄，好身手！")
    lai3:say("(player:fname)掌门，见笑了！我这身武功是在探宝时寻到一本秘籍《降魔袈裟掌》修炼的。")
    situ:say("赖三兄竟有此奇遇。")
    lai3:say("我便将《降魔袈裟掌》交予掌门，希望你能早点收复酒香亭，让百姓安居乐业！")
    situ:say("多谢赖三兄好意！")

    add_player_item("降魔袈裟掌", 1)
    set_flag("豪猪停止破坏酒香亭")
end

set_flag_int("豪猪破坏酒香亭次数", cnt + 1)

black_scene(0.25)
hide_stage()
light_scene(0.25)