show_stage("bg_226.png", "灵猹仙洞")
play_bgm("Music/日常_烟火人间.wav", 0.1)
light_scene(0.2)

local xiada = actor("夏大")
local xiaer = actor("夏二")
local xiasan = actor("夏三")
local xiasi = actor("夏四")
local xiawu = actor("夏五")
local xialiu = actor("夏六")

--初始化位置和朝向
bright_all_actors()

xiada:setPos(200, 75)
xiada:face_right()
xiaer:setPos(500, 75)
xiaer:face_left()
xiasan:setPos(800, 75)
xiasan:face_left()
xiasi:setPos(1100, 75)
xiasi:face_left()
xiawu:setPos(1400, 75)
xiawu:face_left()
xialiu:setPos(1700, 75)
xialiu:face_left()

xiada:say("诸位兄弟，今日我们以石马吊决胜负，胜者将获得我珍藏多年的绝世秘籍一份！")
xiasan:say("老大，这秘籍可是你一直不肯示人的那本？")
xiasi:say("老大，你这秘籍可别是哄我们玩的。")
xiawu:say("秘籍不秘籍的我不在乎，我最关心的是，谁能赢得这次比选。")
xialiu:say("老大，石马吊我可是行家，这秘籍我拿定了！")
xiada:say("规则很简单，谁先胡牌，谁就是胜者。不过，我们这次比的不仅是牌技，还有智谋。")
xiaer:flip()
xiaer:say("今天这场比选，我夏二也作为裁判，保证比赛的公平公正。不过，我得提醒你们，别以为我不知道你们那些小动作。")
stage_narration("比赛开始，四怪围坐在石桌旁，夏大和夏二则站在一旁，作为裁判监督比赛。")
stage_narration("比赛进行得如火如荼，夏三的沉稳让他总能在关键时刻出其不意；夏四的油滑让他总能巧妙地换牌，让人捉摸不透。")
xialiu:say("这石马吊怎么就这么难呢？我明明记得上次赢了的。")
xiawu:say("夏六，你的记性可真差，上次是我让你赢的。")
xiasi:say("夏五，别太得意，我这手牌可是天胡的料。")
stage_narration("随着比赛的进行，局势逐渐明朗。夏三和夏四的牌技不相上下，夏五虽然自认牌技了得，却总是因为一些小失误而落后；夏六的自作聪明让他总能猜到对手的牌路。")
xiada:say("等等，我突然想起来，这秘籍其实……是假的。")
xiasan:say("老大，你这玩笑开得太大了。")
xiasi:say("我就说嘛，老大怎么可能这么轻易就把秘籍拿出来。")
xiawu:flip()
xiawu:say("哈哈，夏六，看来你的胜算又没了。")
xialiu:say("我……我这是被耍了？")
xiaer:say("今天咱们玩得开心，这才是最重要的。")

hide_all_stage_bubble()

black_scene(0.25)
hide_stage()
set_flag("完成内部角逐")
light_scene(0.25)
