
show_stage("bg_226.png", "灵猹仙洞")
play_bgm("Music/日常_烟火人间.wav", 0.1)
light_scene(0.2)

local xiada = actor("夏大")
local xiaer = actor("夏二")
local xiasan = actor("夏三")
local xiawu = actor("夏五")
local xialiu = actor("夏六")

--初始化位置和朝向
bright_all_actors()

xiada:setPos(800, 75)
xiada:face_right()
xiaer:setPos(500, 75)
xiaer:face_right()
xiasan:setPos(-500, 75)
xiasan:face_right()
xiawu:setPos(1100, 75)
xiawu:face_left()
xialiu:setPos(1400, 75)
xialiu:face_left()

xialiu:say("开门！")
xiawu:flip()
xiawu:say("阿驾是阿驾，阿架却非阿驾。")
xialiu:say("阿架虽非阿驾，但阿驾始终是阿驾。")
play_sfx("Story/OpenDoor.mp3")
xiawu:say("这回你总算是记住了咱们的切口。")
xialiu:say("老大这切口，当真是独树一帜，令人难以忘怀。")
xiada:say("夏六，你在那儿嘀咕什么？可有什么要紧的消息？")
xiawu:flip()
xialiu:say("回禀老大，有重大消息！")
xiada:say("何重大消息？")
xialiu:say("那虎焰门虽遭夜鸦毒手，却未彻底覆灭。(player:fname)雷之子，(player:fullname)，尚在人间。")
xiaer:say("不是都说虎焰门已被烧成灰烬了吗？")
xialiu:say("灰烬之中，仍有生机。(player:fullname)带领残余弟子，正在重建门派，而且似乎给临帮带来了不少麻烦。")
xiada:say("(player:fullname)，果然非同小可。")
xiaer:say("那(player:fullname)对我灵猹仙洞若有敌意，只怕他一旦站稳脚跟，便会对我等不利。")
xiada:flip()
xiada:say("老二，速将所有石子和牛皮布取来，再将老三请来！")
xiaer:flip()
wait_twn(xiaer:movetoX(-500))
xialiu:say("这是要做何事？难道老大要在沙盘上布下奇谋？")
xiawu:say("你且看着便是。")
wait_twn(xiasan:movetoX(500), xiasan:daze())
xiasan:say("老大，有何吩咐？")
xiada:say("你们几个，按位坐下。老五、老六，你们在一旁观摩。")
xialiu:say("是！")
xiada:say("上次我赢了，这次我先来。")
xiasan:say("那你便掷骰子吧。")
xiada:say("在这紧张的局势下，不手谈几局，真是难以舒缓心情。")
hide_all_stage_bubble()
unlock_menpai("灵猹仙洞", true)

black_scene(0.25)
hide_stage()
set_flag("完成灵猹仙洞登场")
light_scene(0.25)
