
show_stage("bg_192.png", "虎焰堂")
play_bgm("Music/日常_烟火人间.wav", 0.1)
light_scene(0.2)

local xiasan = actor("夏三")
local situ = actor("司徒来也")
local liuming = actor("刘明")

--初始化位置和朝向
bright_all_actors()

xiasan:setPos(100, 75)
xiasan:face_right()
liuming:setPos(1200, 75)
liuming:face_right()
situ:setPos(1500, 75)
situ:face_left()


liuming:say("掌门，外面有个丑陋不堪的汉子，自称有要事求见。")
wait_twn(xiasan:jumpTo(900, 75), xiasan:daze())
xiasan:say("你这秃头，中午吃了驴粪吗？说话这么难听。")
liuming:flip()
situ:say("请问阁下是？")
xiasan:say("你小时候见过我，我是灵猹仙洞的夏三，你三叔啊。")
situ:say("（心中暗想）灵猹仙洞多年前还是虎焰门的领地，这灵猹六怪仗着与(player:fname)家族有交情，硬是将此洞占为己有，还时常骚扰虎焰门，现在居然好意思说是最友好的邻邦。")
liuming:say("(player:fname)一族世代英俊，我可不记得掌门有你这么个丑叔叔。")
xiasan:say("你这臭嘴火工，别插嘴，我可是来拯救虎焰门的。")
situ:say("我虎焰门为何要你来拯救呢？")
xiasan:say("(player:fname)公子，虎焰门这么打下去不行啊，已经成为众矢之的了。")
situ:say("既然前辈说是虎焰门的友好领邦，如果前辈能来帮忙抗敌，那(player:fullname)一定千恩万谢。")
xiasan:say("你三叔此次来访，正是有此意啊。")
situ:say("（心中暗想）灵猹六怪有这么好？")
xiasan:say("只是看你说的这千恩万谢，是多少千，多少万了。")
situ:say("前辈何意？")
xiasan:say("虎焰门现在最缺的就是人，而我灵猹仙洞个个都是精英，这人嘛，也不是白给的，越是善战的勇士越是要精粮美酒养活啊，你说是不是。")
liuming:say("说了半天，不是白帮忙啊，还得收钱是吧，我就说灵猹洞什么时候这么仗义了。")
xiasan:say("虎焰门(player:fname)雷老爷子，留了那么多金银珍宝，我灵猹六仙不来偷不来抢。")
xiasan:say("还主动伸出援手来救你们于危难之际，这份泼天的大仁大义，难道不值得那实实在在能抓在手上的千恩万谢吗？你说呢，(player:fname)公子？")
situ:say("虎焰门危也罢，难也罢，我(player:fullname)都会挺过去，你请回吧。")
xiasan:say("哟！这骨气！这真是和那(player:fname)雷是一模一样。")
liuming:say("你走吧，走吧，贪财的家伙。")
xiasan:say("(player:fname)公子，三叔俺欣赏你，但如果确有需求，可以到灵猹仙洞来找我，不过别忘了带上实实在在的东西噢！")
liuming:say("滚滚滚。")
hide_all_stage_bubble()
xiasan:jump()
xiasan:flip()
wait_twn(xiasan:movetoX(-500))

black_scene(0.25)
hide_stage()
set_flag("完成灵猹自荐")
light_scene(0.25)
