show_stage("禁地.png", "禁地")
play_bgm("Music/密谋_夜郎.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local zhuhuaner = actor("朱鹮儿")
local wanhecheng = actor("万壑成")
local dingxuan = actor("丁宣")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-500, 75)
situ:face_right()
zhuhuaner:setPos(-800, 75)
zhuhuaner:face_right()
wanhecheng:setPos(1300, -500)
wanhecheng:face_left()
dingxuan:setPos(1600, -500)
dingxuan:face_left()

situ:movetoX(700)
wait_twn(zhuhuaner:movetoX(400), zhuhuaner:daze())
zhuhuaner:say("小(player:gname)，看那墙上就是“血色魔阵”了，我们快去破坏阵眼。")
--一起跳出来
wait_twn(wanhecheng:jumpTo(1000, 75), dingxuan:jumpTo(1300, 75), dingxuan:daze())
dingxuan:say("我便算出你们的目的是风水血阵！本天师早就在此等候多时了！")
zhuhuaner:say("本想先破坏了血阵再去清算，想不到你们竟先送上门来了！")
wanhecheng:say("臭丫头！这风水血阵可是万雀溪谷的多年大计，又怎么会容许你来捣乱？")
wanhecheng:say("待我万雀溪谷一统江湖之时，或许会看在今日你们懂事的份上，放你们一马。")
situ:say("呸！你这人神神叨叨，话语竟也这般颠三倒四！这样的歪门邪道，还妄想称霸武林？简直春秋大梦！")
dingxuan:say("自不量力……既是要送死，那便来试试吧！今天便用你们来祭我这血阵！诸神诸魔，各安各方！起阵！")
hide_all_stage_bubble()
local ret = dungeon_battle("血色魔阵", "禁地之战")
if ret == 1 then
    situ:say("鹮儿姑娘，趁现在，我挡住他们，你快搭弓射箭，直插阵眼。")
    zhuhuaner:say("好计策！")
    stage_narration("朱鹮儿凝神聚气，一支箭离弦而出。“咚！！”，那箭直中阵眼处，发出一声巨响。")
    wanhecheng:offsetY(-150)
    dingxuan:say("不、不可能！竟然破了我的血阵！")
    situ:say("多行不义必自毙！如今便是你的报应！")
    role_remove_affix("万壑成", "血色魔阵")
    pop_tip(string.i18_format("万壑成受到{0}反噬，功力大减！", affix_tip_link("血色魔阵", "血色魔阵", "#FF7A00")))
    black_scene()
    hide_stage()
    set_flag("完成禁地")
    set_flag("完成血色魔阵")
    light_scene()
    dungeon_success("血色魔阵")
else
    hide_stage()
    dungeon_fail("血色魔阵")
end
