show_stage("华丽府内.png", "鹤岭门")
play_bgm("Music/回忆.wav", 0.1)
light_scene(0.2)

local ximenpo = actor("西门坡")
local ximenting = actor("西门霆")
local ximenxiang = actor("西门香")
local situ = actor("司徒来也")

local is_dead = get_role_by_id("西门香").IsDead

--初始化位置和朝向
dark_all_actors()
ximenpo:setPos(800, 75)
ximenpo:face_right()
ximenting:setPos(400, 75)
ximenting:face_right()
if not is_dead then
  ximenxiang:setPos(2500, 75)
  ximenxiang:face_left()
else
  ximenxiang:hide()
end
situ:setPos(2800, 75)
situ:face_left()

if not is_dead then
  ximenxiang:movetoX(1200)
  wait_twn(situ:movetoX(1500), situ:daze())
else
  wait_twn(situ:movetoX(1200), situ:daze())
end


if not is_dead then
  ximenpo:say("想我西门坡汲汲营营，亲人挚爱都能舍弃，竟没想到是这样的结局……")
  ximenxiang:say("够了！这么多年，真当我什么都不知道吗！")
  ximenpo:say("可你明知道，却也什么也没说，不是吗？")
  situ:say("怎么仿佛在说哑谜一般？")
  ximenxiang:say("这原本是西门家的私事，是关于我娘的……")
  ximenting:say("姐姐，你说什么……我娘的事？爹，到底怎么回事？")
  ximenting:say("难道我们一直以为的幸福家庭，其实只是假象吗？")
  ximenpo:say("哼！我西门坡既然做了，便从没想过隐瞒！当年为博得前任掌门赏识，不惜断情绝爱、不顾危险爬雪山寻千年人参。")
  ximenpo:say("能从一个小喽啰翻身成为一门之主，如今却落得如此下场，可悲！可笑！")
  ximenxiang:say("父亲！可曾想过娘亲她是无辜的啊！她只是深爱她的夫君，却没想到，她的夫君竟只将她当做一枚棋子！")
  ximenpo:say("你同你娘一样优柔寡断，成不得大事！当年若不是只有她能寻得到千年雪参……")
  ximenting:say("父亲，姐姐，请不要这样争吵，我们难道不能坐下来好好谈谈吗？")
  ximenpo:say("若不是遇到狼群围困，我又何必如此决绝？她不过是为了西门家牺牲而已，也算死得其所了。")
  ximenxiang:say("可这么多年来，每每与人提及此事，却只提自己幸得神秘高人相救才逃得性命，对于娘亲之死却只字不言！")
  ximenxiang:say("父亲，娘亲的性命在你眼中，当真就如此轻贱吗？")
  ximenting:say("爹，娘亲的死是有什么误会吗？")
  ximenpo:say("当年如果不是为了带出好不容易采到的雪参，兴许还能想到些办法救她一命。只是可惜，是她没那个福分。")
  ximenxiang:say("只怕那并非是想要保护雪参，而只是在保护你的地位，保护你即将如愿以偿的荣誉吧？")
  ximenpo:say("或许如此吧，可这有什么错？")
  ximenpo:say("我后来与韩、赵二位长老辛苦钻研武学，力助鹤岭门门派兴旺，这不也是想要对得起你娘亲的牺牲？")
  ximenxiang:say("对得起娘亲？那不过是一个伪君子常提的、冠冕堂皇的理由罢了。")
  ximenpo:say("哼，那与虎焰门交好，与龙湾门交涉，将鹤岭门发扬光大，甚至将一对儿女托付给最信任的人，确保鹤岭门能够后继有人。我做这些，难道也是伪君子？")
  ximenxiang:say("强词夺理……")
  ximenpo:say("呵呵，强词夺理？我的亲生女儿，竟如此顶撞她的父亲？")
  ximenxiang:say("父亲？你当真还当我是女儿吗？在你的眼里，任何人都是你扩充版图的棋子，被权力蒙蔽了双眼，你可曾用一丝一毫的余光看向我们？")
  ximenpo:say("你怎么能如此绝情？难道……你当真认为我做这一切，真的错了？")
  ximenxiang:say("不，你这不是错了，是失去一切之后怕了。如同当年，权力与母亲之中，你从未想过将天平偏向母亲这边。")
  ximenxiang:say("不要再去找那些自欺欺人的借口了，骗了别人，或许只是你的手段，可连自己也骗了，那才当真可悲！")
  ximenpo:say("自欺……欺人？难道我西门坡这些年的所做作为，当真是自欺欺人？")
  situ:say("西门门主，我们虎焰门绝非赶尽杀绝的匪类。不若门主与西门小姐一道留在虎焰门，来日方长，慢慢想清楚当年的是非可是好的。")
  ximenpo:say("哼！你小子口气倒不小！当我西门坡是什么人？与其日日在你虎焰门苟活，我宁愿远上雪山！当年之举是对是错，若我那亡妻在天有灵，她自会回应我的！")
  ximenting:say("爹！不要啊！我们还有挽回的余地，不要放弃我们这个家！我陪着你上雪山。")
  pop_tip("<color=#ff7a00>西门坡</color>和<color=#ff7a00>西门霆</color>归隐雪山")
  play_sfx("Tip/Tip1.wav")
else
  ximenpo:say("想我西门坡汲汲营营，竟没想到是这样的结局……")
  situ:say("可你舍弃了深爱你的亲人，早就深陷在权力的泥淖之中了！")
  ximenpo:say("哼！做大事何必在意小节？你可知当年为博得前任掌门赏识，不惜断情绝爱、不顾危险爬雪山寻千年人参！")
  ximenpo:say("我西门坡从一个小喽啰翻身成为一门之主。难道靠得是儿女情长？")
  situ:say("可曾想过香儿她是无辜的啊！谁能想到她的生身父亲竟只将她视作一枚棋子！")
  ximenpo:say("香儿？她同她娘一样！成事不足败事有余！")
  ximenting:say("爹，你说什么……我娘的事？到底怎么回事？")
  situ:say("那可是你女儿啊！")
  ximenpo:say("那又如何？当年若不是只有我那亡妻能寻得到千年雪参……")
  ximenpo:say("若不是遇到狼群围困，我又何必如此决绝？我那亡妻也好，如今的香儿也罢，为了西门家牺牲，也算死得其所了。")
  situ:say("西门门主，人的性命在你眼中，当真就如此轻贱吗？")
  ximenpo:say("轻贱？或许吧。可不入虎穴不得虎子？我若非得到一位神秘高人相救才逃得性命，怕是也要同我那亡妻一般，葬身雪山之中了。")
  ximenpo:say("怪只能怪她福薄短命，不顾自己也要护住那些雪参。")
  situ:say("我想尊夫人当年并非是想要保护雪参，而只是在保护你的地位，却没想成全的竟是你对权力的痴迷！")
  ximenpo:say("或许如此吧，可这有什么错？")
  ximenpo:say("我后来与韩、赵二位长老辛苦钻研武学，力助鹤岭门门派兴旺，这不也是想要对得起亡妻的牺牲？")
  situ:say("那不过是一个伪君子常提的、冠冕堂皇的理由罢了，又何必说得天花乱坠？")
  ximenpo:say("哼，那与虎焰门交好，与龙湾门交涉，将鹤岭门发扬光大，甚至将一对儿女托付给最信任的人，确保鹤岭门能够后继有人。我做这些，难道也是伪君子？")
  situ:say("不过是强词夺理罢了。在你眼中，既然权力大过世间的一切，那便要承担痴迷权力所带来的恶果！")
  ximenpo:say("恶果？我苦心经营的一切，竟是这样的恶果？")
  situ:say("你把亲人们当做扩充版图的棋子时，就应当想到这样的结局。就如同当年，你可曾在妻子与权利之间动摇过？如果你还心存良知，你的妻子又怎会尸骨无存？")
  ximenpo:say("哈哈哈！可笑！你这小子懂什么！我鹤岭门可是息风谷之主，才是我西门坡存在的意义！便是孤家寡人又如何？拥有着滔天的权势便什么都有了！哈哈哈！")
  situ:say("胡言乱语！一味沉迷权势，只怕会丢了一切，只落得家破人亡的下场！")
  ximenpo:say("家破人亡？不！你懂什么！我那发妻，还有香儿！她们不都在这里吗！你看！她们都在那边等我过去呢！你看！就在那边！")
  play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
  wait_twn(ximenpo:movetoX(1200, 4000), situ:jumpTo(1500, 75), ximenpo:offsetX(-300, 4000), ximenpo:daze())
  situ:say("西门门主？！用这以命换命的招式，这、这又是何必呢？")
  ximenpo:say("小子，能躲开我这一招算你走运，不过这世间除了我自己，还没人能取走我西门坡的性命，如今你虎焰门也不行！终是我赢了，哈哈哈——")
  ximenting:say("爹——")
  play_sfx("Skills/Wuxia/TY_JianXue1.mp3")
  ximenpo:rotatetoZ(-90)
  wait_twn(ximenpo:offsetY(-100))
  kill_disciple("西门坡")
  ximenting:say("为什么会这样……我们本可以避免这一切的……")
  situ:say("罢了，竟到死也这般痴迷，当真无药可救！只是香儿啊，如今因果终结，你在天之灵或许也能瞑目了吧……")
  ximenting:say("如今家破人亡，我该何去何从？")
  pop_tip("<color=#ff7a00>西门霆</color>归隐雪山")
  play_sfx("Tip/Tip1.wav")
end

destroy_menpai("鹤岭门")

hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成鹤岭门灭亡结局")
light_scene(0.25)
