show_stage("bg_219.png", "虎焰堂")
play_bgm("Music/舒缓_云淡风轻.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")

--初始化位置和朝向
dark_all_actors()
situ:setPos(-400, 75)
situ:face_right()
qiliuge:setPos(1200, 75)
qiliuge:face_right()

qiliuge:spring_scale(1.5, 1, 1, 0.2)
qiliuge:say("嘿——吼——意修罡气，热火不侵。")
qiliuge:spring_scale(1.5, 1, 1, 0.2)
qiliuge:say("嘿——吼——六合八荒，五气朝元。")
wait_twn(situ:movetoX(800), situ:daze())
situ:say("六哥在练功呢？那不打扰了。")
qiliuge:flip()
qiliuge:say("没有没有，不知掌门过来，是有何吩咐？")
situ:say("如今门中凋零，虎视眈眈者大有人在。我却对这乱局却无从着手……")
qiliuge:say("掌门这是关心则乱，且先不说豪猪长垄，便是附近龙湾门之流也不容小觑。")
situ:say("正因如此，才更觉这江湖之事，实在棘手。")
qiliuge:say("掌门却不知，这“浑水摸鱼”也是一策妙计？")
situ:say("哦？此话怎讲？")
qiliuge:say("江湖大乱，却也是人人自危。掌门不妨趁此时机<color=red>养精蓄锐、招募人才</color>，以待时机？")
situ:say("是了，之前爹娘也常常叮嘱我要低调行事，厚积而薄发。到了此时，才明白这一片苦心……")
qiliuge:say("若看到掌门如此，他们一定很欣慰。")
situ:say("六哥能看到这一层，当真是老江湖了。")
qiliuge:say("哪里哪里，在下武功低微，也只好在这些事情上多用些心思了。")
situ:say("人各有长，六哥在守卫门派一项上便是大功，倒也不必过分在意功夫的事。")
qiliuge:say("正因如此，为了守护门派，在下才更需在武学上努力修炼！")
situ:say("唉，倒也不是……也罢，到底是六哥的心意难得！")

hide_all_stage_bubble()
change_favor_by_id("齐六哥", 1)

black_scene(0.25)
hide_stage()
set_flag("完成贴身老六")
light_scene(0.25)
