
show_stage("bg_219.png", "虎焰堂")
play_bgm("Music/舒缓_云淡风轻.wav", 0.1)
light_scene(0.2)

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local liuming = actor("刘明")
local zsniang = actor("朱三娘")

--初始化位置和朝向
bright_all_actors()
situ:setPos(-400, 75)
situ:face_right()
qiliuge:setPos(800, 75)
qiliuge:face_right()
liuming:setPos(1100, 75)
liuming:face_left()
zsniang:setPos(1300, 75)
zsniang:face_left()

qiliuge:emotion("NaoHuo")
wait_twn(situ:movetoX(500), situ:daze())

qiliuge:say("刘明、三娘，你们看看，这几个月的开销怎么越来越高了？")
liuming:say("这可真的冤枉啊，本来入了冬月便比前时冷，偏今年炭火更是紧得很，这才……")
zsniang:say("确实，我们伙房这边已经尽量节省了，但必要的开销还是避免不了。")
situ:say("哎呀，六哥，这些小钱何必这么计较呢？")
qiliuge:flip()
qiliuge:emotion()
qiliuge:say("掌门，这不是计较的问题。每个月都这么浪费，长此以往，怎么得了？")
situ:say("这些都是小账，不必太放在心上。")
liuming:say("是啊，省来省去，也没几个钱。")
qiliuge:flip()
qiliuge:say("这怎么能是小账？虽然单次数额不大，但积累起来就是一笔不小的开销。")
situ:say("六哥，你也不用这么小气……")
qiliuge:flip()
qiliuge:say("小气？")
liuming:say("是啊，为了区区一两银子，念叨个三五天，这不是小气是什么？")
qiliuge:say("算了，随你们吧。")
hide_all_stage_bubble()
wait_twn(qiliuge:jump(), qiliuge:movetoX(-500))
situ:say("哎，怎么这就走了？我还没说完呢，脾气倒是不小。")
zsniang:say("掌门，这件事情，其实也不能全怪齐总管。")
situ:say("算了，我就不管了，你们自己看着办吧。")

hide_all_stage_bubble()

change_favor_by_id("齐六哥", -1)

black_scene(0.25)
hide_stage()
set_flag("完成齐六哥剧情4")
light_scene(0.25)
