show_stage("bg_92.png", "万雀溪谷")
light_scene(0.2)
play_bgm("Music/回忆.wav")

local situ = actor("司徒来也")
local qiliuge = actor("齐六哥")
local shinv = actor("柔儿")
local wanhecheng = actor("万壑成")
local dingxuan = actor("丁宣")
local zhuhuaner = actor("朱鹮儿")

--初始化位置和朝向
bright_all_actors()
situ:setPos(500, 75)
situ:face_right()
qiliuge:setPos(200, 75)
qiliuge:face_right()
wanhecheng:setPos(1400, 75)
wanhecheng:face_left()
shinv:setOverrideName("柔儿")
shinv:setPos(1300, -500)
shinv:face_left()
dingxuan:setPos(1100, 75)
dingxuan:face_left()
zhuhuaner:setPos(800, 75)
zhuhuaner:face_right()

situ:say("万壑成！你的报应到了！")
wanhecheng:say("可恶！我费尽心机却还是败在你们手上！")
zhuhuaner:say("万壑成！是你丧尽天良，引得人神共愤，才有今日这般下场！")
dingxuan:say("就是就是！若不是你万壑成逆天改命，一意孤行，稻花村如何会毁于一旦？")
zhuhuaner:say("这里没你说话的份！")
dingxuan:say("哎呦——女侠说的是！可小的就一照看地界儿的，还望女侠看在同为稻花村人的份上，网开一面啊！")
zhuhuaner:say("呸！恩将仇报的叛徒！你还有什么脸面？")
dingxuan:say("哎呦！小的可冤枉啊！那都是——")
hide_all_stage_bubble()
dingxuan:movetoY(-600, 5000)
zhuhuaner:say("都是什么……这、这是……血？")
situ:say("怎么忽然就死了？万壑成！莫非是你杀人灭口？")
wanhecheng:say("哼……无知小儿，你又知道什么？这江湖中本就是弱肉强食，我不保全这溪谷，难道要让这样的美景沦落成虎焰门一般的下场？")
situ:say("你这话什么意思？")
wanhecheng:say("哈哈哈哈哈！看来(player:fname)雷什么都没对你讲啊……")
situ:say("讲什么？你到底知道什么？")
wanhecheng:say("你，是在找夜鸦吧？")
hide_all_stage_bubble()
local options = {
    "盯紧此人！切不可放过一丝线索！",
    "莫非是垂死狡辩？暂且听听也无妨！"
}
local idx = show_quick_selections(options)
switch(idx) {
    ["1"] = function()
        situ:say("你倒是消息灵通，想必你也清楚，了解的太多可不是什么好事！")
        wanhecheng:say("哈哈哈！你这小子倒也是个明白人！")
        zhuhuaner:say("你们含含糊糊说什么呢？")
        wanhecheng:say("现在想来，何止一个稻花村，只怕我这万雀溪谷，从一开始便已经被算计进去了……")
        zhuhuaner:say("你……你这话什么意思？")
        wanhecheng:say("对不起……害了你们稻花村……")
        hide_all_stage_bubble()
        wanhecheng:movetoY(-600, 5000)
        zhuhuaner:say("喂！喂喂！死、死了？怎么会这样！")
        situ:say("暗处的朋友！出来吧！")
        wait_twn(shinv:jumpTo(1500, 75))
        shinv:say("不愧是虎焰门掌门，当真有些手段！")
        situ:say("想不到如此柔弱的女子，竟如蛇蝎一般！")
        shinv:say("哈哈哈哈！掌门是什么时候开始怀疑柔儿的？")
        situ:say("我们攻上来的时候！")
        shinv:say("哦？柔儿哪里露了破绽？")
        situ:say("一个弱女子，总是能在不同的地方重遇，虽看起来是慌不择路，可未免太巧了些！")
        shinv:say("还不是那些废物没用？连个人都拦不住。")
        zhuhuaner:say("莫非刚刚那个神棍，还有万壑成，竟然都是你……")
        situ:say("你怂恿万壑成扩张溪谷，到底为了什么！")
        shinv:say("“地螺迂回，星曜北斗”，哎呀，虎焰门的小子认不出来，朱家妹子你还认不出来？")
        zhuhuaner:say("你是司南宫的人！")
        shinv:say("正是！只是可惜，若是平常，我倒愿意与几位交个朋友……不过现下，怕是要失陪了！")
        hide_all_stage_bubble()
        shinv:hide()
        zhuhuaner:say("站住！可恶！")
        situ:say("罢了！她能在我们眼皮底下取了丁宣和万壑成两条人命，功夫自然不好对付。日后我们再寻便是，只是不知这司南宫是什么来头？")
        zhuhuaner:say("这个我也只是听村里的老人们讲过，这溪谷之中水道密布，乃是司南宫的聚气之所……只是后来司南宫被夜鸦所毁，变成了如今司南地宫这一片废墟。")
        situ:say("若当真如此，只怕我们还要前往司南地宫一探究竟。")
    end,
    ["2"] = function()
        situ:say("你说什么？")
        wanhecheng:say("哈哈哈哈！虎焰门既已入局，便不可能有生路了！")
        zhuhuaner:say("神神叨叨说些什么？稻花村的账还没同你算清呢！")
        wanhecheng:say("稻花村？哈哈哈，是了！那个被献祭的村落……如今想来，这溪谷只怕也成了祭品了……")
        zhuhuaner:say("你……你这话什么意思？")
        situ:say("不好！莫非这其中另有隐情！留神暗箭伤人！")
        wanhecheng:say("啊——")
        hide_all_stage_bubble()
        wanhecheng:movetoY(-600, 5000)
        zhuhuaner:say("哎呀——哪里来的暗器？莫非刚刚那个神棍也是如此……")
        situ:say("正是……只是可惜我们太过大意，竟着了对方的道。")
        zhuhuaner:say("可恶……竟被对方抢了先。不过这等高明的功夫，这躲在暗处之人，到底是什么来头？")
        situ:say("不知道，但我想，这人利用万壑成，应当与溪谷、夜鸦都有些关联……")
        zhuhuaner:say("若是如此说来的话……")
        situ:say("鹮儿姑娘莫非知道些什么线索？")
        zhuhuaner:say("我也只是听村里的老人们讲过，这溪谷之中水道密布，乃是一处势力的聚气之所……只是后来那势力被夜鸦所毁，破败消亡了。")
        zhuhuaner:say("若是万雀溪谷被人利用，想必与那势力定有牵连！")
        situ:say("什么势力？")
        zhuhuaner:say("司南地宫！")
        situ:say("若当真如此，只怕我们还要前往司南地宫一探究竟。")
    end
}
destroy_menpai("万雀溪谷")

hide_all_stage_bubble()
black_scene(0.25)
hide_stage()
set_flag("完成万雀溪谷灭亡结局")
light_scene(0.25)
